cnti-testcatalog/testsuite

USAGE.md

- update tests in USAGE.md using To Do, PoC and :heavy_check_mark: 
How to use these:
- ToDo - This covers both not started and WIP items
- PoC - This covers items which are proof of concept/prototypes
- heavy_check_mark - this covers items which are on master and pass all QA, automated tests and any acceptance criteria
closes #95 
- https://github.com/cncf/cnf-conformance/issues/95
**Issue**

update USAGE using To Do, PoC and :heavy_check_mark: 

---

sample-cnfs/sample-coredns-cnf/cnf-conformance.yml
sample-cnfs/sample_coredns/cnf-conformance.yml
spec/configuration_lifecycle_spec.cr
src/tasks/configuration_lifecycle.cr

usage:
```
crystal src/cnf-conformance.cr rolling_update -- version_tag=latest
```
where version_tags value is a valid release name for the image set in
the helm chart's configuration
i.e. for the coredns stable chart
https://github.com/helm/charts/tree/master/stable/coredns#configuration
the image is `coredns/coredns`
and the version is `v1.6.7`
but any valid version tag from docker hub
https://hub.docker.com/r/coredns/coredns/tags
can be used
refs #7
- https://github.com/cncf/cnf-conformance/issues/NNN
**Issue**

rolling update conformance test

---

EXAMPLE-CNFS.md

The PROX engine is a DPDK application that performs packet operations in a highly configurable
manner and displays performance statistics.
Same image and engine can be used for various types of tests: as generator, swap/reflector or impair gateway.
More complex configurations would allow for prototyping other functionality.

[Example CNFs] Add PROX to Layer 2

---

INSTALL.md

Updated CNF Developer instructions to support using the new CNF setup and cleanup commands. Noted how to stop automatic deployment of CNF.
Fixes: #133 
**Issue**

Added CNF setup and cleanup instructions

---

example-cnfs/ip-forwarder/vpp/templates/configmap.yaml

Fixes a bug with deployment where default plugins are enabled by default.
#148 
**Issue**

Bugfix for VPP IP Forwarder example

---

src/tasks/installability.cr

- Adding ✔️ and ✖️  for pass/fail on published helm chart
- adding emoji for test
Ticket: https://github.com/cncf/cnf-conformance/issues/169
**Issue**

Adding emoji, 📊🖛 🌐, to  published helm chart test

---

src/tasks/installability.cr

- final emoji 📊⎯➤🌐
- switch to unicde line and error instead of emoji right arrow
- Unicode Character “⎯” (U+23AF)
- Unicode Character “➤” (U+27A4)
- added space before status emoji and PASSED or FAILED
Refs: #NNN
**Issue**

Using unicode ⎯➤ instead of emoji arrow in published helm chart test

---

example-cnfs/coredns/README.md
example-cnfs/coredns/cnf-conformance.yml

Adds CoreDNS as an example CNF with working cnf-conformance.yml and README on usage and description.
- #183

Adds CoreDNS as an example CNF

---

TEST-CATEGORIES.md
USAGE.md

nodeport_not_used test now available
Refs: ##165
- [] Added integration testing to cover
- [] New feature (non-breaking change which adds functionality)
**Issue**

nodeport_not_used test now available #165 documentation

---

README.md

Removing `develop` CI test badge

remove develop CI tests as `develop` is no longer used

---

src/tasks/installability.cr

#221 helm_deploy now uses a prefix for testing the deployment
Refs: #NNN
- [d] No updates required.
**Issue**

#221 helm_deploy now uses a prefix for testing the deployment

---

spec/fixtures/cnf-conformance-invalid-and-unmapped-keys.yml
src/tasks/installability.cr

usage
```
crystal src/cnf-conformance.cr validate_config cnf-config=./spec/fixtures/cnf-conformance-unmapped-keys.yml
```
Refs: #201
**Issue**

re: #201 add validate_config task

---

spec/utils/system_information/curl_spec.cr
spec/utils/system_information/kubectl_spec.cr
spec/utils/system_information/wget_spec.cr
src/tasks/utils/system_information/kubectl.cr

Kubectl client version can contains non-numeric symbols in its minor version. E. g.:
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
This exception causes that the regex used to discover information fails. This change addresses that scenario.
NA
**Issue**

Update regexp used by kubectl_version function

---

shard.yml

shard.yml was declaring 0.31.1 as the crystal version, but it was changed to the proper version - 0.33.0
Refs: #239 
**Issue**

#239 updated shard.yml to ensure correct version of crystal is used

---

example-cnfs/coredns/cnf-conformance.yml

Some clusters have Multus installed and kube-multus will need to be whitelisted.  This is the case in the beta test clusters.
Ref: #238 #232

Whitelisting kube-multus in CoreDNS example

---

points-all.yml
points.yml

- Non-implemnted tests are commented out since they affect the score
- Set source ip address test to not give points if it passes since the
final score is confusing
ref: #232, #181, #251

Updated points.yml to only have implemented tests enabled

---

src/tasks/utils/sample_utils.cr

Updated deployment output to use logger so it can be turned off for in non-verbose modes (eg. INFO and DEBUG).
hotfix for beta release

BUGFIX: Deployment wait output now using logger

---

src/tasks/utils/sample_utils.cr

Updated deployment output to use logger so it can be turned off for in non-verbose modes (eg. INFO and DEBUG).

Deployment wait output to make defaults quieter

---

.gitignore
spec/utils/utils_spec.cr
src/cnf-conformance.cr
src/tasks/cleanup.cr
src/tasks/setup.cr
src/tasks/utils/sample_utils.cr
src/tasks/utils/utils.cr

Update how and when results are saved so a repeated warning for overwriting results.yml does not occur
Refs: #282
**Issue**

Update how and when results are saved so a repeated warning for overwriting results.yml does not occur

---

src/tasks/microservice.cr

Since full size of an image is retrieved in bytes, then `50 000 000` is only 50mb, but the comment says it should be less than 5gb.
Refs: #NNN
**Issue**

Fix docker image size check

---

curl_install.sh

#301 curl now supports new cnf-conformance binary names
#301 curl now supports new cnf-conformance binary names
Refs: #301 
**Issue**

#301 curl now supports new cnf-conformance binary names

---

src/tasks/resilience.cr

Because chaos-mesh is now a CNCF sandbox project with its own domain, the CRD of chaos-mesh have been changed ([in this commit](https://github.com/chaos-mesh/chaos-mesh/commit/26ec8ddc5a65566b8160852280b30bdbf1cb6895),
As a result, we have an inconcistency in the `resilience.cr` file, where we install `chaos-mesh` version `v0.8.0`, but we uninstall the latest version of the chaos-mesh repository (master)
This commit simply updates the repository URL and fixes a consistent chaos-mesh version through a constant in the `resilience.cr` file.
**Issue**

Fix chaos-mesh version through constant and update repository URL

---

spec/utils/release_manager_spec.cr

#362 release manager now disabled for pull requests
#362 release manager now disabled for pull requests
Refs: #362
**Issue**

#362 release manager spec tests now disabled for pull requests 

---

INSTALL.md
sam.cr
src/tasks/utils/release_manager.cr
src/tasks/utils/utils.cr

(ab)uses method missings to move us off of `logger` and on to `log`
partial refactor to remove logger deprecation warnings ... …
though I don't really love it because it (ab)uses method_missing
so I make seperate pr
also it only buys us a little bit because several of our dependancies
are still using the deprecated logger ... so we don't even get rid of
all dep warnings
Refs: #311 
**Issue**

Maint/upgrade crystal to 0.35.1 logging refactor

---

src/tasks/utils/sample_utils.cr

Without this fix, wait_for_install waits for at least one replica to be ready. However for a deployment of a CNF with multiple replicas, we need to wait for all replicas to be in the ready state before declaring it 'installed'.
At least this is what is assumed by the `chaos_container_kill` test, which uses the `wait_for_install` method to check that after a pod is killed, a new one is spawned to match the number of desired replicas.
In the previous version of the function, when there are more than 1 replica (e.g. with the `envoy` example), the test does not wait and produces a wrong result.

make wait_for_install wait on all replicas

---

spec/platform/hardware_and_scheduler.cr
spec/platform/platform_spec.cr
src/tasks/utils/utils.cr

Add support for running platform tests without a workload cnf 
Refs: ##365
**Issue**

#365 Add support for running platform tests without a workload cnf 

---

USAGE.md
src/cnf-conformance.cr

also documentation
implements tab completion. 
works wit the binary very well. that is `./cnf-conformance <TAB> <TAB>`
wish I could get it work with source  ie. `crystal src/cnf-conformance.cr <TAB> <TAB>`
but that is a whole can of worms that turns a 3 pter into an 8.
So we can just use the bin to get the names and copy pasta
Refs: #265 
**Issue**

poc of tab_completion

---

spec/spec_helper.cr

Specs now do not have the initial 3 warnings
**Issue**

Specs now do not have the initial 3 warnings

---

src/tasks/utils/release_manager.cr

#348 release date now has command behind day
Refs: #348
**Issue**

#348 release date now has command behind day

---

spec/platform/cluster_api_spec.cr
src/tasks/cluster_api_setup.cr
src/tasks/platform/platform.cr

#328 cluster api now has a negative test
328 cluster api now has a negative test
Refs: #328
**Issue**

#328 cluster api now has a negative test

---

.github/workflows/actions.yml
example-cnfs/nsm/README.md

The build should not be triggered for documentation changes #478
Refs: #478
**Issue**

The build should not be triggered for documentation changes #478

---

sample-cnfs/k8s-sidecar-container-pattern/cnf-conformance.yml
src/tasks/utils/docker_client.cr
src/tasks/utils/kubectl_client.cr

#485 sidecar container example now uses tag 1.16.0
Refs: #485
**Issue**

#485 sidecar container example now uses tag 1.16.0

---

src/tasks/utils/release_manager.cr

#release manager now uses first entry in rev-parse
release manager now uses first entry in rev-parse
Refs: #NNN
**Issue**

release manager now uses first entry in rev-parse

---

src/tasks/utils/release_manager.cr

release manager git tag now scrapes git status
Refs: #NNN
**Issue**

release manager git tag now scrapes git status

---

TEST-CATEGORIES.md
USAGE.md

Missing doc updates for #82
--
Refs: #82 
**Issue**

Updated test-cat and usage to include rollback (rolling_downgrade)

---

points.yml
spec/utils/utils_spec.cr
spec/workload/resilience/pod_network_latency_spec.cr
src/tasks/cleanup.cr
src/tasks/litmus_cleanup.cr
src/tasks/litmus_setup.cr
src/tasks/litmuschaos_setup.cr
src/tasks/workload/resilience.cr

Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
- This PR adds a litmus test to check the resiliency of the CNF application when subject to network latency for a certain chaos duration. 
Refs: 
- [Resilience test: is CNF healthy after pod-network-latency Litmus Chaos test? #520](https://github.com/cncf/cnf-conformance/issues/520)
- EPIC to add various litmus probes: https://github.com/cncf/cnf-conformance/issues/499
**Issue**

Feat(resiliency): Add litmus pod network latency test

---

.github/workflows/actions.yml
sample-cnfs/sample-local-storage/cnf-conformance.yml
sample-cnfs/sample-statefulset-cnf/README.md
sample-cnfs/sample-statefulset-cnf/cnf-conformance.yml
spec/cnf_conformance_all/cnf_conformance_spec.cr
spec/fixtures/cnf-conformance.yml
spec/utils/cnf_manager_spec.cr
spec/utils/utils_spec.cr
spec/workload/security_spec.cr
src/cnf-conformance.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/helm.cr
src/tasks/utils/kubectl_client.cr
src/tasks/utils/release_manager.cr
src/tasks/utils/utils.cr
src/tasks/workload/configuration_lifecycle.cr
src/tasks/workload/microservice.cr
src/tasks/workload/resilience.cr
src/tasks/workload/scalability.cr
src/tasks/workload/security.cr
src/tasks/workload/statelessness.cr

Add support for additional K8s workload resource kinds: Pod, ReplicaSet, StatefulSet, Daemonset #531
Refs: #531
**Issue**

Add support for additional K8s workload resource kinds: Pod, ReplicaSet, StatefulSet, Daemonset #531

---

INSTALL.md

Current link goes to /releases which means the user will have to wade through all of the dev snapshots.  This update links to https://github.com/cncf/cnf-conformance/releases/latest for the latest stable release

Link to releases/latest for binary download

---

USAGE.md
spec/cnf_conformance_all/cnf_conformance_spec.cr
spec/utils/utils_spec.cr
spec/workload/installability_spec.cr
spec/workload/microservice_spec.cr
src/tasks/platform/resilience.cr
src/tasks/workload/installability.cr
src/tasks/workload/microservice.cr

[Enhancement] Add existing destructive flag to the `reasonable_startup_time` and `helm_deploy` tests #562
Refs: #562
**Issue**

[Enhancement] Add existing destructive flag to the `reasonable_startup_time` and `helm_deploy` tests #562

---

spec/platform/platform_spec.cr
spec/utils/cnf_manager_spec.cr
spec/utils/utils_spec.cr
spec/workload/configuration_lifecycle_spec.cr
spec/workload/installability_spec.cr
spec/workload/scalability_spec.cr
spec/workload/security_spec.cr
src/cnf-conformance.cr
src/tasks/cnf_setup.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/helm.cr
src/tasks/utils/utils.cr

[BUG] After running cnf_setup, cnf-conformance errors "you must provide cnf-config or cnf-path" when running tests after the setup. #572

---

src/tasks/utils/release_manager.cr

[Feature] Add the date or a date+time to the dev snapshots tag for auto sorting on GitHub release page #530
Refs: ##530
**Issue**

[Feature] Add the date or a date+time to the dev snapshots tag for auto sorting on GitHub release page #530

---

src/cnf-conformance.cr
src/tasks/chaos_mesh_setup.cr
src/tasks/cnf_setup.cr
src/tasks/constants.cr
src/tasks/helmenv_setup.cr
src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/utils/embedded_file_manager.cr
src/tasks/utils/helm.cr
src/tasks/utils/utils.cr
src/tasks/workload/configuration_lifecycle.cr
src/tasks/workload/resilience.cr
src/tasks/workload/scalability.cr
src/tasks/workload/security.cr
src/tasks/workload/statelessness.cr

[Feature] cnf_manager references to kubectl get should be moved to KubectlClient Module #590
Refs: #590
**Issue**

[Feature] cnf_manager references to kubectl get should be moved to KubectlClient Module

---

sample-cnfs/sample_immutable_configmap_some/chart/templates/configmap-test-not-immutable.yaml

Patch suggestion for yaml parsing error on `sample-cnfs/sample_immutable_configmap_some/chart/templates/configmap-test-not-immutable.yaml` that was erroring during `cnf_setup` 
Refs: #508
https://github.com/cncf/cnf-conformance/issues/508#issuecomment-778501963
**Issue**

[PATCH] Fix for 'converting YAML to JSON error' during cnf_setup for immutable_configmap

---

src/tasks/workload/resilience.cr

Fix bug causing the Litmus Network Latency test to fail.
Refs: cncf/cnf-conformance#636
**Issue**

Fix bug causing the Litmus Network Latency test to fail cncf/cnf-conformance#636

---

sample-cnfs/sample_local_registry_org_image/README.md
sample-cnfs/sample_local_registry_org_image/chart/.helmignore
sample-cnfs/sample_local_registry_org_image/chart/Chart.yaml
sample-cnfs/sample_local_registry_org_image/chart/README.md
sample-cnfs/sample_local_registry_org_image/chart/templates/NOTES.txt
sample-cnfs/sample_local_registry_org_image/chart/templates/_helpers.tpl
sample-cnfs/sample_local_registry_org_image/chart/templates/clusterrole-autoscaler.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/clusterrole.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/clusterrolebinding-autoscaler.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/clusterrolebinding.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/configmap-autoscaler.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/configmap.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/deployment-autoscaler.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/deployment.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/poddisruptionbudget.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/podsecuritypolicy.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/service-metrics.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/service.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/serviceaccount-autoscaler.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/serviceaccount.yaml
sample-cnfs/sample_local_registry_org_image/chart/templates/servicemonitor.yaml
sample-cnfs/sample_local_registry_org_image/chart/values.yaml
sample-cnfs/sample_local_registry_org_image/cnf-conformance.yml
spec/workload/microservice_spec.cr
src/tasks/utils/docker_client.cr
src/tasks/workload/microservice.cr

#619 registry port now uses the full k8s container image. 
#619 registry port now uses the full k8s container image. 
Refs: #619
**Issue**

#619 registry port now uses the full k8s container image. 

---

.gitignore
sample-cnfs/sample_local_registry/cnf-conformance.yml
spec/workload/configuration_lifecycle_spec.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/helm.cr
src/tasks/utils/kubectl_client.cr
src/tasks/workload/configuration_lifecycle.cr
src/tasks/workload/microservice.cr

[BUG] rollback, rolling_version_change tests do not handle images that use a local registry with port
Refs: #635
**Issue**

[BUG] rollback, rolling_version_change tests do not handle images that use a local registry with port

---

spec/cnf_conformance_all/cnf_conformance_spec.cr
src/tasks/dockerd_setup.cr
src/tasks/utils/utils.cr
src/tasks/workload/microservice.cr

[BUG] reasonable_image_size test should not fail if dockerd is not installed or if docker command fails
Refs: #645
**Issue**

[BUG] reasonable_image_size test should not fail if dockerd is not installed or if docker command fails

---

USAGE.md
points.yml
scoring_config/points_v1.yml
spec/cnf_conformance_all/cnf_conformance_config_lifecycle_spec.cr
spec/cnf_conformance_all/cnf_conformance_microservice_spec.cr
spec/cnf_conformance_all/cnf_conformance_spec.cr
spec/utils/cnf_manager_spec.cr
spec/workload/resilience/disk_fill_spec.cr
src/tasks/litmus_cleanup.cr
src/tasks/litmus_setup.cr
src/tasks/workload/resilience.cr

- This PR adds a litmus disk fill chaos experiment to check the resiliency of the CNF application when subject to disk stress for a certain amount of given memory either in the percentage of total ephemeral-storage limit or the memory in Mi unit. It can also be used to test the Ephemeral Storage Limits, to ensure those parameters are sufficient and the application's resiliency to disk stress/replica evictions. For More information checkout [experiment docs](https://docs.litmuschaos.io/docs/disk-fill/).
-  This PR also update the litmus version and pod network latency chaos version to`1.13.2` (which is the latest as of now).  
- Check out the test logs [here](https://github.com/cncf/cnf-conformance/issues/499#issuecomment-801415239).
Refs: #499 …

[Enhancement] Add disk fill chaos and pod network latency chaos version update #663

---

USAGE.md
points.yml
scoring_config/points_v1.yml
spec/cnf_conformance_all/cnf_conformance_config_lifecycle_spec.cr
spec/cnf_conformance_all/cnf_conformance_microservice_spec.cr
spec/cnf_conformance_all/cnf_conformance_spec.cr
spec/utils/cnf_manager_spec.cr
spec/workload/resilience/disk_fill_spec.cr
src/tasks/litmus_cleanup.cr
src/tasks/litmus_setup.cr
src/tasks/workload/resilience.cr

- This PR adds a litmus disk fill chaos experiment to check the resiliency of the CNF application when subject to disk stress for a certain amount of given memory either in the percentage of total ephemeral-storage limit or the memory in Mi unit. It can also be used to test the Ephemeral Storage Limits, to ensure those parameters are sufficient and the application's resiliency to disk stress/replica evictions. For More information checkout [experiment docs](https://docs.litmuschaos.io/docs/disk-fill/).
-  This PR also update the litmus version and pod network latency chaos version to`1.13.2` (which is the latest as of now).  
- Check out the test logs [here](https://github.com/cncf/cnf-conformance/issues/499#issuecomment-801415239).
Refs: #499 …

Feat(resiliency): Add litmus disk fill chaos test

---

spec/utils/cnf_manager_spec.cr
src/tasks/utils/points.cr

[BUG] tags for points.yml scores are getting added for workload reslilience tests when they're tagged as platform:resilience
Refs: #701
**Issue**

[BUG] tags for points.yml scores are getting added for workload reslilience tests when they're tagged as platform:resilience

---

src/tasks/utils/cnf_manager.cr

[BUG] Debug type output is displayed when LOG_LEVEL=error
[BUG] Debug type output is displayed when LOG_LEVEL=error
Refs: #580
**Issue**

[BUG] Debug type output is displayed when LOG_LEVEL=error

---

src/tasks/dockerd_setup.cr
src/tasks/utils/points.cr

[BUG] dockerd failed error when dockerd pod already installed on cluster #686
Refs: #686
**Issue**

[BUG] dockerd failed error when dockerd pod already installed on cluster #686

---

INSTALL.md
README.md
SOURCE_INSTALL.md

Using cnf-testsuite instead of cnf-conformance for urls in installation docs.
Note:
- Does not update code.
- Does not change the commands to run.
Refs: #555 
**Issue**

updated quick install links for download

---

spec/workload/installability_spec.cr
src/tasks/utils/cnf_manager.cr
src/tasks/workload/installability.cr
src/tasks/workload/microservice.cr

Refactor helm_deploy to use data from initial test suite CNF deployment and no longer do a new deployment
Refs: #564
**Issue**

Refactor helm_deploy to use data from initial test suite CNF deployment and no longer do a new deployment

---

.github/workflows/actions.yml

Fix bug causing binary tests to run for documentation only changes.
Refs: cncf/cnf-testsuite#734
**Issue**

Fix bug causing binary tests to run for documentation only changes 

---

curl_install.sh
spec/curl_install_spec.cr

Update curl install script to give a non-zero exit code on failures.
Refs: cncf/cnf-testsuite#741
**Issue**

Update curl install script to give a non-zero exit code on failures

---

src/cnf-testsuite.cr

Use full binary execution path for running the help command 
Refs: cncf/cnf-testsuite#746
**Issue**

Use full binary execution path for running the help command 

---

config.yml

was set to info which has debug info. Change in config.yml locally or
via LOG_LEVEL=<LOG_LEVEL_NAME> eg. LOG_LEVEL=info
make it less noisy for default checkouts of config.yml
note:  #764 goes into creating the config.yml at runtime and not having in repo
Refs: #764 
**Issue**

Set default log level to error

---

example-cnfs/coredns/cnf-testsuite.yml

Fixes the output during `cnf_setup` of the example cnf yml: `rm: cannot remove '/home/taylor/workspace/taylor/cnfs/coredns/configmap_test.yml': No such file  or directory`
Refs: #776 
**Issue**

Fixed the example cnf-testsuite.yml as it was outdated

---

curl_install.sh

remove -v option so tar output is not shown
Refs: #745 
**Issue**

remove verbose option from tar

---

spec/setup_spec.cr
src/tasks/cnf_setup.cr
src/tasks/utils/airgap.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/generate_config.cr
src/tasks/utils/helm.cr
src/tasks/utils/kubectl_client.cr

cnf_setup manifest should populate the exported_chart directory and export a temp_template file
Refs: #827
**Issue**

cnf_setup manifest should populate the exported_chart directory and export a temp_template file

---

.github/workflows/actions.yml
spec/prereqs_spec.cr
spec/utils/system_information/kubectl_spec.cr
src/tasks/prereqs.cr
src/tasks/utils/system_information/kubectl.cr

Checks that the kubectl client is not lagging behind the server by more than 3 minor versions.
**Output after changes**
```
$ ./cnf-testsuite prereqs verbose
No Global helm version found
Local helm found. Version: v3.1.1
Global kubectl found. Version: 1.21
Global kubectl client is not more than 3 minor versions behind server version
No Local kubectl version found
Global git found. Version: 2.17.1
No Local git version found
All prerequisites found.
$ ./cnf-testsuite prereqs verbose offline=1
No Global helm version found
Local helm found. Version: v3.1.1
Global kubectl found. Version: 1.21
Global kubectl client is not more than 3 minor versions behind server version
No Local kubectl version found
All prerequisites found.
```
* Add acceptable_kubectl_version?() to compare server and client …

[Fix #761] Check if kubectl is within 3 minor versions of server

---

USAGE.md
spec/cnf_testsuite_all/cnf_testsuite_config_lifecycle_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_microservice_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_spec.cr
spec/workload/resilience/pod_delete_spec.cr
src/tasks/litmus_cleanup.cr
src/tasks/litmus_setup.cr
src/tasks/workload/resilience.cr

This PR contains:
- Add litmus pod delete experiment to test suite - https://docs.litmuschaos.io/docs/pod-delete/
- Add timeout for the tests based on the TCD (total chaos duration) of the experiment.
- Fix the test result output.
- Update litmus to the latest version (as of now) 1.13.6.
About pod delete and why do we need it?
- Pod Delete experiment tests the deployment sanity that is the replica availability & uninterrupted service and recovery workflow of the application. The experiment causes (forced/graceful) pod failure of specific or random replicas of application resources. This will help to test if the CNF application is servive the `pod delete` chaos injection.
Refs: https://github.com/cncf/cnf-testsuite/issues/499 && …

Feat(Resiliency): Add litmus pod delete experiment, timeout for tests and fix test result output

---

spec/prereqs_spec.cr
spec/utils/system_information/kubectl_spec.cr
src/tasks/prereqs.cr
src/tasks/utils/system_information/kubectl.cr

This PR is based on @agentpoyo's feedback on #761 for the earlier PR.
**Summary of changes:**
* Version check respects [Kubernetes version skew policy for kubectl](https://kubernetes.io/releases/version-skew-policy/)
* Warnings are only displayed incase the version check fails - so stdout doesn't get extra messages
* Adds explicitly check for missing server version and hint that the server config might be missing
* Adds explicit check for `offline` flag. Previously this was just a hint at air-gapped mode.
The test scenarios below directly use the `prereqs` task that is run when `setup` is invoked.
* kubectl v1.15 and server v1.17
* **Output**: Warns about version incompatibility.
* kubectl v1.16 and server v1.17
* **Output**: No warning about version incompatibility.
* kubectl v1.17 and …

Improvements to #761 to respect kubernetes version skew policy

---

.github/ISSUE_TEMPLATE/new-platform-test.md
.github/ISSUE_TEMPLATE/new-workload-test.md
PSEUDO-CODE.md
README.md
TEST-CATEGORIES.md
USAGE.md
embedded_files/points.yml
points-all.yml
spec/cnf_testsuite_all/cnf_testsuite_container_chaos_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_network_chaos_spec.cr
spec/workload/statelessness_spec.cr
src/cnf-testsuite.cr
src/tasks/workload/statelessness.cr

* Renames "statelessness" to "state" in both code and docs
* Verified non-existence of statelessness across repo by grepping for statelessness `grep -nri "statelessness" .`
* Build is green (atleast the build for the branch I was pushing to)
Refs: #744 and #264 

Rename statelessness to state to fix #744 and #264

---

spec/setup_spec.cr
spec/utils/cnf_manager_spec.cr
src/tasks/cnf_setup.cr
src/tasks/utils/cnf_manager.cr

1. `cnf_setup` task should respect `cnf-config` option as an alias to `cnf-path` option
2. `cnf_cleanup` task should respect `cnf-config` option as an alias to `cnf-path` option
3. Added tests for both [1] and [2]
> Only [1] fixes an issue reported on #634. But I've added [2] is an extra after reviewing how `cnf_cleanup` behaves.
* In the `cnf_setup` task, there's a call to `CNFManager.sample_setup_cli_args` to process the args to the task and return a hash.
* Along with other keys/options, this helper function returns an `extended_config_file` key. The value of this key was the output of calling `File.dirname` on the config path.
* In the `cnf_setup` task, the call to `AirGap.generate_cnf_setup` is passed the `extended_config_file` key.
**Change:** Pass `config_file` to …

[bug/634]: cnf_setup and cnf_cleanup should respect cnf-config option as an alias to cnf-path option

---

spec/utils/system_information/kubectl_spec.cr
src/tasks/utils/system_information/kubectl.cr
src/tasks/utils/utils.cr

* Adds support for running the testsuite on microk8s. #824 
* This is done by stripping off the "+" signs from microk8s kubectl and server versions during version checks.
Changes to following tasks:
* `prereqs`
* `cnf_setup`
Also adds appropriate tests for `acceptable_kubectl_version?/2` to support the microk8s scenario.
```shell
$ microk8s config > microk8s.config
$ export KUBECONFIG="$(pwd)/microk8s.config"
$ sudo snap alias microk8s.kubectl kubectl
Added:
- microk8s.kubectl as kubectl
```
**Reproduce issue**
```shell
$ PATH="/snap/bin:$PATH" ./cnf-testsuite prereqs
No Global helm version found
Local helm found. Version: v3.1.1
Global kubectl found. Version: 1.21+
../../../../.crenv/versions/0.35.1/share/crystal/src/string.cr:424:5 in 'to_i32' …
```

Adds support for running the testsuite on microk8s

---

USAGE.md
spec/cnf_testsuite_all/cnf_testsuite_config_lifecycle_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_microservice_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_spec.cr
spec/workload/resilience/pod_memory_hog_spec.cr
src/tasks/litmus_cleanup.cr
src/tasks/litmus_setup.cr
src/tasks/workload/resilience.cr

Signed-off-by: Jonsy13 <vedant.shrotria@chaosnative.com>
This PR contains:
- Add litmus pod memory hog experiment to test suite - https://docs.litmuschaos.io/docs/pod-memory-hog/
- Update litmus to the latest version (as of now) 1.13.8.
About pod memory hog and why do we need it?
Pod Memory Hog simulates conditions where cnf application pods experience Memory spikes either due to expected/undesired processes thereby testing how the overall application stack behaves when this occurs. This will help to test if the CNF application survives the pod memory hog chaos injection.
Refs: #NNN
**Issue**

Feat(Resiliency): Add litmus pod memory hog experiment.

---

USAGE.md
spec/cnf_testsuite_all/cnf_testsuite_config_lifecycle_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_microservice_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_spec.cr
spec/workload/resilience/pod_io_stress_spec.cr
src/tasks/workload/resilience.cr

@agentpoyo (Drew): Fixed conflicts and pushed branch to verify github action tests.
- Add litmus pod io stress experiment to cnf testsuite.
- Docs for the experiment - https://docs.litmuschaos.io/docs/pod-io-stress/
- This experiment causes filesystem IO stress on the application pod by providing the total percentage of available memory or by providing the memory value in GB.
- The application pod should be healthy once chaos is stopped. The expectation is that service requests should be served despite the chaos.
Refs: https://github.com/cncf/cnf-testsuite/issues/499 && https://github.com/cncf/cnf-testsuite/issues/901
**Issue**

Feature (Resiliency): Add litmus pod io stress experiment

---

USAGE.md
spec/cnf_testsuite_all/cnf_testsuite_config_lifecycle_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_microservice_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_spec.cr
spec/workload/resilience/pod_io_stress_spec.cr
src/tasks/workload/resilience.cr

- Add litmus pod io stress experiment to cnf testsuite.
- Docs for the experiment - https://docs.litmuschaos.io/docs/pod-io-stress/
- This experiment causes filesystem IO stress on the application pod by providing the total percentage of available memory or by providing the memory value in GB.
- The application pod should be healthy once chaos is stopped. The expectation is that service requests should be served despite the chaos.
Refs: https://github.com/cncf/cnf-testsuite/issues/499 && https://github.com/cncf/cnf-testsuite/issues/901
**Issue**

Feat(Resiliency): Add litmus pod io stress experiment

---

USAGE.md

This PR will add a brief usage of the litmus experiments in the resiliency category. The docs are added for:
- pod memory hog
- pod io stess
Refs: https://github.com/cncf/cnf-testsuite/issues/929
**Issue**

Chore(docs): Add docs for pod memory and io experiment

---

utils/kubectl_client/kubectl_client.cr

This PR includes some changes to the `KubectlClient` module
* Adds KubectlClient::ShellCmd to run system commands
* Uses the new ShellCmd module in
* exec, cp and server_version functions
* Apply, Annotate, Delete and Rollout modules
* KubectlClient::Set.image helper function
* KubectlClient::Get module for pods and nodes helpers
* Adds new helpers to use in future PRs
* KubectlClient::Get.namespaces helper
* Create and Scale helper modules
Reason for adding Create module is for the new helper to allow creating other resources like namespaces.
Refs: #307 
**Issue**

[bug/307] Remove backticks and legacy log lines: Part-4 (Changes to KubectlClient)

---

utils/kubectl_client/kubectl_client.cr

* Add replica_count/4 and use it to slim down resource_wait_for_install/4
* Replace usage of some legacy logging wrappers
* Replace backticks in below helpers in KubectlClient::Get
* deployment/1
* resource/2
* save_manifest/2
* deployments/1
* secrets/0
* configmaps/0
* configmap/1
* resource_ready?/3
* replica_count/4
* wait_for_install_by_apply/2
* resource_desired_is_available/2
* node_status/1
* desired_is_available?/1
* pod_status/1
Removes backticks and legacy log lines
Refs: #307
**Issue**

Changes to KubectlClient::Get for bug/307

---

USAGE.md
spec/cnf_testsuite_all/cnf_testsuite_config_lifecycle_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_microservice_spec.cr
spec/workload/resilience/pod_network_corruption_spec.cr
src/tasks/litmus_cleanup.cr
src/tasks/litmus_setup.cr
src/tasks/workload/resilience.cr

- Add Litmus Pod Network Corruption Experiment
- Pod Network Corruption Injects packet corruption on the specified container by starting a traffic control (tc) process with netem rules to add egress packet corruption. The application can test the CNF application's resilience to a lossy/flaky networks.
- Update Litmus to the latest version as of now which is 2.0.0
- Update litmus docs link to point the latest docs.
Refs: https://github.com/cncf/cnf-testsuite/issues/499 && https://github.com/cncf/cnf-testsuite/issues/956
**Issue**

Feat(Resiliency): Add litmus pod network corruption experiment and update litmus version to latest

---

.github/workflows/actions.yml
utils/kubectl_client/kubectl_client.cr

The platform:observability test currently has a bug where the cnf gets initialised too quickly and reports the desired replicas as 0, subsequently resulting in the cnf being incorrectly reported as 'running', causing the spec to fail. This PR fixes this bug by updating the 'ready' check to also watch for 'unavailable' replicas, and if any are found to keep looping.
Refs: cncf/cnf-testsuite#971 
**Issue**

Fix bug with the platform:observability test. #971

---

USAGE.md
spec/cnf_testsuite_all/cnf_testsuite_config_lifecycle_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_microservice_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_spec.cr
spec/workload/resilience/pod_network_duplication_spec.cr
src/tasks/workload/resilience.cr

- Pod-network-duplication injects chaos to disrupt network connectivity of kubernetes pods. Causes Injection of network duplication on the specified CNF container by starting a traffic control (tc) process with netem rules to add egress delays. It Can test the CNF application's resilience to duplicate networks.
Refs: https://github.com/cncf/cnf-testsuite/issues/499 && https://github.com/cncf/cnf-testsuite/issues/958
**Issue**

Feat(Resiliency): Add litmus pod network duplication experiment

---

spec/platform/observability_spec.cr
src/cnf-testsuite.cr
src/tasks/cluster_api_setup.cr
src/tasks/cri_setup.cr
src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr
src/tasks/workload/configuration_lifecycle.cr
src/tasks/workload/resilience.cr

* Replace backticks with Process.run in configuration_lifecycle.cr and resilience.cr
* Move namespace deletion to the ensure block to avoid clashing with the Task runner return type
Fix issues with cluster_api_setup
* Once the commands are run, cd back to current dir.
* Remove duplicate KubectlClient::Apply.file line (wait_for_instlal_by_apply already runs apply).
* When control planes is fetched, convert the output to string before parsing json.
* #307
* #987
**Issue**

[bug/307] Updates to platform.cr and configuration_lifecycle.cr

---

src/tasks/workload/statelessness.cr

State task was not running the no_local_volume_configuration test. This fixes it by adding the test/task as a dependency of the state test.
Refs: #984
**Issue**

Run no_local_volume_configuration as a dependency for state workload task

---

USAGE.md

Added the ingress and egress blocked description and remediation steps in the USAGE doc.
This is a PR to merge into #1063 pull request.
Refs: #1029
**Issue**

USAGE doc update for ingress egress blocked PR

---

USAGE.md

Added description and remediation dropdown details for kubescape tests
Refs: #1043 , #1075
**Issue**

Documenation/1043 Added description and remediation detail dropdowns for tests in USAGE

---

.github/workflows/actions.yml
spec/utils/release_manager_spec.cr
src/tasks/cleanup.cr
src/tasks/constants.cr
src/tasks/kubescape_setup.cr
src/tasks/utils/release_manager.cr

This PR contains two fixes.
* This replaces usage of `GH_USER` and `GH_TOKEN` secrets configured in the GitHub repo.
* This avoids having to use any personal GitHub token and does not require refreshing this token frequently to prevent build failures.
There are commented `curl` lines that have been updated in `actions.yml`. This was intentional to ensure that incase we use them it would still be valid. We could remove these commented lines later if we do not intend to use them.
This fix for kubescape download errors was required to get the build passing for the primary issue in the PR (1077)
([Example failing build for reference](https://github.com/cncf/cnf-testsuite/runs/4076895387?check_suite_focus=true))
* The `install_kubescape` task in the main branch depends on the …

Use GITHUB_TOKEN provided by GitHub Actions

---

src/tasks/workload/resilience.cr

If running cnf-testsuite workload test for the first time, falco is installed without issues to run the `non_root_user` test. When you run workload again without cleanup or reinstall of your CNF, workload fails and exits.
Refs: #1090 
**Issue**

BUG #1090 Removed disabled chaos mesh tests and added missing pod_network_corruption test

---

src/tasks/workload/observability.cr

* Identified #1099 when working on #41 (was fetching logs for a multi-container pod).
* Fixed #1099 in this PR by passing the `--all-containers` flag.
Refs: #1099 
**Issue**

[1099] Pass --all-containers when fetching logs for the log_output test

---

README.md

- Daylight savings time has ended
- Thursday contributor meetings change from starting at 14:15 UTC to starting at 15:15 UTC
Refs: N/A documentation 
**Issue**

Contributor meetings at 15:15 UTC

---

.github/workflows/actions.yml
src/tasks/kind_setup.cr

This fixes the kind path on cluster deletion during the cni_compatible test
This also applies airgap CI fixes that were committed in https://github.com/cncf/cnf-testsuite/tree/feature/%231064-cni-airgap
Refs: #1106
**Issue**

[BUG] #1106 CNI kind delete cluster tools binary PATH error

---

USAGE.md

Need to add missing details for USAGE for `tracing` and `elastic_volume` tests.
Refs: #1149 #1150 #1081 #1025
**Issue**

[BUG] Documentation Updates to add missing desc USAGE

---

src/tasks/kind_setup.cr
src/tasks/utils/utils.cr
src/tasks/workload/compatibility.cr
utils/kubectl_client/kubectl_client.cr

This PR contains code contributions to resolve multiple issues (mentioned below).
* Move to an object-based usage pattern to allow for holding paths as state.
* Add helper to wait for cluster nodes to be ready.
* Rename `KindManager.wait_for_cluster` to `KindManager#wait_until_pods_ready`. This update would impact cni_compatible test.
* Update `cni_compatible` test to use the new KindManager interface.
* Additionally, refactor `cni_compatible` test abstract out cilium and calico setup as functions.
* Add `ensure_kubeconfig!` helper to utils (helper to be re-used for issue-41).
`KubectlClient.wait_until_pods_ready` now counts pods that have multiple instances separately.
This helps be able to detect pod readiness correctly.
* For pod readiness, check pods in all namespaces instead of just …

Improvements to resolve 1151, 1152, 1156 and 1157

---

USAGE.md
embedded_files/points.yml
spec/utils/cnf_manager_spec.cr
spec/workload/microservice_spec.cr
src/tasks/workload/microservice.cr
utils/kubectl_client/kubectl_client.cr

This PR:
* Adds new `service_discovery` test to microservice category (pass: 5pts, fail: 0pts)
* Updates documentation for the test
* Updates points.yml
* Adds appropriate positive and negative spec tests
A previous implementation of this test required an endpoints helper in KubectlClient. I've retained it as is for the future.
This CNF has a service that exposes a pod and should pass.
This CNF has no service and should fail.
Refs: #1168
- [] Covered by existing integration testing
**Issue**

[1168] Add new service_discovery test to microservice category

---

src/tasks/cleanup.cr
src/tasks/cluster_setup.cr
src/tasks/setup.cr
src/tasks/utils/task.cr

* This change removes all installed CNFs when `samples_cleanup` task is run.
* Ensures that cluster-tools is removed when `tools_cleanup` is run.
Refs: #1079
**Issue**

[1079] Remove cleanup all CNFs when samples_cleanup is run

---

tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh

The github runner images were old with new API changes made. This was causing no spec jobs from running by grabbing available idle runners.
Discovered when pushing Ref #1165

[BUG] new runner image for gh actions to v2.287.1

---

embedded_files/points.yml
spec/utils/cnf_manager_spec.cr
src/tasks/utils/points.cr
src/tasks/workload/security.cr
utils/kubectl_client/kubectl_client.cr

* [687] Excludes skipped tests from maximum points calculation
* [687] Identified tests missing in points.yml and added them
* Moves Falco error logs from `puts` to `Log.info` to avoid cluttering test output
* The usual change from `LOGGING.info/debug` to `Log.info/debug`
Refs: #687 

[687] Resolves differences in test score and maximum points

---

spec/utils/kernel_introspection_spec.cr
spec/workload/microservice_spec.cr
spec/workload/registry_spec.cr
src/tasks/cluster_setup.cr
src/tasks/constants.cr
src/tasks/dockerd_setup.cr
src/tasks/platform/observability.cr
src/tasks/utils/cluster_utils.cr
src/tasks/utils/embedded_file_manager.cr
src/tasks/workload/microservice.cr

* Consolidate clustertools manifests into one as a a precursor to #1199.
* Consolidate helper functions from `ClusterToolsSetup` into `ClusterTools`. Replace usage across codebase appropriately.
* Consolidate kubectl create/apply/delete calls with helper functions from `KubectlClient` or `ClusterTools`.
* Identified and resolved issue with dockerd manifest when testing 1202 in a cleanroom dir.
That test will not pass due to the nature of the fix for 1209.
* Remove `LOGGING` wrapper for `KubectlClient.exec` - the helper is already capable of logging output on its own.
* Remove outdated & unused helper code from `dockerd_setup.cr`
Refs: #1202, #1209

[1202, 1209] Consolidate cluster tools manifests and resolve dockerd manifest issue

---

.gitignore
spec/platform/observability_spec.cr
spec/utils/k8s_instrumentation_spec.cr
spec/utils/utils_spec.cr
spec/workload/microservice_spec.cr
spec/workload/observability_spec.cr
spec/workload/registry_spec.cr
spec/workload/state_spec.cr
src/tasks/cnf_setup.cr
src/tasks/constants.cr
src/tasks/platform/observability.cr
src/tasks/setup.cr
src/tasks/utils/cluster_utils.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/k8s_instrumentation.cr
src/tasks/utils/kubescape.cr
src/tasks/utils/mysql.cr
src/tasks/workload/microservice.cr
src/tasks/workload/observability.cr
src/tasks/workload/state.cr
utils/kubectl_client/kubectl_client.cr

This PR moves cluster tools to different namespace to avoid residue cluster resources and third-party tools from affecting other tests. This PR also sets up the ground work for #1219
Create new testsuite namespace (`cnf-testsuite`) in the k8s cluster
* Defines a new constant `TESTSUITE_NAMESPACE`
* Adds `create_namespace` task as a dependency for `setup` and `cnf-setup` (fail-safe)
* Runs `setup` task in before_all for the following spec test groups.
* Observability platform spec tests
* Observability workload spec tests
* Microservice workload spec tests
* K8s Instrumentation spec tests
* Utils spec tests
* Also had to move Observability Workload tests into the describe block to ensure that they respect the `before_all` block.
Add namespace optional argument to the following and update …

[1199, 1220, 1221] Move cluster-tools to a separate namespace to avoid causing test failures

---

USAGE.md
spec/cnf_testsuite_all/cnf_testsuite_config_lifecycle_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_microservice_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_spec.cr
spec/workload/resilience/pod_dns_error_spec.cr
src/tasks/workload/resilience.cr
src/templates/chaos_templates/pod_dns_error.yml.ecr

Signed-off-by: Jonsy13 <vedant.shrotria@chaosnative.com>
**This PR contains:**
- Add litmus pod dns error experiment to test suite - https://litmuschaos.github.io/litmus/experiments/categories/pods/pod-dns-error/
**About pod dns error experiment and why do we need it?**
pod-dns-error injects chaos to disrupt dns resolution in kubernetes pods. It causes loss of access to services by blocking dns resolution of hostnames/domains. This will help to test if the CNF application survives the pod dns error chaos injection.
Refs: #NNN
**Issue**

Feat(Resiliency): Adding litmus pod dns error experiment

---

USAGE.md

Fixed URLs and small updates of CNI description.
Refs: #1243 #1244
**Issue**

[BUG] 1243 1244 usage doc URL and description fixes

---

RATIONALE.md

Additions to rational doc.
Refs: #1208 
**Issue**

security rationale now points to kubescape

---

spec/utils/cnf_manager_spec.cr
src/tasks/utils/cnf_manager.cr
tools/cluster-tools/Dockerfile
tools/cluster-tools/manifest.yml

Fix bug that causes cnf-setup to fail when a helm warning occurs.
Refs: cncf/cnf-testsuite#1275
**Issue**

Fix bug that causes cnf-setup to fail when a helm warning occurs.

---

USAGE.md
embedded_files/points.yml
sample-cnfs/sample_latest_tag/cnf-testsuite.yml
sample-cnfs/sample_latest_tag/manifests/pod.yml
spec/utils/cnf_manager_spec.cr
spec/workload/configuration_spec.cr
spec/workload/installability_spec.cr
spec/workload/security_spec.cr
src/tasks/cnf_setup.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/kyverno.cr
src/tasks/workload/configuration.cr
src/tasks/workload/microservice.cr
src/tasks/workload/observability.cr
src/tasks/workload/security.cr
src/tasks/workload/state.cr
utils/helm/helm.cr
utils/kubectl_client/kubectl_client.cr

* Add the following tests based on Kyverno:
* `default_namespace`
* `latest_tag`
* `selinux_options`
* Add spec tests for the above tests
* Add docs for the above tests
* Add the tests to points.yml
These changes prevent residue of CNFs installed for different spec tests from affecting subsequent tests.
* Add new `KubectlClient::Utils.wait_for_terminations` with reasoning in comments
* Add wait option for `KubectlClient::Delete.file`
* Update CNFManager.sample_cleanup to wait for resources to be deleted on cleanup.
* Add return types for `Helm.workload_resource_kind_names` and fix rabbit hole of type issues.
* `Helm.workload_resource_kind_names` should return namespace of the resource.
* `KubectClient::Get.resource_wait_for_install` should be passed the namespace name when called from …

[1272,1273,1274,1292] Add default_namespace, latest_tag and selinux_options tests based on Kyverno

---

docs/LIST_OF_TESTS.md

This document lists all tests as of the [v0.27.0 release](https://github.com/cncf/cnf-testsuite/releases/tag/v0.27.0)
Add document which lists all tests in releases with an overview of what they do.
Refs: #1306

List of tests as of release v0.27.0

---

docs/LIST_OF_TESTS.md

- add POC and expectation to K8s alpha API test
- ## [Kubernetes Alpha APIs - Proof of Concept](https://github.com/cncf/cnf-testsuite/blob/v0.27.0/src/tasks/workload/configuration.cr#L499)
- Expectation: CNF should not use Kubernetes alpha APIs
**What's tested:** This checks if a CNF uses Kubernetes alpha or unstable APIs
Refs: #1306 
**Issue**

add POC and expectation to K8s alpha API test

---

src/tasks/utils/utils.cr

Add points and max points when category task is run.
> Please ignore the bad formatting in the output. I resized my window and the output screen went bad. But the `maximum_points` and `points` fields are visible on the cat output in the right tmux pane.
> Test output is on the left pane. The right pane is the grep output for the `points` and `maximum_points` in the results file.
**Issue**

[#1301] Add points and max points when category task is run

---

embedded_files/points.yml
spec/workload/microservice_spec.cr
src/tasks/workload/configuration.cr
src/tasks/workload/microservice.cr
src/tasks/workload/reliability.cr
src/tasks/workload/security.cr

* `shared_database` should be run when microservice test category is run (#1323)
* `versioned_tag` test should be run when configuration category is run (#1324)
* `host_network` sholud be run when workload security is run (#1325)
* `service_account_mapping` should be run as a part of workload security (#1326)
* `pod_network_duplication` should be run as a part of resilience (#1330)
* `liveness` and `readiness` should be run as a part of resilience (#1331)
* Ship shared_database test if not MariaDB containers are found (#1342)
* Mark `pod_dns_error` under the `resilience` category in `points.yml` (#1343)
* Surround all Kyverno tests with `CNFManager::Task.task_runner` block (No ticket for this. Just added it for sanity)
Refs: #1323, #1324, #1325, #1326, #1330, #1331, #1342, #1343 …

[Fix points-related issues] Runs tests that were missed earlier

---

spec/workload/state_spec.cr
src/tasks/workload/state.cr

Refs: #1336
* The `elastic_volumes` will be skipped if the cnf does not used any volumes.
* Updated the message for test failure to be a bit more clear.
* Add spec test for skipped scenario.
* Skipped result: `sample-cnfs/sample_nonroot`
* Pass result: `sample-cnfs/sample-elastic-volume`
* Fail result: `sample-cnfs/sample-coredns-cnf`
**Issue**

[bug/1336] The `elastic_volumes` test should be skipped if the cnf does not use any volumes

---

src/tasks/litmus_setup.cr

The `puts` statements in LitmusManager causes unformatted white-colored output to be displayed.
* This PR removes the puts statement that was displaying unformatted output.
* Also replaces any other `puts` statements with calls to the `Log` module.
Refs: #1290
**Issue**

[bug/1290] Replace puts with log statements in LitmusManager

---

sample-cnfs/ndn-non-root-user/cnf-testsuite.yml
sample-cnfs/ndn-non-root-user/manifests/pod.yml
sample-cnfs/sample-ndn-privileged/cnf-testsuite.yml
sample-cnfs/sample-ndn-privileged/manifests/pod.yml
spec/cnf_testsuite_all/cnf_testsuite_spec.cr
spec/utils/utils_spec.cr
spec/workload/security_spec.cr
src/tasks/cleanup.cr
src/tasks/utils/cnf_manager.cr
src/tasks/workload/configuration.cr
src/tasks/workload/security.cr
utils/helm/helm.cr
utils/kubectl_client/kubectl_client.cr

> *Resolves #1387, #1386, #1375*
Adds support for security tests to test CNFs using non-default namespaces.
* Return the namespace for every resource as a part of the resource hash.
* The namespace returned must be the namespace as in the spec and not the default namespace assumed by the helper function.
* Update calls to `KubectlClient` helpers to pass a namespace arg.
> No A/C steps would be required for this. Any validation done for the `privileged` test would verify these CNFManager changes too.
* Added new sample CNF to test non-default namespaces `sample-ndn-privileged`
* Updated the test failure output to display the container's resource/pod name and namespace. This helps clarity.
* Commands added below to setup and test sample CNF that does not use default namespace.
* Update …

[1375, 1387, 1386] Add non-default namespace support for workload security tests

---

spec/utils/utils_spec.cr
spec/workload/installability_spec.cr
src/tasks/workload/compatibility.cr

This PR has the following changes:
* Removes requirement of destructive option for `helm_deploy` test.
* Update spec test for verbose logger because it uses the `helm_deploy` test.
Tested the changes with the following scenarios
* With no CNF installed.
* With the `sample_coredns` CNF installed.
```
./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample_coredns
./cnf-testsuite helm_deploy
```
Refs: #1445
**Issue**

[bug/1445] Remove requirement of destructive option for `helm_deploy` test

---

spec/utils/system_information/helm_spec.cr
src/tasks/helmenv_setup.cr
src/tasks/utils/system_information/helm.cr

> *This PR fixes #1390*
The setup command should show the local helm version accurately. It is currently using a helm that fallsback to display the global helm version - this causes the bug reported in 1390.
If global helm is not available on the machine, download and set path for global helm.
```
wget https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz
tar zxvf helm-v3.9.0-linux-amd64.tar.gz
export PATH=$PATH:/home/pair/workspace/akash/projects/linux-amd64
```
```
$ ./cnf-testsuite setup
Successfully created directories for cnf-testsuite
Global helm found. Version: v3.9.0
Local helm found. Version: v3.9.0
Global kubectl found. Version: 1.21
Global kubectl client version could not be checked for compatibility with server. (Server not configured?)
No Local kubectl version found
Global git …
```

[bug/1390] Display accurate local helm version in the setup command output

---

src/tasks/utils/chaos_templates.cr
src/tasks/workload/reliability.cr
src/templates/chaos_templates/pod_network_latency.yml.ecr

> *This PR resolves #1474*
Add support for running the `pod_network_latency` test against CNFs that use non-default namespaces.
Sample CNF to test: `sample-cnfs/sample-coredns-cnf`
**Issue**

[feature/1474] Add support for running the `pod_network_latency` test against CNFs that use non-default namespaces

---

src/tasks/utils/chaos_templates.cr
src/tasks/workload/reliability.cr
src/templates/chaos_templates/pod_network_corruption.yml.ecr

> *This PR resolves #1476*
Add support for running the `pod_network_corruption` test against CNFs that use non-default namespaces.
Sample CNF to test: `sample-cnfs/sample-coredns-cnf`
**Issue**

[feature/1476] Add support for running the `pod_network_corruption` test against CNFs that use non-default namespaces

---

src/tasks/utils/chaos_templates.cr
src/tasks/workload/reliability.cr
src/templates/chaos_templates/pod_network_duplication.yml.ecr

> *This PR resolves #1477*
Add support for running the `pod_network_duplication` test against CNFs that use non-default namespaces.
Sample CNF to test: `sample-cnfs/sample-coredns-cnf`
**Issue**

[#1477] Update pod_network_duplication test to support CNFs in non-default namespaces

---

src/tasks/utils/chaos_templates.cr
src/tasks/workload/reliability.cr
src/templates/chaos_templates/pod_io_stress.yml.ecr

Refs: #1492
Adds support `pod_io_stress` to test CNFs that run in non-default namespaces.
**Issue**

[1492] Adds support for `pod_io_stress` to test CNFs that run in non-default namespaces

---

src/tasks/utils/cnf_manager.cr
src/tasks/utils/kyverno.cr
src/tasks/workload/security.cr

> Issue: #1514
`sysctls` test will only report failures of resources that are part of the CNF
* Install `sample-cnfs/sample_coredns` CNF
* Run this command to create one more resource: `kubectl apply -f sample-cnfs/sample_sysctls/manifests/pod.yml`
**Issue**

[#1514] sysctls should only test CNF resources

---

src/tasks/workload/configuration.cr

Signed-off-by: denverwilliams <denver@debian.nz>
Testing:
Install a container into the default namespace(outside of the CNF being tested):
helm install --set image.tag=latest corednstag coredns/coredns
Results on default_namespace_fix#1513 branch: (Passing - Only the CNF being tested was caught in the failure logs)
`./cnf-testsuite -l info cnf_setup cnf-config=./sample-cnfs/sample_coredns`
`./cnf-testsuite -l info latest_tag`
```
./cnf-testsuite -l info default_namespace
I, [2022-06-21 23:10:01 +00:00 #885830]  INFO -- cnf-testsuite-verbose: default_namespace
I, [2022-06-21 23:10:01 +00:00 #885830]  INFO -- cnf-testsuite: kyverno_policy_path command: ls /home/pair/src/denver/cnf-testsuite/tools/kyverno-policies/best-practices/disallow_default_namespace/disallow_default_namespace.yaml
I, …
```

Update default_namespace test to only check the CNF's Resources #1513

---

src/tasks/workload/security.cr

Signed-off-by: denverwilliams <denver@debian.nz>
Testing:
Install a container using an external IP(outside of the CNF being tested):
`helm install --set service.externalIPs={192.168.1.1} corednstag coredns/coredns`
Results on external_ips#1516 branch: (Passing - No containers were caught in the failure logs)
`./cnf-testsuite -l info cnf_setup cnf-config=./sample-cnfs/sample_coredns`
`./cnf-testsuite -l info external_ips`
```
☺ ➔  ./cnf-testsuite -l info external_ips                                                                                                      
I, [2022-06-22 23:00:58 +00:00 #1065961]  INFO -- cnf-testsuite-verbose: external_ips
I, [2022-06-22 23:00:58 +00:00 #1065961]  INFO -- cnf-testsuite: kyverno_policy_path command: ls …
```

Update external_ips test to only check the CNF's Resources #1516

---

src/tasks/workload/security.cr

Moves Kyverno policy audit outside of `task_runner` for the `sysctls` test.
Refs: #1514
**Issue**

[#1514] Move policy audit outside of task_runner

---

src/tasks/workload/configuration.cr

Testing:
Install a container on the cluster without required_labels(outside of the CNF being tested):
`kubectl create -f sample-cnfs/k8s-non-helm/manifests/`
Results on require_labels#1524 branch: (Passing)
`./cnf-testsuite -l info cnf_setup cnf-config=./sample-cnfs/sample_coredns`
`./cnf-testsuite -l info require_labels`
```
☺ ➔  ./cnf-testsuite -l info require_labels
I, [2022-06-22 23:35:45 +00:00 #1072970]  INFO -- cnf-testsuite-verbose: require-labels
I, [2022-06-22 23:35:45 +00:00 #1072970]  INFO -- cnf-testsuite: kyverno_policy_path command: ls /home/pair/src/denver/cnf-testsuite/tools/kyverno-policies/best-practices/require_labels/require_labels.yaml
I, [2022-06-22 23:35:45 +00:00 #1072970]  INFO -- cnf-testsuite: kyverno_policy_path output: …
```

Update require_labels test to only check the CNF's Resources #1524

---

src/tasks/cleanup.cr

Refs: #1579, #1586
* Added `uninstall_falco` as dependency to `tools_cleanup`. Falco is now uninstalled when `cleanup_all` is run.
* Also updated the order of dependencies for `tools_cleanup` (for #1586), which was also affecting uninstallation for other third-party tools.
**Issue**

[bug/1579, bug/1586] Falco should be uninstalled when cleanup_all is run

---

USAGE.md
spec/workload/resilience/node_drain_spec.cr
src/tasks/workload/state.cr

Refs: #1574
* `node_drain` test skip message informs user about the requirement of a multi-node cluster.
* Updated USAGE.md with note about multi-node requirement for `node_drain` test.
* Updated assertion in spec test to use the new skip message for the test.
**Issue**

Add note about schedulable nodes to node_drain skip message

---

src/tasks/opa_setup.cr

* Add helm option to disable namespace update job for OPA Gatekeeper.
* This speeds up the Gatekeeper install since the namespace update job (which has an error), would not be installed.
* With this fix the gatekeeper install time is reduced from 5min to around 25 secs.
Notes and screenshots about this issue are on [this hackmd doc](https://hackmd.io/M7qWnl5sRKCGBkCCXK190w).
Refs: #1582
**Issue**

[#1582] Add helm option to disable namespace update job for OPA Gatekeeper

---

src/tasks/workload/configuration.cr

Refs: #1583
* It looks like the white lines in the output of the `ip_addresses` test were intended to be shown to the user to fix the test.
* This PR improves the formatting of the output instead of outputting the raw grep output.
> *The changes can be validated with the `lighty` branch, which has the testsuite config for the lighty-rnc CNF. The branch has the changes from this PR.*
```
#
./cnf-testsuite cnf_setup cnf-config=sample-cnfs/sample-coredns-cnf
./cnf-testsuite ip_addresses
./cnf-testsuite cnf_cleanup cnf-config=sample-cnfs/sample-coredns-cnf
#
./cnf-testsuite cnf_setup cnf-config=sample-lighty-rnc/cnf-testsuite.yml
./cnf-testsuite ip_addresses
./cnf-testsuite cnf_cleanup cnf-config=sample-lighty-rnc/cnf-testsuite.yml
```
Screenshot below shows the output for both when the test …

[bug/1583] Format IP addresses in the output appropriately in `ip_addresses` test

---

src/tasks/opa_setup.cr

Refs: #1593, #1592
* This PR moves gatekeeper to cnf-testsuite namespace.
* Adds helm local install task as a dependency (#1592)
* Also added task to create namespace as a dependency.
[hackmd doc with notes about this issue](https://hackmd.io/JJYb-alcQ2CwG8656_iY1Q)
```
./cnf-testsuite setup
./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/k8s-sidecar-container-pattern/cnf-testsuite.yml
./cnf-testsuite versioned_tag
```
```
./cnf-testsuite setup
./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns/cnf-testsuite.yml
./cnf-testsuite versioned_tag
```
**Issue**

[bug/1593, bug/1592] Move Gatekeeper to cnf-testsuite namespace

---

src/tasks/utils/kubescape.cr

Refs: #1594, #1603
* Construct alert messages for Kubescape-based tests if `alertMessage` in the Kubescape test report is empty. This is required to display the failed resources to the user.
* Refactored Kubescape test report parser into new `Kubescape::TestReportParser`.
```
./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample-privilege-escalation/cnf-testsuite.yml
./cnf-testsuite privilege_escalation
./cnf-testsuite cnf_cleanup cnf-config=./sample-cnfs/sample-privilege-escalation/cnf-testsuite.yml
./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample-nonroot-containers/cnf-testsuite.yml
./cnf-testsuite privilege_escalation
./cnf-testsuite cnf_cleanup cnf-config=./sample-cnfs/sample-nonroot-containers/cnf-testsuite.yml
```
```
./cnf-testsuite cnf_setup …
```

[1595, 1603] Update Kubescape test parser to return message about failed resources

---

tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh

Upgrades GitHub Runners base image to latest  version 2.295.0.
Refs: #1604
**Issue**

[1604] GitHub Runners image upgrade (16 Aug 2022)

---

spec/utils/system_information/docker_spec.cr
src/tasks/utils/system_information/docker.cr
src/tasks/workload/compatibility.cr

Refs: #1600
* Adds `DockerVersion` class with an `installed?` method.
* Renames `docker_installation` helper to `docker_version_info`.
* `docker_version_info` returns a new `DockerVersion` object.
* Updates `cni_compatible` test to use the new `docker_version_info` helper
* Updates specs for the docker helpers to check for `docker_version_info` helper.
* Renames `docker_version` to `parse_docker_version`
```
./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample-coredns-cnf
./cnf-testsuite cni_compatible
```
**Issue**

[bug/1600] `cni_compatible` no longer outputs docker version info to stdout

---

src/tasks/workload/observability.cr

Refs: #1610
When `routed_logs` is run after any test that uninstalls ClusterTools, then the test fails with an error.
This PR adds a task dependency to install ClusterTools before running the `routed_logs` test.
```
helm repo add fluent https://fluent.github.io/helm-charts
helm install --values ./embedded_files/fluentbit-config.yml -n cnf-testsuite fluent-bit fluent/fluent-bit
./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample_coredns
./cnf-testsuite host_network
./cnf-testsuite routed_logs
```
**Issue**

[1610] Add `install_cluster_tools` as dependency for `routed_logs`

---

.github/workflows/actions.yml
tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh

Refs: #1630, #1631
* [1630] Add GitHub gpg keys to the GitHub Actions Runner image.
* [1631] Updates GitHub Actions Runner to use base image to `myoung34/github-runner:2.296.1-ubuntu-bionic`
* Updates the create runners script to use the new image
Workers have already been recreated to with an updated fork of the image.
**Issue**

[1631, 1630] Fix GitHub Actions Runner issues

---

.github/workflows/actions.yml

Refs: #1633
* Uses kubectl-run with an Ubuntu image to check cluster rate limit.
* Removes kind v0.14 install patch from Chaos specs GitHub Actions config.
**Issue**

[1633] Updates to Github Actions config to allow Chaos specs to run on kind v0.15

---

README.md

- Meetings every Tuesday at 14:15 - 15:00 UTC (during Daylight Savings Time)
Signed-off-by: Taylor Carpenter <taylor@vulk.coop>

Office hours moved to Tuesday

---

src/tasks/opa_setup.cr

Refs: #1670
Installing OPA on Kubernetes server v1.25.0 causes the testsuite to crash. This is required for the versioned_tag test to work.
PodSecurityPolicy has been removed in Kubernetes v1.25.0. It has to be disabled on Gatekeeper install by passing a value to the helm chart. The change in this PR checks the k8s version of the current cluster and sets the value for the gatekeeper helm chart if required.
Checks `versioned_tag` test on different Kubernetes server versions.
**Issue**

[#1670] Disable PSP when installing gatekeeper on k8s server >= v1.25.0

---

src/tasks/utils/kernel_instrospection.cr

Refs: #1668
When looking for prometheus, the containerID is not available for pods when the pods are being initialized. This cause a crash due to missing containerID key.
The change now looks for the containerID only if the pod is ready.
The crash reported in Issue-1668 can only be reproduced on Kubernetes 1.25.0. Version information below:
**Issue**

[#1668] ContainerID is not available when pod is being initialized on Kubernetes `1.25.0`

---

src/tasks/workload/compatibility.cr
src/tasks/workload/configuration.cr
src/tasks/workload/security.cr

Signed-off-by: W. Watson <w.watson@vulk.coop>
Fix bug causing the F5 cert to crash when running security tests.
Refs: #NNN
**Issue**

#1678 kyverno not does not stop the remaining tests from running

---

CONTRIBUTING.md

The CNF Test Suite team meets once a week on Tuesdays at 15:15-16:00 UTC (7:15-8:00 AM Pacific Standard Time)
Signed-off-by: Lucina Stricko <lucina@vulk.coop>
Refs: #NNN
**Issue**

change office hours to Tuesdays at 15:15 UTC

---

README.md

Update office hours time in README to match contribute doc
remove TUG meeting completely
only have link to CNF WG meeting
Signed-off-by: Taylor Carpenter <taylor@vulk.coop>

Update README.md for meeting info for office hours, TUG and CNF WG

---

tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh

Had to update github runners to latest image as they were no longer picking up jobs for PR, branch pushes and updates.
Refs: #NNN

GitHub Runners Image Update to 2.299.1

---

spec/utils/cnf_manager_spec.cr
spec/workload/microservice_spec.cr
src/tasks/workload/microservice.cr

If MariaDB is not available on cluster, then `shared_database` test should be `N/A` result. This will ensure that the test is not counted for the max number of tests in the category.
Refs: #1697
**Issue**

[bug/1697] If MariaDB is not available on cluster, then `shared_database` test result should be N/A

---

src/tasks/cert/cert.cr
src/tasks/setup.cr
src/tasks/utils/points.cr

* Print testsuite version when running setup and cert commands.
* Add testsuite_version to results file.
Refs: #1472
**Issue**

[feature/1472] Print testsuite version when cert and setup commands are run

---

src/tasks/workload/compatibility.cr

Refs: #1634
When increase capacity fails or decrease capacity fails, then the failure messages should be separately reported.
This PR includes changes to report these failures separately.
To reproduce,
1. Run the testsuite setup command
2. Install the coredns sample CNF
3. `unset KUBECONFIG` env var so that kubectl will not find the cluster
4. Run the test: `./cnf-testsuite increase_decrease_capacity` (both increase and decrease will fail)
**Issue**

[bug/1634] Add separate failure messages for `increase_decrease_capacity` test

---

.github/workflows/actions.yml

Update to the latest Ubuntu 22.04 image for Chaos Tests to avoid the expiring Ubuntu 18.04 brown out periods where the jobs will be cancelled and not run.
Refs: #NNN
**Issue**

[BUG] Update github actions chaos tests to use Ubuntu 22.04 image

---

sample-cnfs/multi_helm_directories/multiple/directory/chart/values.yaml
sample-cnfs/sample-appliciation-credentials/chart/values.yaml
sample-cnfs/sample-bad_helm_coredns-cnf/chart/values.yaml
sample-cnfs/sample-fragile-state/chart/values.yaml
sample-cnfs/sample-insecure-capabilities/chart/values.yaml
sample-cnfs/sample-large-cnf/chart/values.yaml
sample-cnfs/sample-local-storage/chart/values.yaml
sample-cnfs/sample-privilege-escalation/chart/values.yaml
sample-cnfs/sample-prom-pod-discovery/chart/values.yaml
sample-cnfs/sample_coredns/chart/values.yaml
sample-cnfs/sample_coredns_bad_liveness/chart/values.yaml
sample-cnfs/sample_coredns_chart_directory/chart/values.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/values.yaml
sample-cnfs/sample_coredns_protected/chart/values.yaml
sample-cnfs/sample_coredns_values/chart/values.yaml
sample-cnfs/sample_immutable_configmap_all/chart/values.yaml
sample-cnfs/sample_immutable_configmap_all_plus_env/chart/values.yaml
sample-cnfs/sample_immutable_configmap_all_plus_env_but_fail/chart/values.yaml
sample-cnfs/sample_immutable_configmap_some/chart/values.yaml
sample-cnfs/sample_local_registry/chart/values.yaml
sample-cnfs/sample_local_registry_org_image/chart/values.yaml
sample-cnfs/sample_local_registry_rolling/chart/values.yaml
sample-cnfs/sample_network_loss/chart/values.yaml
sample-cnfs/sample_operator/chart/values.yaml
sample-cnfs/sample_privileged_cnf/chart/values.yaml
sample-cnfs/sample_rolling/chart/values.yaml
sample-cnfs/sample_rolling_invalid_version/chart/values.yaml
sample-cnfs/sample_whitelisted_privileged_cnf/chart/values.yaml

The registry URL for k8s images is changing. This pull request in the below issue addresses this URL where we use within our sample-cnfs available in our code base and spec tests.
Refs: #1742 
**Issue**

Maintenance/#1742 registry k8s URL update

---

.github/workflows/actions.yml
shard.lock
shard.override.yml
shard.yml
tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh
utils/airgap/shard.yml

Refs: #1751, #1760, #1754
1. Update some shards to point to their semver releases.
2. Update Crystal version to 1.6.2 in GitHub Runner image enable [1] to work.
3. Update GitHub Runner dockerfile to point to new base image version.
4. Update create_runners script to use new image tag.
**Issue**

[1751] Semver releases for shards + Crystal update for GitHub Runner image

---

spec/cluster_setup_spec.cr
spec/setup_spec.cr
src/tasks/cluster_setup.cr

redo of https://github.com/cncf/cnf-testsuite/pull/1746
which was accidentally merged from a bad force push.
blocked by https://github.com/cncf/cnf-testsuite/pull/1766
Refs: #1624 
depends on https://github.com/cnf-testsuite/cluster_tools/pull/12
**Issue**

raise exception when cluster tools namespace does not exist #1624

---

.github/workflows/actions.yml
CNF_TESTSUITE_YML_USAGE.md
src/tasks/constants.cr
src/tasks/utils/config.cr
src/tasks/utils/dockerd.cr
src/tasks/utils/embedded_file_manager.cr
src/tasks/utils/task.cr
src/tasks/workload/microservice.cr
src/templates/docker-config.yml.ecr
src/templates/dockerd-manifest.yml.ecr

Refs: #1597
The `reasonable_image_size` test would throw an `Int64` error. This was due to two issues:
Private registries hosted on the cluster usually have to be trusted to use registry API endpoints via HTTP. The docker daemon has to be configured to be allowed to access the private image registry on the cluster via HTTP endpoints.
The Docker daemon is setup by the testsuite on the `cnf-testsuite` namespace. For the `reasonable_image_size` test, when the testsuite is referring to an image registry on another namespace, the testsuite requires the service discovery url for the service. It cannot access the registry with just the service name.
So if the helm chart mentions `foobar:5000/coredns:1.6.7`, the docker daemon wouldn't know which namespace the service is on.
This PR adds support …

[bug/1597] Allow configuring insecure docker registries and image registry FQDNs

---

.github/workflows/actions.yml

This update only attempts to delete kind binary if kind exists.
Refs: #1809
**Issue**

[1809] Fix kind install step in GitHub Actions workflow

---

.github/workflows/actions.yml
spec/utils/cnf_manager_spec.cr
spec/utils/utils_spec.cr
src/tasks/platform/hardware_and_scheduling.cr
src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr
src/tasks/platform/security.cr
src/tasks/utils/points.cr
src/tasks/utils/utils.cr
src/tasks/workload/compatibility.cr
src/tasks/workload/configuration.cr
src/tasks/workload/microservice.cr
src/tasks/workload/observability.cr
src/tasks/workload/reliability.cr
src/tasks/workload/security.cr
src/tasks/workload/state.cr

Refs: #1807
When `TASK_TIMESTAMPS` env var is set when running any tests, the following fields are added to every test in the results file:
* `start_time` - Timestamp in UTC when the task was started
* `end_time` - Timestamp in UTC when the task was completed (ended)
* `task_runtime_milliseconds` - Time required for this task to run in milliseconds.
```
TASK_TIMESTAMPS=true ./cnf-testsuite cert
```
**Issue**

[1807] Add task runtime info to results file if `TASK_TIMESTAMPS` env var is set

---

shard.lock
shard.yml

* Added support for kubectl v1.28 in kubectl_client 1.0.2
* Updated the shard.yml in the project to point to kubectl_client 1.0.2
**Issue**

[1822] Update kubectl_client to 1.0.2 to support kubectl v1.28

---

shard.override.yml

This PR removes the shard.override.yml that was created to override kubectl_client to a branch with fixes.
**Issue**

[1798] Remove shard.override.yml for kubectl_client

---

sample-cnfs/sample-coredns-cnf2/README.md
sample-cnfs/sample-coredns-cnf2/cnf-testsuite.yml
shard.lock
shard.override.yml
shard.yml
src/tasks/litmus_setup.cr
src/tasks/workload/state.cr

* Uncordon node after running `node_drain` for an app.
* Update `kubectl_client` to `1.0.4`.
* Added sample coredns CNF with different release name and namespace to help with testing the changes.
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
containerdConfigPatches:
- |-
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
endpoint = ["http://139.178.70.81:80"]
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry:5000"]
endpoint = ["http://localhost:5000"]
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.default.svc.cluster.local:5000"]
endpoint = ["http://localhost:5000"]
```
```shell
export KIND_CLUSTER_NAME="1834-3node"
export KUBECONFIG="${PWD}/${KIND_CLUSTER_NAME}.kubeconfig" …
```

[bug/1834] Uncordon node after running `node_drain` test for a CNF

---

sample-cnfs/sample-coredns-cnf3/README.md
sample-cnfs/sample-coredns-cnf3/cnf-testsuite.yml
sample-cnfs/sample-coredns-cnf4/README.md
sample-cnfs/sample-coredns-cnf4/cnf-testsuite.yml
src/tasks/litmus_setup.cr
src/tasks/workload/state.cr

* `LitmusManager.wait_for_test`: Increase wait_count to 30min
* Add two more copies of coredns CNF to be able to reproduce `node_drain` failures for multiple CNFs.
* Update `node_drain` chaos experiment name to use `Random::Secure.hex/1` instead of `Random.rand/1`
* Output `node_drain` experiment name and test name to debug log.
* Output command to inspect chaos experiment if `node_drain` fails for CNF
* Output chaos experiment resource/result to debug log if test fails for CNF
Setup a 3-node cluster and install multiple CNFs like below. The CNFs can be copy of coredns CNF installed into different namespace and with different release names.
```
export KIND_CLUSTER_NAME="1834-3node"
export KUBECONFIG="${PWD}/${KIND_CLUSTER_NAME}.kubeconfig"
kind create cluster --name $KIND_CLUSTER_NAME \ …
```

[bug/1838] Increase wait_count in LitmusManager.wait_for_test to allow for slow verdicts

---

src/tasks/platform/hardware_and_scheduling.cr
src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr
src/tasks/platform/security.cr
src/tasks/utils/points.cr
src/tasks/workload/compatibility.cr
src/tasks/workload/configuration.cr
src/tasks/workload/microservice.cr
src/tasks/workload/observability.cr
src/tasks/workload/ran.cr
src/tasks/workload/reliability.cr
src/tasks/workload/security.cr
src/tasks/workload/state.cr

* Publish a log message when a task is started. This helps identify when test starts running for a particular CNF.
* The task timestamps are now published to the info log irrespective of `TASK_TIMESTAMPS=true` being set.
* For log messages directly within the test task, publish log messages with Log.for instead of the top-level log (Log).
**Issue**

[maintain/1841] Add log lines and organize log messages in tests

---

src/cnf-testsuite.cr
src/tasks/cleanup.cr
src/tasks/cnf_conformance_setup.cr
src/tasks/constants.cr
src/tasks/utils/embedded_file_manager.cr
src/tasks/utils/points.cr

Fix creation of results file and folder during class definition. Now, they are created only on-demand via updated getter. Fix creation of points.yml file during the definition of constants. Add meaningful error messages if these files could not be created due to insuficcient user permissions in current directory.
Tested: results folder and points.yml are not created on "help" and "version" commands. If user does not have permissions in workdir - other commands still fail due to not sufficient permissions (but i suppose, that covering them with meaningful error messages should be done in another change). Workload tests are running without issues with this change, so any functionality shouldn't be lost. 
Refs: #1802
- [*] Bug fix (non-breaking change which fixes an issue) …

results and points.yml: Fix unnecessary creation and add exceptions

---

src/cnf-testsuite.cr

The repo url used with `ReleaseManager::GitHubReleaseManager` needs to be updated for the `Publish Release` GitHub Actions step to work as expected. This is currently failing in the `main` branch builds.
Refs: #1900
**Issue**

[bug/1900] Update repo url used with GithubReleaseManager

---

embedded_files/points.yml
src/tasks/utils/points.cr

This change modifies the points.yml file to use correct YAML syntax for a list.
It also includes the simplification of tag handling.
Refs: #1865
Tested by running all tests (workload and platform) and all spec tests.
**Issue**

Refactoring of tag handling with correct YAML syntax

---

spec/workload/state_spec.cr
src/tasks/utils/mysql.cr
src/tasks/workload/state.cr

elastic_volumes test should fail if any of the volumes is not elastic database_persistence test should test specifically resources with mysql images and pass if condition is true for all of them. This commit should fix that.
Fixes: #1884
Redesigned these tests according to the discussion in the #1884.
database_persistence is tested on bitnami/mysql helm chart (i don't have possibility to set up elastic volumes, so i've checked that it fails with elastic_volume condition and passes without it)
Refs: #1884
**Issue**

Fix elastic_volumes and database_persistence logic

---

embedded_files/points.yml
spec/utils/cnf_manager_spec.cr
spec/utils/utils_spec.cr
src/tasks/utils/points.cr
src/tasks/utils/task.cr
src/tasks/utils/utils.cr
src/tasks/workload/observability.cr
src/tasks/workload/state.cr

Modularized test im plementation:
- centralized test result output
- remove repeated code/strings/emojis from test implementation
- category emojis are taken based on test category in points.yml
- the adaptations require adaptation (simplification and removal of code) of every test case.
- This is a WIP pull request for purpose of review of the chanegs. Only test cases in workload/observability.cr are adapted. What is missing is to adapt all remaining tests (after this one goes through the review process to avoid changing many files during the review). Do not merge for now.
- note that it was also required to fix some of #1864 as the code stopped working after adding arguments to some methods.
- also note that ResultStatus enum was moved 2 levels up in hierarchy to be better usable.
Refs: …

Modularize implementation of tests #1861

---

embedded_files/points.yml
spec/utils/cnf_manager_spec.cr
spec/workload/operator_spec.cr
src/tasks/utils/points.cr
src/tasks/workload/5g_validator.cr
src/tasks/workload/compatibility.cr
src/tasks/workload/configuration.cr
src/tasks/workload/microservice.cr
src/tasks/workload/ran.cr
src/tasks/workload/reliability.cr
src/tasks/workload/security.cr
src/tasks/workload/state.cr

Workload tests adapted to cenralized result logging
Refs: #1861 
**Issue**

Workload tests adapted to centralized result logging

---

.github/workflows/actions.yml

It updates Kind from v0.17.0 to v0.22.0 and the hardcoded v1.23.13 images to v1.23.17.
Refs: #1886

Update Kind and its image versions in gates

---

curl_install.sh

cnf-testsuite isn't executable in the archive which breaks [Installation and Usage](https://github.com/cnti-testcatalog/testsuite?tab=readme-ov-file#installation-and-usage)
curl_install.sh must also chmod the binary.

chmod a+x cnf-testsuite in curl_install.sh

---

embedded_files/points.yml
src/tasks/cert/cert_resilience.cr

pod_dns_error requires docker k8s runtime.
This is not aligned with certification environment requirements, thus removing the test from certification. Refs:#1977
Refs: #NNN
**Issue**

Remove pod_dns_error from certification

---

.github/workflows/actions.yml
spec/workload/resilience/pod_memory_hog_spec.cr
src/tasks/litmus_setup.cr
src/tasks/workload/reliability.cr
src/templates/chaos_templates/disk_fill.yml.ecr
src/templates/chaos_templates/pod_memory_hog.yml.ecr

Litmus error
Updating to new version of Litmus and adjusting code for new version
Refs: #1973 
**Issue**

(fixing main) Update pod_memory_hog_spec.cr

---

example-cnfs/coredns/cnf-testsuite.yml
example-cnfs/envoy/cnf-testsuite.yml
example-cnfs/ip-forwarder/cnf-testsuite.yml
example-cnfs/nsm/cnf-testsuite.yml
example-cnfs/pantheon-nsm-nat/cnf-testsuite.yml
example-cnfs/vpp-3c2n-csp-use-case/cnf-testsuite.yml

example-cnfs/coredns fails passing default_namespace by default and fails in gates too [1].
It forces now deployment coredns-coredns to be in cnfspace.
Please note it sets helm_install_namespace in all example cnf-testsuite.yml when missing.
[1] https://github.com/cnti-testcatalog/testsuite/actions/runs/8564278589/job/23493678803#step:11:1170
Refs: #1952

Set helm_install_namespace in all example cnf-testsuite.yml

---

src/tasks/utils/init_systems.cr
src/tasks/workload/microservice.cr

This updates the behaviour so the test will not pass when there is an environment or external error causing the test to not be able to do a complete validation as intended. (eg. the containers could not be inspected because of an external unrelated issue).
The error is reported and the test will not pass.
Refs: #1959
**Issue**

Prevent microservice tests from passing on errors

---

src/tasks/workload/configuration.cr

Minor change to fix immutable configmaps typo
Refs: #na
**Issue**

fix immutable configmaps typo

---

embedded_files/points.yml
src/tasks/cert/cert_compatibility.cr

Disabling cni_compatible from the list of tests run when using the `cert` command.  
This test is crashing and uses an old k8s version.
This PR does not remove the test from the testsuite.  The test issues will need to be addressed in a different PR.  See the issue #1965 for more details.
Refs: #1965
**Issue**

remove cni_compatible from cert tests

---

spec/5g/core_spec.cr
spec/5g/ran_spec.cr
spec/platform/hardware_and_scheduler_spec.cr
spec/platform/observability_spec.cr
spec/platform/platform_spec.cr
spec/platform/resilience_spec.cr
spec/platform/security_spec.cr
spec/utils/utils_spec.cr
spec/workload/compatibility_spec.cr
spec/workload/configuration_spec.cr
spec/workload/installability_spec.cr
spec/workload/microservice_spec.cr
spec/workload/observability_spec.cr
spec/workload/operator_spec.cr
spec/workload/resilience/disk_fill_spec.cr
spec/workload/resilience/node_drain_spec.cr
spec/workload/resilience/pod_delete_spec.cr
spec/workload/resilience/pod_dns_error_spec.cr
spec/workload/resilience/pod_io_stress_spec.cr
spec/workload/resilience/pod_memory_hog_spec.cr
spec/workload/resilience/pod_network_corruption_spec.cr
spec/workload/resilience/pod_network_duplication_spec.cr
spec/workload/resilience/pod_network_latency_spec.cr
spec/workload/security_spec.cr
spec/workload/state_spec.cr
src/tasks/utils/task.cr
src/tasks/utils/utils.cr

Add information of which test is starting to the console output 
Add test name to test result console output
Refs: #1958
No documentation update is needed.
Only outputs have been modified, functionality shouldn't be affected in any way.

Enhancement: Add test name before and after the test in console output

---

src/tasks/cert/cert.cr
src/tasks/cert/cert_compatibility.cr
src/tasks/cert/cert_configuration.cr
src/tasks/cert/cert_microservice.cr
src/tasks/cert/cert_observability.cr
src/tasks/cert/cert_resilience.cr
src/tasks/cert/cert_security.cr
src/tasks/cert/cert_state.cr
src/tasks/utils/points.cr

Add possibility to run only essential tests with "cert essential" 
Get certification tests by tags from points.yml
Run tests inside certification categories with t.invoke instead of task dependencies
Refs:#1997
Manual runs of certification process with and without the new option.
Specs shouldn't be afflicted.
New feature (non-breaking change which adds functionality)
There's no specific documentation for running cert, maybe some changes could be introduced to certification repo.

cert: rework certification tasks, add "essential" argument

---

.github/workflows/actions.yml

cnf testsuite must be verified vs up-to-date K8S versions.
By removing the harcoded K8S versions, the gates will leverage the latest stable K8S version as proposed by Kind.
Refs: #1948
A verification job must be executed to see the testcases which would have to be updated.
This PR may ask for others PR if obsolete test cases ask for updates.

Remove all hardcoded EOL K8s version

---

spec/workload/microservice_spec.cr

In one of shared DB spec tests was missing removal of pvc which was created during cnf setup.
This change adds this removal.
Refs: #2017 
**Issue**

Add removal of pvc in the end of spec test

---

USAGE.md
spec/utils/utils_spec.cr
src/tasks/utils/utils.cr

Add processing of environment variables LOGPATH and LOG_PATH If either one exists - logger will log into the file on that path instead of STDOUT.
Refs: #2000
Manual testing of the functionality.
Running new spec.
New non-breaking feature
No documentation update is needed.

logging: Add possibility to log into file

---

src/tasks/workload/state.cr

In 69dedb30dd686ab2d1edffb4178ddb3f2c94e7e4, Litmus version was updated And all links for experiments were changed accordingly except for the node_drain. This commit fixes that.
ref: #2022

node-drain: Fix link to experiment

---

src/tasks/workload/state.cr

node-drain: Fix link to experiment #2024
CI permissions for running specs against https://github.com/cnti-testcatalog/testsuite/pull/2024
Refs: https://github.com/cnti-testcatalog/testsuite/pull/2024

Konst/node drain fix - node-drain: Fix link to experiment #2024

---

src/tasks/workload/compatibility.cr

Update of cilium version.
Refs: #2015 
**Issue**

Update: Cilium version update

---

README.md

- removed best practices meeting - canceled until further notice
- removed certification meeting
- kept test catalog meeting in test catalog repo.
- refs https://github.com/lfn-cnti/bestpractices/issues/348

remove non-testsuite meetings from README.md

---

src/tasks/constants.cr
src/tasks/utils/points.cr
src/tasks/utils/task.cr
src/tasks/utils/utils.cr

- add upsert_decorated_task method into single_task_runner
- if task ends with unexpected error, is also add into results file with status: error
Refs: #1334
**Issue**

fix: add error_task into cnf-testsuite-results file

---

sample-cnfs/k8s-multiple-processes/cnf-testsuite.yml
sample-cnfs/sample-multiple-processes/cnf-testsuite.yml
sample-cnfs/sample_coredns/cnf-testsuite.yml
sample-cnfs/sample_coredns_default_namespace/chart
sample-cnfs/sample_coredns_default_namespace/cnf-testsuite.yml
spec/workload/configuration_spec.cr
src/tasks/workload/microservice.cr
src/tasks/workload/observability.cr

The namespace is needed to be passed as a parameter when calling pods_by_resource of kubectl client.
Impacted tests: single_process_type, prometheus_traffic Also adding non-default namespace to respective spec tests.
Refs: #2030
**Issue**

Add namespace when calling pods_by_resource

---

shard.lock
shard.yml
src/tasks/constants.cr
src/tasks/utils/init_systems.cr
src/tasks/workload/microservice.cr

This change defines a list of specialized init systems as a constant and excludes it from the verification of a single process check.
**This PR depends on https://github.com/cnf-testsuite/k8s_kernel_introspection/pull/3 which has to be merge first.**
Refs: #2038
**Issue**

Add exclusion of init system from single process check

---

.github/workflows/actions.yml

Don't fail on unsuccessful cluster deletion.
This unnecessary make the jobs failing.
Refs: #2064
Refs: #NNN
**Issue**

Don't fail on delete cluster in github actions

---

src/tasks/setup.cr
src/tasks/utils/utils.cr

- add one more elsif condition in case variable KUBECONFIG is not set (empty)
- change error messages
Refs: #985 
**Issue**

fix: add condition in method ensure_kubeconfig!

---

shard.lock
shard.yml

Bump kubectl_client to fix labelling issue

---

src/tasks/utils/utils.cr

Add condition in ensure_kubeconfig! method to check the cluster's health. 
Refs: #1968
**Issue**

improvement: check if cluster is up and running

---

.github/workflows/actions.yml

Make "docker login" in spec execution optional. Note that it has anyway limited (if any) effect as docker registry mirror cache is used and docker login does not really have expected affect. The registry mirror cache itself needs to be configured with respective credentials. 
Refs: #2066
**Issue**

Allow GH actions on PRs from forked repos

---

spec/cluster_setup_spec.cr
src/tasks/cluster_setup.cr

As explained in the referenced issue, there was an unnecessary stack trace printed out in `install_cluster_tools` and `uninstall_cluster_tools` if `./cnf-testsuite setup` has not been run. This was remediated by replacing the `raise` command with `puts`. Additionally I made the informative message more explicit for new users.
Refs: #1926 
**Issue**

Change: Cluster setup exception message shortened

---

.github/workflows/actions.yml
.github/workflows/test-doc-lint.yml
.gitignore
doc-lint/Local-lint-usage
doc-lint/mdl-TTDS-rules.rb
doc-lint/mdl-style.rb
docs/TEST_DOCUMENTATION.md

Add mdl as a linter for new cnf-testsuite documentation 
Add custom rules for keeping format of the documentation 
Add lint to git workflows to run mdl.
Remove docs directory from .gitignore
Fix small issues in documentation for linter to pass.
Refs: #1945

docs: Add linter for the documentation

---

src/tasks/workload/configuration.cr

Add information about file location, line numbers and lines themselves if the hardcoded_ip_addresses_in_k8s_runtime_configuration fails
Refs: #2093
Covered by existing integration testing
Bug fix (non-breaking change which fixes an issue)

hardcoded-ip-test: Redesign test, add more info on fail

---

src/tasks/utils/cnf_manager.cr

Removed file globbing as it caused errors and added a new function that will detect a specific tgz file to be untared. Removed the line: `FileUtils.rm_rf(tgz_name)` as it did not work previously and now that globbing has been fixed it would cause undesired behavior (honestly I was not able to figure out why it is there at all).
Refs: #1947 
**Issue**

Fix: export_published_chart correctly detects and exports tar file

---

docs/TEST_DOCUMENTATION.md

Should move all k8s API related stuff to the correct configuration sections across doc files.
Interestingly there were as of yet unimplemented TO DO'S in USAGE.md and TEST_CATEGORIES.md which were also moved for future coherence (these relate to the k8s APIs category).
Refs: #2077 
**Issue**

Docs: Relocate alpha_k8s_apis to configuration sections across docs

---

src/tasks/utils/cnf_manager.cr
src/tasks/utils/k8s_tshark.cr
src/tasks/utils/oran_monitor.cr
src/tasks/workload/5g_validator.cr

**Commit message:**
- Prior functionality was bound to fixed time of execution (120s), which introduced problems in testing (tshark session ending before the test began).
- New functionality mainly implements infinite tshark execution along with the possibility of terminating it when deemed appropriate. This is complemented with robust error handling and termination of the tshark process on unexpected crashes during initialization. NOTE: The main tests currently do not handle states where a crash could occur elsewhere and thus a hanging tshark session can still happen (although unlikely).
- The module is properly commented which should allow the user to get a quick understanding of its functionality.
- The user functionality remains the same with easier-to-comprehend function names.
- …

Feat: Rework k8s_tshark functionality and apply the changes in tests

---

spec/utils/cnf_install/install_common_spec.cr
spec/utils/cnf_manager_spec.cr
src/tasks/cleanup.cr
src/tasks/cnf_setup.cr
src/tasks/utils/cnf_installation/install_common.cr
src/tasks/utils/cnf_installation/manifest.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/config.cr
src/tasks/utils/generate_config.cr
src/tasks/utils/task.cr
src/tasks/workload/microservice.cr
src/tasks/workload/state.cr

Problem explained in referenced issue.
Move "installation methods" enum from helm repo
Move Manifest-related functionality ("Manifest" module) from helm repo
Refs: #2105

manifest_install: Move manifest install to repo

---

.github/workflows/actions.yml

In our CICD, when new commit is pushed (or amended) while workflow for old one is still running - there is no auto-cancelation. Old workflows have to be canceled manually by maintainers to avoid unneccessary waiting.
This change fixes that issue by grouping workflows by PR number or branch ref (in case for push event), and if new workflow is ran in the same group - old one would be automatically cancelled.
Change is relatively simple, so issue wasn't created for it.

workflow: Cancel workflows on push

---

shard.lock
shard.yml
src/tasks/workload/microservice.cr

The single_process_type / process_check spec tests took on average 1:30:00 to execute (in github actions), this was reduced to around 10-15 minutes. It was caused by incorrect use of libraries which checked unnecessary processes multiple times.
**These two changes need to be merged first:**
cluster_tools change: [#27](https://github.com/cnf-testsuite/cluster_tools/pull/27)
k8s_kernel_introspection change: [#4](https://github.com/cnf-testsuite/k8s_kernel_introspection/pull/4)
Because this pull request makes changes in two libraries, it is rather difficult to verify it through actions. Currently there are changes to the `shards.yaml` and `shards.lock` files which will be removed once the reviewers approve the change and the individual library pull requests are merged.
**For reviewers:** …

Fix: Optimize single_process_type execution

---

embedded_files/points.yml
spec/utils/cnf_manager_spec.cr

Certification was updated to count only for essential tests. 
This commit reflects the change in certification.
Refs: #2117

cert: remove cert tag from non-essential tests

---

CONTRIBUTING.md
CONTRIBUTION_LADDER.md
FAQ.md
README.md

Cnti channels were reduced to a single one.
Adapting documentation accordingly.
Refs: lfn-cnti/cnti#32

Update links to the cnti slack channel

---

spec/workload/microservice_spec.cr

After #2114 was merged, an issue was revealed
with image size - protected repo spec test.
It was discovered only after merging.
Until this is fixed, disabling this variant
of the image size spec test.
Refs: #2114 #2136

quick fix: remove protected image repo spec test

---

shard.lock
shard.yml

Optimizing cluster-tools for download amount/speed. 
Refs: cnf-testsuite/cluster_tools#24

Bump cluster-tools to v1.0.7

---

sample-cnfs/sample-local-storage/chart/templates/persistent-volume-claim.yaml
sample-cnfs/sample-oran-noric/manifests/ric.yml
sample-cnfs/sample-oran-noric/manifests/srsran.yml
sample-cnfs/sample-oran-ric/manifests/ric.yml
sample-cnfs/sample-oran-ric/manifests/srsran.yml
sample-cnfs/sample-tracing/cnf-testsuite.yml
sample-cnfs/sample_open5gs/cnf-testsuite.yml
sample-cnfs/sample_srsran_ueauth_open5gs/cnf-testsuite.yml
spec/5g/ran_spec.cr
spec/utils/cnf_manager_spec.cr
src/tasks/utils/cnf_installation/install_common.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/jaeger.cr
src/tasks/utils/srsran.cr
src/tasks/utils/ueransim.cr
src/tasks/workload/5g_validator.cr

- affect CNFs that installing method is HelmDirectory
- CNFs are correctly install into cnf-default namespace (if helm_install_namespace variable is not set)
- change Helm::InstallMethod::HelmDirectory to CNFInstall::InstallMethod::HelmDirectory
Refs: #2039
**Issue**

fix: Change Helm library to CNFInstall module

---

CNF_TESTSUITE_YML_USAGE.md
src/tasks/update_config.cr
src/tasks/utils/cnf_installation/config.cr
src/tasks/utils/cnf_installation/config_updater/config_updater.cr
src/tasks/utils/cnf_installation/config_updater/transformation_base.cr
src/tasks/utils/cnf_installation/config_updater/v1_to_v2_transformation.cr
src/tasks/utils/cnf_installation/config_versions/config_v1.cr
src/tasks/utils/cnf_installation/config_versions/config_versions.cr

To speed up the development of the #2120 epic we are currently experimenting with a different approach to pull requests. This pull request has been created anew from a different branch, if you want to check the already existing discussion around it, view the old [#2133](https://github.com/cnti-testcatalog/testsuite/pull/2133).
The transformer transforms the old config according to the structure proposed in #2129.
**Notes**
1. To allow for some input validation, the v1 config was reimplemented as class in `config_v1.cr`.
2. Certain arguments are found in cnf-testsuite.yml files spread across the samples and examples that are unused anywhere in the code, these are still parsed but ignored to avoid too much manual intervention in later stages.
3. A new task has been added to allow for …

config: CNF installation (2.1) Transformer for old version of config

---

src/tasks/cnf_setup.cr

Create new config generation task, that would generate v2 config.
This task should be more interactable and friendly to new testsuite users.
Refs: https://github.com/cnti-testcatalog/testsuite/issues/2138
Re-created from different branch, old PR: #2142

config-generator: CNF Installation (2.2) Add generator for v2 config

---

USAGE.md
shard.lock
shard.yml

Ameba is a linting tool, which isn't being used in our CI pipelines, and causes complications with crystal version update. 
Ameba dependency should be removed from cnf-testcatalog shards and usage guidelines should point to more independent usage via installing the linter from source.
Refs: #2157

ameba: Remove ameba from shard dependencies

---

spec/5g/ran_spec.cr
spec/setup_spec.cr
spec/utils/utils_spec.cr
src/tasks/cnf_setup.cr

Remove the ability of users to run `cnf-testsuite cnf_setup {../testsuite.yml}` multiple times.
Refs: #2095 #2120 
**Issue**

config: CNF installation (3.1) Limit cnf_setup to only one CNF

---

shard.lock
src/tasks/constants.cr
src/tasks/utils/cnf_installation/manifest.cr
src/tasks/utils/cnf_manager.cr

- Gather all the manifest files from the various CNFs into a single file called common_manifests.yaml
- Modified temp_template.yaml to reference common_manifests.yaml
- Removed code responsible for generating CNF templates as it is no longer used
- Added functionality in cleanup.cr to remove common_manifests.yaml as part of the cleanup process
- Update generated manifest, add namespace to each resource
- Depends on PR in helm library: https://github.com/cnf-testsuite/helm/pull/4
Refs: #2125 
Re-created from different branch, old PR: #2144

Feature: CNF Installation (4) Group several manifest into one file

---

.github/workflows/actions.yml
spec/workload/configuration_spec.cr
src/tasks/static.cr
src/tasks/workload/configuration.cr
src/tasks/workload/observability.cr
tools/curl_install_tester_docker_setup/Dockerfile

- open_metrics and prometheus_traffic - changed config map naming
- ip_addresses - removed, fully replaced by hardcoded_ip_addresses_in_k8s_runtime_configuration
- hardcoded_ip_addresses_in_k8s_runtime_configuration - change to use common_manifest.yml file
Refs: #2153

Feature: CNF Installation (5.1) Test preparation for new installation

---

spec/utils/utils_spec.cr
src/tasks/cnf_setup.cr
src/tasks/constants.cr
src/tasks/utils/cnf_installation/config.cr
src/tasks/utils/cnf_installation/deployment_management/deployment_manager_common.cr
src/tasks/utils/cnf_installation/deployment_management/helm_deployment_manager.cr
src/tasks/utils/cnf_installation/deployment_management/manifest_deployment_manager.cr
src/tasks/utils/cnf_installation/install_common.cr

Create new CNF installation process, that will support multiple deployments, be more comprehensible and easier to maintain.
Don't replace the old one yet, both installation methods should exist simultaneously
Refs: #2161

installation: CNF Installation (6) New installation process

---

.github/workflows/actions.yml

It also deletes cluster after Oran testing
No logs after failures in gates

Export Kind logs to ease debugging

---

.github/workflows/actions.yml
spec/workload/registry_spec.cr
src/tasks/utils/fluent_manager.cr
src/tasks/workload/compatibility.cr

- remove registry:5000 as unused
- stop listing registries out the spec tests installing them
- cache docker.io everywhere needed
- also override registry for private_registry_rolling et al

 Fix the private registry logic

---

.github/workflows/actions.yml

v3 is deprecated [1].
It will remove 50+ warnings
[1] https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

Update all github actions

---

.github/workflows/actions.yml

ubuntu-latest is currently raising warnings.
For more details, see https://github.com/actions/runner-images/issues/10636

Force the use of ubuntu-24.04

---

.github/workflows/actions.yml

Avoid 2 artifact conflicts:
- https://github.com/cnti-testcatalog/testsuite/actions/runs/12195578105/job/34088189833
- https://github.com/cnti-testcatalog/testsuite/actions/runs/12195578105/job/34088189949

Avoid 2 artifact conflicts

---

.github/workflows/actions.yml

Many delete cluster jobs fail by exiting 1 (it's shown as errors in summary).
This changes simply ensure that the next cleanups are done.
Please see https://github.com/cnti-testcatalog/testsuite/actions/runs/12236823830
Annotations 11 errors

Protect kind delete calls

---

.github/workflows/actions.yml

They are flaky and then skipped until they are fixed.
It also removes the following tags which no longer exist:
- testsuite-config-lifecycle
- testsuite-microservice
- testsuite-all
- chaos_container_kill
- chaos_cpu_hog

Skip both 5g and core tags

---

CNF_TESTSUITE_YML_USAGE.md
sample-cnfs/sample-elk-stack/cnf-testsuite.yml
spec/setup_spec.cr
src/tasks/utils/cnf_installation/config_versions/config_v2.cr
src/tasks/utils/cnf_installation/deployment_management/deployment_manager_common.cr
src/tasks/utils/cnf_installation/deployment_management/helm_deployment_manager.cr
src/tasks/utils/cnf_installation/deployment_management/manifest_deployment_manager.cr
src/tasks/utils/cnf_installation/install_common.cr

Add installation_priority parameter for specification of order for installation of deployments.
More info in documentation changes and issue.
Refs: #2176

Installation: add installation_priority parameter

---

.github/workflows/actions.yml
shard.lock
shard.yml
src/tasks/platform/observability.cr

Bitnami moved to Docker Hub [1] which forces us to login to Docker Hub (the workflow pulls too much Bitnami helm charts for the anon pull request limit).
[1] https://github.com/bitnami/containers/issues/75671

Login to Docker Hub

---

INSTALL.md
SOURCE_INSTALL.md
USAGE.md
spec/setup_spec.cr
src/tasks/cleanup.cr
src/tasks/utils/cnf_installation/install_common.cr

As of release v1.4.0 the `uninstall_all` task is broken and some testsuite dependencies cannot be uninstalled the intended way (cluster tools, etc.). This has been caused by the `CNFInstall.uninstall_cnf` function that was exiting with code 1 in case no CNF was installed, to fix this we have decided to relegate it to a warning (this makes the change significantly easier) and removed the `exit 1` command.
To avoid a similar situation in future, two spec tests have been added. The `uninstall_all` spec test required a change to `tools_uninstall` task since it previously gave no indication of passing. Further verification of `tools_uninstall` passing correctly should be added, but it might be out of the scope of this ticket.
Additionally some renaming regarding cleanup/uninstall has been left …

Fix: Repair `uninstall_all`

---

spec/setup_spec.cr

GH actions tag discovery command (`grep -roP --no-filename 'tags: \K(\[|")(.*)(\]|")' spec/ | tr -d '[],' | tr -s '\n' ' ' | xargs -n1 | sort -u | xargs | sed s/:/_/g`) requires that there is a space between colon and the left bracket. This has gone unnoticed in the #2184 pull request and it is the only pull request that went unchecked (other existing pull requests will likely need to be rebased), since it did not change any functionality but merely renamed some tasks, this should not be a problem.

Fix: cnf_installation tag was not being discovered after name change

---

sample-cnfs/sample_conditional_values_file/chart/Chart.yaml
sample-cnfs/sample_conditional_values_file/chart/templates/deployment.yaml
sample-cnfs/sample_conditional_values_file/chart/values.schema.json
sample-cnfs/sample_conditional_values_file/chart/values.yaml
sample-cnfs/sample_conditional_values_file/cnf-testsuite.yml
sample-cnfs/sample_conditional_values_file/test-values.yaml
spec/workload/installability_spec.cr
src/tasks/workload/compatibility.cr

Makes the underlying `helm lint` command, ran in the `helm_chart_valid` task, also verify if any override value files should be utilized. Also adds a spec test to make sure that this functions correctly. The `values.schema.json` file guarantees that without `-f test-values.yaml`, `helm lint` would not pass.
Refs: #2206
**Issue**

Fix: helm_chart_valid did not consider value files passed through helm_values

---

sample-cnfs/sample_good_signal_handling_tini/cnf-testsuite.yml

Failure was internal Jenkins dependency installation in init-container. Add 'installPlugins=false' helm value to not install unneeded dependencies to avoid similar problems in the future and speed up Jenkins deployment.
Refs: #NNN
**Issue**

Fix Jenkins CNF installation in CI

---

sample-cnfs/sample_good_signal_handling_tini/cnf-testsuite.yml
shard.lock
shard.yml
spec/5g/ran_spec.cr
spec/platform/observability_spec.cr
spec/workload/microservice_spec.cr
spec/workload/observability_spec.cr
spec/workload/operator_spec.cr
src/tasks/chaos_mesh_setup.cr
src/tasks/kind_setup.cr
src/tasks/opa_setup.cr
src/tasks/platform/resilience.cr
src/tasks/prereqs.cr
src/tasks/utils/cnf_installation/deployment_management/helm_deployment_manager.cr
src/tasks/utils/fluent_manager.cr
src/tasks/utils/jaeger.cr
src/tasks/utils/mysql.cr
src/tasks/utils/srsran.cr
src/tasks/utils/ueransim.cr
src/tasks/utils/utils.cr
src/tasks/workload/5g_validator.cr
src/tasks/workload/compatibility.cr

Updates to testsuite according to helm shard refactor (changes can be found here cnf-testsuite/helm#6). No other changes added besides removing duplicate from `shards.yaml` file.
Refs: #2199 
**Issue**

Updates to testsuite according to cnf-testsuite/helm#6
