USAGE.md

[Documentation] fix typo for valid Helm chart test
#43

fix typo for valid Helm chart test

---

PSEUDO-CODE.md
TEST-CATEGORIES.md
USAGE.md

- checks are for each end point type (alpha, beta, ga)
- phrasing matches other testing examples
TODO: maybe add a meta test that covers when a CNF *only uses GA*.  This could also be a summary...
https://github.com/cncf/cnf-conformance/issues/51

[Documentation] Updates to wording for API endpoint usage testing

---

README.md

- moved crystal to new section
- info on k8s
- info on upstream tools
https://github.com/cncf/cnf-conformance/issues/53

Added implementation overview section

---

MAINTAINERS.md

add 2 sections for core maintainers, maintainers
n/a
**Issue**

add 2 sections for core maintainers, maintainers

---

src/tasks/sample_coredns_setup.cr

Scalability Test: Can CNF increase and decrease capacity?
Installability Test: Helm chart valid? 
Security test: Are any containers running in privileged mode?
Configuration test: is there a readiness entry in the Helm chart?
Configuration test: is there a liveness entry in the Helm chart?
Issues:
- https://github.com/cncf/cnf-conformance/issues/56
- https://github.com/cncf/cnf-conformance/issues/57
- https://github.com/cncf/cnf-conformance/issues/24
- https://github.com/cncf/cnf-conformance/issues/6
- https://github.com/cncf/cnf-conformance/issues/55
* [] Tested locally on a new K8s cluster
* []  New feature (non-breaking change which adds functionality)
* []  I have updated the documentation accordingly.

Sample manifest now hard coded to point to coredns-coredns

---

src/tasks/security.cr

Security test: Are any containers running in privileged mode?
Issues:
- https://github.com/cncf/cnf-conformance/issues/55
* [] Tested locally on a new K8s cluster
* []  New feature (non-breaking change which adds functionality)
* []  I have updated the documentation accordingly.

Privileged mode now a part of the security tasks

---

README.md
USAGE.md

- cncf/cnf-conformance/issues/72
- #24
- #6
- #55
* [] Tested locally on a shared K8s cluster
* [] Tested locally on a new K8s cluster
* []  Have not tested
* []  Bug fix (non-breaking change which fixes an issue)
* []  New feature (non-breaking change which adds functionality)
* []  My change requires a change to the documentation.
* [] No updates required.

Documentation Update - README

---

README.md
USAGE.md
spec/cnf_conformance_spec.cr
src/tasks/configuration_lifecycle.cr
src/tasks/installability.cr
src/tasks/sample_coredns_setup.cr
src/tasks/scalability.cr
src/tasks/security.cr

Liveness/Readiness, Dynamic Manifest, Automated Tests, Documentation
Issues:
- #72
- #73
- #64
- #42
* [] Tested locally on a new K8s cluster
* [] No updates required.

Liveness/Readiness, Dynamic Manifest, Automated Tests, Documentation

---

.travis.yml
USAGE.md
spec/cnf_conformance_spec.cr
src/tasks/configuration_lifecycle.cr
src/tasks/helmenv_setup.cr
src/tasks/installability.cr
src/tasks/sample_coredns_setup.cr
src/tasks/scalability.cr
src/tasks/security.cr

- https://github.com/cncf/cnf-conformance/issues/6
**Issue**

Invalid Helm Chart

---

README.md
sample-cnfs/sample-bad_helm_coredns-cnf/cnf-conformance.yml
spec/cnf_conformance_spec.cr
spec/sample_coredns_setup_spec.cr
src/tasks/cleanup.cr
src/tasks/installability.cr
src/tasks/sample_coredns_setup.cr
src/tasks/setup.cr
src/tasks/utils.cr

Proof of Concept: Test using Travis-CI for CNF Conformance automated tests
- #80
- [] Documentation update
**Issue**

Proof of Concept: Test using Travis-CI for CNF Conformance automated tests

---

README.md
sample-cnfs/sample-bad_helm_coredns-cnf/cnf-conformance.yml
spec/cnf_conformance_spec.cr
spec/sample_coredns_setup_spec.cr
src/tasks/cleanup.cr
src/tasks/installability.cr
src/tasks/sample_coredns_setup.cr
src/tasks/setup.cr
src/tasks/utils.cr

Enable Travis for running automated tests 
- https://github.com/cncf/cnf-conformance/issues/80
**Issue**

Enable Travis for running automated tests

---

README.md

- Move Installation guide from README.md to INSTALL.md
- add link to INSTALL.md
Issues:
- https://github.com/cncf/cnf-conformance/issues/28
- https://github.com/cncf/cnf-conformance/issues/NNN
**Issue**

add link to INSTALL.md

---

INSTALL.md
README.md
sample-cnfs/sample_privileged_cnf_setup_coredns/README.md
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/Chart.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/README.md
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/NOTES.txt
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/_helpers.tpl
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/clusterrole-autoscaler.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/clusterrole.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/clusterrolebinding-autoscaler.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/clusterrolebinding.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/configmap-autoscaler.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/configmap.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/deployment-autoscaler.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/deployment.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/podsecuritypolicy.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/service-metrics.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/service.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/serviceaccount-autoscaler.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/serviceaccount.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/templates/servicemonitor.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/chart/values.yaml
sample-cnfs/sample_privileged_cnf_setup_coredns/cnf-conformance.yml
spec/cnf_conformance_spec.cr
spec/security_spec.cr
src/tasks/sample_coredns_setup.cr

Update README.md and create INSTALL.md 
- https://github.com/cncf/cnf-conformance/issues/28
**Issue**

Update README.md and create INSTALL.md 

---

README.md

- add get involved and license to README.md
- https://github.com/cncf/cnf-conformance/issues/92
**Issue**

add get involved and license to README

---

sample-cnfs/sample_privileged_cnf_setup_coredns/non-whitelisted-conformance.yml
sample-cnfs/sample_privileged_cnf_setup_coredns/whitelisted-conformance.yml
spec/cnf_conformance_spec.cr
spec/security_spec.cr
src/tasks/sample_coredns_setup.cr

Add tests for privileged containers.
- cncf/cnf-conformance#55
**Issue**

Add privileged mode test cncf/cnf-conformance#55

---

USAGE.md

- update tests in USAGE.md using To Do, PoC and :heavy_check_mark: 
How to use these:
- ToDo - This covers both not started and WIP items
- PoC - This covers items which are proof of concept/prototypes
- :heavy_check_mark: - this covers items which are on `master` and pass all QA, automated tests and any acceptance criteria
- https://github.com/cncf/cnf-conformance/issues/95
**Issue**
- https://github.com/cncf/cnf-conformance/issues/NNN
**Issue**

update USAGE using To Do, PoC and :heavy check:

---

.gitignore
USAGE.md
points.yml
spec/cnf_conformance_spec.cr
spec/configuration_lifecycle_spec.cr
spec/installability_spec.cr
spec/sample_coredns_setup_spec.cr
spec/security_spec.cr
spec/utils_spec.cr
src/cnf-conformance.cr
src/tasks/cleanup.cr
src/tasks/configuration_lifecycle.cr
src/tasks/installability.cr
src/tasks/platform/platform.cr
src/tasks/scalability.cr
src/tasks/security.cr
src/tasks/setup.cr
src/tasks/utils.cr

Proof of Concept: Scoring results from tests
- https://github.com/cncf/cnf-conformance/issues/30
**Issue**

Proof of Concept: Create PoC scoring system for Workload / Application tests

---

INSTALL.md
KIND-INSTALL.md

kind install instructions
- https://github.com/cncf/cnf-conformance/issues/77
**Issue**

kind install instructions

---

EXAMPLE-CNFS
INSTALL.md
config.yml
spec/installability_spec.cr
spec/sample_coredns_setup_spec.cr
spec/security_spec.cr
spec/utils_spec.cr
src/tasks/api_snoop_setup.cr
src/tasks/chart_testing_setup.cr
src/tasks/cleanup.cr
src/tasks/cnf_conformance_setup.cr
src/tasks/compatibility.cr
src/tasks/configuration_lifecycle.cr
src/tasks/hardware.cr
src/tasks/helmenv_setup.cr
src/tasks/installability.cr
src/tasks/observability.cr
src/tasks/opa_setup.cr
src/tasks/sample_coredns_setup.cr
src/tasks/scalability.cr
src/tasks/security.cr
src/tasks/sonobuoy_setup.cr
src/tasks/stateless.cr
src/tasks/utils/sample_utils.cr
src/tasks/utils/utils.cr

New features can have toggles to enable/disable
list of potential CNFS
Instructions for vendor to follow to install and use the test suite
- https://github.com/cncf/cnf-conformance/issues/49
**Issue**

Adding new EXAMPLE-CNFs, Vendor  Usage Instructions, and Feature Toggle support

---

EXAMPLE-CNFS.md

Updates to documentation on example CNFs

---

INSTALL.md

CNF Developer is more encompassing a term for who can work on a CNF (testing, creating, forking, etc)
Fixes: #109 
**Issue**

WIP Updating Vendor reference to say CNF Developer

---

config.yml
example-cnfs/envoy/README.md
example-cnfs/envoy/cnf-conformance.yml
spec/utils_spec.cr
src/tasks/configuration_lifecycle.cr
src/tasks/installability.cr
src/tasks/sample_coredns_setup.cr
src/tasks/utils/sample_utils.cr
src/tasks/utils/utils.cr

Using more general CNF Developer term
Fixes: #109 
**Issue**

Updating Vendor reference to say CNF Developer

---

INSTALL.md
config.yml
example-cnfs/envoy/README.md
example-cnfs/envoy/cnf-conformance.yml
src/tasks/configuration_lifecycle.cr
src/tasks/installability.cr
src/tasks/sample_coredns_setup.cr
src/tasks/utils/sample_utils.cr
src/tasks/utils/utils.cr

Merging some `master` changes back to `develop`

Merging changes back from master

---

.github/workflows/crystal.yml
example-cnfs/ip-forwarder/README.md
example-cnfs/ip-forwarder/cnf-conformance.yml
example-cnfs/ip-forwarder/csp/.helmignore
example-cnfs/ip-forwarder/csp/Chart.yaml
example-cnfs/ip-forwarder/csp/templates/_helpers.tpl
example-cnfs/ip-forwarder/csp/templates/configmap.yaml
example-cnfs/ip-forwarder/csp/templates/deployment.yaml
example-cnfs/ip-forwarder/csp/values.yaml
src/tasks/installability.cr
src/tasks/sample_coredns_setup.cr
src/tasks/security.cr
src/tasks/utils/sample_utils.cr

Test use case from CNF Testbed.  Make minimal changes needed to deploy and run test.  Identify updates needed in test code.
Fixes: #143
**Issue**

[CNFs] Test VPP pipeline service chain use case with the CNF Conformance Test Suite

---

.travis.yml
INSTALL.md

Binary release process
Fixes: https://github.com/cncf/cnf-conformance/issues/119
**Issue**

Feature binary releases 119

---

INSTALL.md

correct sha sum invocation

---

example-cnfs/ip-forwarder/README.md
example-cnfs/ip-forwarder/cnf-conformance.yml
example-cnfs/ip-forwarder/vpp/.helmignore
example-cnfs/ip-forwarder/vpp/Chart.yaml
example-cnfs/ip-forwarder/vpp/templates/bridge.yaml
example-cnfs/ip-forwarder/vpp/templates/configmap.yaml
example-cnfs/ip-forwarder/vpp/templates/deployment.yaml
example-cnfs/ip-forwarder/vpp/values.yaml

Adds a basic VPP based IP Forwarder to the example CNFs.
Uses Multus to create a host bridge, with each container having one interface attached and configured through VPP.
#148 
**Issue**

[CNF Example] Basic VPP IP forwarder (#148)

---

scoring_config/points_v1.yml
src/tasks/utils/utils.cr

refs https://github.com/cncf/cnf-conformance/issues/119
make points configuration configurable w/ env vars at @wavell 's suggestion
Refs: #119 
**Issue**

default and overrideable points.yml

---

example-cnfs/envoy/cnf-conformance.yml
example-cnfs/ip-forwarder/cnf-conformance.yml
example-cnfs/vpp-3c2n-csp-use-case/cnf-conformance.yml

Setting a image release for the current examples

---

INSTALL.md
scoring_config/points_v1.yml
src/tasks/utils/utils.cr

polish for binary release
Refs: #119 
**Issue**

binary updates for static, travis, points

---

example-cnfs/linkerd2/README.md
example-cnfs/linkerd2/cnf-conformance.yml

init commit of linkerd2 example

---

spec/utils/sample_utils_spec.cr

```
Failures:                                                        
1) SampleUtils 'sample_destination_dir' should return the full path of the potential destination cnf directory based on the source sample cnf directory
Failure/Error: sample_destination_dir("sample-generic-cnf").should contain("cnf-conformance/cnfs/sample-generic-cnf")
Expected:   "/home/pair/workspace/taylor/qa/testmay4/cnf-conformance-test2/cnfs/sample-generic-cnf"
to include: "cnf-conformance/cnfs/sample-generic-cnf"     
Finished in 44.39 seconds                                                   
1 examples, 1 failures, 0 errors, 0 pending                                                                
Failed examples:                                                 
crystal spec spec/utils/sample_utils_spec.cr:93 # …
```

Fix hardcoded conformance directory path1

---

USAGE.md

https://github.com/cncf/cnf-conformance/issues/69
updated documentation for helm_deploy
Refs: #NNN
- [x ] Verified all A/C passes
**Issue**

updated documentation for helm_deploy

---

KIND-INSTALL.md

Updated documentation with steps needed to install Multus and CNIs in a Kind cluster.
N/A
**Issue**

Steps for adding Multus and CNIs to Kind

---

USAGE.md

#69 documentation for helm_deploy
Documentation for helm_deploy
Refs: #69 
**Issue**

#69 Documentation for helm_deploy

---

USAGE.md
points.yml
sample-cnfs/sample_coredns_hardcoded_ips/README.md
sample-cnfs/sample_coredns_hardcoded_ips/chart/.helmignore
sample-cnfs/sample_coredns_hardcoded_ips/chart/Chart.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/README.md
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/NOTES.txt
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/_helpers.tpl
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/clusterrole-autoscaler.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/clusterrole.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/clusterrolebinding-autoscaler.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/clusterrolebinding.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/configmap-autoscaler.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/configmap.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/deployment-autoscaler.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/deployment.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/poddisruptionbudget.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/podsecuritypolicy.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/service-metrics.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/service.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/serviceaccount-autoscaler.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/serviceaccount.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/templates/servicemonitor.yaml
sample-cnfs/sample_coredns_hardcoded_ips/chart/values.yaml
sample-cnfs/sample_coredns_hardcoded_ips/cnf-conformance.yml
spec/cnf_conformance_spec.cr
spec/configuration_lifecycle_spec.cr
spec/utils/utils_spec.cr
src/tasks/configuration_lifecycle.cr

This PR adds the 'hardcoded_ip_addresses_in_k8s_runtime_configuration' conformance test.
Refs: cncf/cnf-conformance#68
**Issue**

Add test for hardcoded IPs in the K8s resource configuration cncf/cnf-conformance#68

---

src/tasks/configuration_lifecycle.cr
src/tasks/installability.cr
src/tasks/microservice.cr
src/tasks/platform/platform.cr
src/tasks/security.cr

- :heavy_check_mark: for PASSED
- :x: for FAILED
fixed double colon typo
- #191 
**Issue**

Emoji for pass fail

---

MAINTAINERS.md

Added self to list of maintainers. Also removed template line
**Issue**

Add Michael to list of MAINTAINERS

---

INSTALL.md
USAGE.md
example-cnfs/coredns/cnf-conformance.yml
spec/cnf_conformance_spec.cr
spec/fixtures/cnf-conformance.yml
spec/installability_spec.cr
spec/microservice_spec.cr
spec/setup_spec.cr
spec/spec_helper.cr
spec/utils/sample_utils_spec.cr
src/cnf-conformance.cr
src/tasks/cnf_setup.cr
src/tasks/installability.cr
src/tasks/utils/sample_utils.cr
src/tasks/utils/utils.cr

[CNF Developer UX] Support passing cnf configuration to all and cleanup commands to simplify CLI usage
Refs: #213
**Issue**

[CNF Developer UX] Support passing cnf configuration to all and cleanup commands to simplify CLI usage

---

example-cnfs/ip-forwarder/cnf-conformance.yml
sample-cnfs/sample_coredns/cnf-conformance.yml
spec/installability_spec.cr
spec/microservice_spec.cr
src/cnf-conformance.cr
src/tasks/configuration_lifecycle.cr
src/tasks/installability.cr
src/tasks/microservice.cr
src/tasks/scalability.cr
src/tasks/utils/sample_utils.cr

Fix bugs with reasonable_startup, rolling_update & hardcoded ip tests.
Refs: #NNN
**Issue**

Fix bugs with reasonable_startup, rolling_update & hardcoded ip tests.

---

.travis.yml
INSTALL.md
shard.lock
shard.yml

Trying to build the source code using crystal 0.34.0-1 version raises the following error:
```
Showing last frame. Use --error-trace for full trace.                                                                                                           
In lib/halite/src/halite/client.cr:160:17                                                                                                                       
160 | rescue ex : IO::Timeout                                                                                                                                  
^----------                                                                                                                                  
Error: undefined constant IO::Timeout   
```
This change fixes that compilation …

Update Halite version to 0.10.5

---

KIND-INSTALL.md

Updated references used by the Kind installation document and reduced the instructions required to install and configure Kind
Refs: None
**Issue**

Update KinD documentation

---

CNF_CONFORMANCE_YML_USAGE.md
README.md
TEST-CATEGORIES.md

The old link in README.md doesn't makes sense because of **your-github-user**. It eventually resulted into a broken link. Made the necessary changes to keep it smooth.

Improve documentation.

---

.travis.yml
shard.lock
shard.yml
spec/microservice_spec.cr

Bugfix: microservice test doesn't clean up envoy
Refs: #240
**Issue**

Bugfix: microservice test doesn't clean up envoy

---

spec/cnf_conformance_spec.cr
src/cnf-conformance.cr
src/tasks/configuration_lifecycle.cr
src/tasks/installability.cr
src/tasks/microservice.cr
src/tasks/scalability.cr
src/tasks/security.cr
src/tasks/utils/utils.cr

Display the maximum number of points with the final score, aka 99/100
Refs: #181 
**Issue**

Display the maximum number of points with the final score, aka 99/100

---

src/tasks/resilience.cr

Adding emojis 📦💻🐷📈 to test for #231

Add emoji 📦💻🐷📈 for cpu hog test #231

---

src/tasks/resilience.cr

Adding 📶☠️  emoji to chaos network test #157

---

README.md

- update README
- change twice monthly to monthly
Refs: N/A
**Issue**

update TUG to monthly

---

USAGE.md

#158
Container kill chaos test
Refs: #158 
- [] New feature (non-breaking change which adds functionality)
**Issue**

#158 container kill documentation

---

INSTALL.md
README.md
TEST-CATEGORIES.md

- documentation updates
- "CN" was not clear, "Cloud Native" is more clear
- Added link to contributing guide in README
- Moved CNF Developer Install instructions to top of INSTALL
Refs: 
- found when working on #140 
- #273 
- #220 
**Issue**

updating README, Test Categories and Install Guide

---

INSTALL.md

updates static build command to work again
Refs: #NNN
**Issue**

update static build command

---

src/tasks/resilience.cr

Pin ChaosMesh version to v0.8.0
Refs: #288
**Issue**

Pin ChaosMesh version to v0.8.0

---

MAINTAINERS.md

Added self to list of maintainers.
**Issue**

update MAINTAINERS adding agentpoyo

---

spec/utils/utils_spec.cr
src/tasks/resilience.cr
src/tasks/statelessness.cr
src/tasks/utils/utils.cr

Upsert now stop double counting of test scores
Refs: #159
**Issue**

Upsert now stop double counting of test scores

---

.github/ISSUE_TEMPLATE/bug-report.md
CONTRIBUTING.md
README.md
USAGE.md
spec/utils/utils_spec.cr
src/cnf-conformance.cr
src/tasks/utils/utils.cr

refs #291 #280 
refs #291 #280 
**Issue**

Feature/280 log level change aka logging refactor p3 

---

spec/utils/release_manager_spec.cr
src/tasks/utils/release_manager.cr

Add version command
Refs: #284
**Issue**

#284 asset upload now compares local hash with remote master hash

---

src/tasks/utils/release_manager.cr

Add version command
Refs: #284
**Issue**

Force version name change head > master

---

src/tasks/utils/release_manager.cr

Add version command
Refs: #284
**Issue**

Version command#284 Uploading corrupted files

---

src/tasks/utils/release_manager.cr
tools/ephemeral_env/README.md

Documentation Ephemeral documentation
Static build capability
cncf/cnf-conformance#206
**Issue**

Ephemeral dev env#206 Documentation

---

spec/utils/utils_spec.cr
src/cnf-conformance.cr
src/tasks/api_snoop_setup.cr
src/tasks/chart_testing_setup.cr
src/tasks/cleanup.cr
src/tasks/cnf_setup.cr
src/tasks/configuration_lifecycle.cr
src/tasks/helmenv_setup.cr
src/tasks/installability.cr
src/tasks/microservice.cr
src/tasks/opa_setup.cr
src/tasks/platform/platform.cr
src/tasks/resilience.cr
src/tasks/scalability.cr
src/tasks/security.cr
src/tasks/setup.cr
src/tasks/sonobuoy_setup.cr
src/tasks/statelessness.cr
src/tasks/utils/release_manager.cr
src/tasks/utils/sample_utils.cr
src/tasks/utils/system_information/curl.cr
src/tasks/utils/system_information/helm.cr
src/tasks/utils/system_information/kubectl.cr
src/tasks/utils/system_information/wget.cr
src/tasks/utils/utils.cr

so it logs even when main logger debugger level is set differenty
refs cncf/cnf-conformance#280
Refs: #280 
**Issue**

move verbose logging stuff to a seperate logger

---

src/tasks/utils/release_manager.cr

Static build capability
(remove non-static build)
cncf/cnf-conformance#206
**Issue**

Ephemeral dev env#206 Static build

---

README.md
curl_install.sh

Add Curl install option cncf/cnf-conformance#301
Refs: cncf/cnf-conformance#301
**Issue**

Add Curl install option cncf/cnf-conformance#301

---

tools/ephemeral_env/README.md

Ephemeral build rule documentation
Ephemeral build rule documentation
Refs: #NNN
**Issue**

#206 documentation update

---

spec/curl_install_spec.cr

Add missing spec test for Curl install command.
Refs: cncf/cnf-conformance#301
**Issue**

Add spec for Curl install#301

---

curl_install.sh
spec/curl_install_spec.cr

Curl install add unsupported shell message
Refs: cncf/cnf-conformance#301
**Issue**

Curl install add unsupported shell message cncf/cnf-conformance#301

---

CONTRIBUTING.md
README.md

refs #https://github.com/cncf/cnf-conformance/issues/339
- add link to good first issues to readme
Refs: #https://github.com/cncf/cnf-conformance/issues/339
**Issue**

Add good first issues & meeting minutes to README

---

src/tasks/installability.cr
src/tasks/microservice.cr

[Feature] Replace hardcoded emojis with variables
Refs: #336
**Issue**

move some emoji to variables

---

USAGE.md
shard.lock
shard.yml

Add code style linter and how to use to repo
Refs: #330 
**Issue**

Add linter and usage doc

---

.travis.yml
shard.lock
shard.yml
tools/ephemeral_env/Dockerfile

Make cnf conformance work on crystal latest crystal as of this ticket which is `0.35.1`
Refs: #311 
**Issue**

Maint/upgrade crystal to 0.35.1 311

---

src/tasks/configuration_lifecycle.cr
src/tasks/microservice.cr
src/tasks/security.cr

Add emojis to tests that are missing emojis
Refs: #334 

Add emojis to tests that are missing emojis

---

.travis.yml

Don't publish release if github keys aren't set
Refs: #NNN
**Issue**

Don't publish release if github keys aren't set

---

USAGE.md
points-all.yml
points.yml
spec/platform/hardware_and_scheduler.cr
spec/utils/kubectl_client_spec.cr
spec/utils/utils_spec.cr
src/tasks/platform/hardware_and_scheduling.cr
src/tasks/utils/kubectl_client.cr
src/tasks/utils/system_information/helm.cr

Add OCI compliant container runtime test
Refs: cncf/cnf-conformance#327
**Issue**

Add OCI compliant container runtime test 

---

README.md

Refs #317
add Code of Conduct to README
Refs: #317 
**Issue**

add Code of Conduct to README

---

spec/platform/hardware_and_scheduler.cr

Add missing spec test tag for platform:oci_compliant
Refs: cncf/cnf-conformance#327
**Issue**

Add missing spec test tag for platform:oci_compliant

---

USAGE.md

#322 updated usage docs for running node_failure command

---

config.yml
points-all.yml
points.yml
spec/utils/utils_spec.cr
src/tasks/platform/hardware_and_scheduling.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr
src/tasks/utils/utils.cr

Platform now runs only platform tasks and has totals for only platform categories
Refs: #327
**Issue**

#327 platform totals

---

points-all.yml
points.yml
spec/platform/resilience_spec.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr

Non-POC Worker Node Recover Test #320
Refs: cncf/cnf-conformance#320
**Issue**

Non-POC Worker Node Recover Test #320

---

.travis.yml
tools/ephemeral_env/ephemeral_env.cr

Add support for using Packet.net for executing CI Jobs.
Refs: cncf/cnf-conformance#384
**Issue**

Add support for using Packet.net for executing CI Jobs. #384

---

INSTALL.md
README.md
USAGE.md
tools/curl_install_tester_docker_setup/Dockerfile
tools/curl_install_tester_docker_setup/README.md

source install instructions still need work
also still decidding on if development stuff belongs in install.md at
all
Refs: #370 
**Issue**

Overhaul INSTALL docs

---

README.md

Documentation: Duplicate 'multiple vendors' language
**Issue**

Documentation: Duplicate 'multiple vendors' language

---

spec/prereqs_spec.cr
spec/utils/system_information/git_spec.cr
src/tasks/prereqs.cr
src/tasks/utils/system_information/git.cr

Git now part of prereqs
Refs: #385
**Issue**

Feature/#385 Git now part of prereqs

---

.travis.yml
spec/platform/hardware_and_scheduler_spec.cr
src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/sonobuoy_setup.cr
tools/ephemeral_env/ephemeral_env.cr

Fix bug with Travis jobs not failing with correct exitcode.
Refs: cncf/cnf-conformance/issues/404
**Issue**

Fix bug with Travis jobs not failing with correct exitcode #404

---

.travis.yml

Adds cleanup task to all new Travis jobs.
Refs: cncf/cnf-conformance#399
**Issue**

Fix Bug with Travis job limits #399

---

.travis.yml
test.sh

Fix bug where cleanup doesn't run when the Travis job fails.
Refs: cncf/cnf-conformance/issues/422
**Issue**

Fix bug where cleanup doesn't run when the Travis job fails. #422

---

.travis.yml

Switch to using the Travis runner for CI Jobs
Refs: #NNN
**Issue**

Switch to using the Travis runner for CI Jobs

---

.travis.yml
src/tasks/utils/utils.cr
tools/curl_install_tester_docker_setup/Dockerfile
tools/curl_install_tester_docker_setup/README.md

Use docker container to tset binary inside of empty folder (so we can catch bugs introduced by files neded from the source that won;t be ther for curl installs)
Refs: #398 
**Issue**

test binary in empty folder

---

INSTALL.md

#387 prereq docs updated
Refs: #387
**Issue**

#387 prereq docs updated

---

spec/configuration_lifecycle_spec.cr
src/tasks/configuration_lifecycle.cr
src/tasks/prereqs.cr
src/tasks/utils/system_information/helm.cr

helm prerequisite checker
Refs: #397
**Issue**

#397 helm prerequisite checker

---

.circleci/Dockerfile
.circleci/config.yml
.circleci/retry.sh

Circle Ci build
Refs: #428
**Issue**

Circleci project setup

---

spec/configuration_lifecycle_spec.cr
src/tasks/configuration_lifecycle.cr
src/tasks/utils/cnf_manager.cr

#402
Update frequently failing static workload test that checks for ip addresses
#402
Refs: #402
**Issue**

Update frequently failing static workload test that checks for ip addresses #402

---

FAQ.md

- small recommendations
Small changes to FAQ.md draft
https://github.com/cncf/cnf-conformance/issues/390
**Issue**

Small changes to FAQ.md draft

---

src/tasks/utils/utils.cr

[BUG] weird errors when a command is not found. #296
Refs: #296
**Issue**

#296 [BUG] weird errors when a command is not found. 

---

src/tasks/setup.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/system_information/helm.cr

Update prerequisite checker to "not download helm if helm is in $PATH"
#397
Refs: #397
**Issue**

Update prerequisite checker to "not download helm if helm is in $PATH" #397

---

TEST-CATEGORIES.md
USAGE.md

updated documentation for static workload test that checks for ip addresses #402 
Refs: #402 
**Issue**

updated documentation for ipaddress conformance test

---

FAQ.md

FAQ.md initial creation and documentation to add for project reference and use.
Refs: #390
**Issue**

Faq documentation #390

---

FAQ.md

- replace cncf slack URL with  https://slack.cncf.io/ 
- add TC's slack profile URL
- punctuation
Refs #390
**Issue**

update https://slack.cncf.io/ and punctuation

---

.github/workflows/actions.yml

#Shards install bug
Shards install bug
Installs shards outside of container in order to avoid intermittent memory errors 
Refs: #438
**Issue**

Shards install bug

---

cnf-wg/README.md

Refs: #NNN
- [ x] Documentation update
**Issue**

add chairs section

---

README.md

Adding benefits of the CNF Conformance program.

add why conformance matters

---

cnf-wg/charter.md

Additional governance and operations details

add governance and operations

---

CONTRIBUTING.md

Daylight savings time ended on Nov 1, 9:15am Central Time became 15:15 UTC

update meeting time to 15:15-16:00 UTC

---

.github/workflows/actions.yml
spec/cnf_conformance_spec.cr
spec/installability_spec.cr
spec/scalability_spec.cr
src/tasks/cnf_setup.cr

Fix memory error bug on cnf-conformance builds.
Switched to LLVM version 10.
Split platform tests out from workload tests.
Increased speed of test by using wait_count=0
Refs: github.com/cncf/cnf-conformance#429
**Issue**

Fix memory error bug on cnf-conformance builds.

---

spec/cnf_conformance_all/cnf_conformance_container_chaos_spec.cr
spec/cnf_conformance_all/cnf_conformance_network_chaos_spec.cr
spec/cnf_conformance_all/cnf_conformance_spec.cr
spec/microservice_spec.cr
spec/resilience/container_chaos_spec.cr
spec/resilience/network_chaos_spec.cr

Split specs for faster builds
Refs: 
**Issue**

Split specs for faster builds

---

example-cnfs/coredns/cnf-conformance.yml
example-cnfs/envoy/cnf-conformance.yml
sample-cnfs/sample-coredns-cnf-bad-chart/cnf-conformance.yml
sample-cnfs/sample-coredns-cnf/cnf-conformance.yml
sample-cnfs/sample-generic-cnf/cnf-conformance.yml
sample-cnfs/sample-large-cnf/cnf-conformance.yml
spec/fixtures/cnf-conformance-invalid-and-unmapped-keys.yml
spec/fixtures/cnf-conformance-unmapped-keys-and-subkeys.yml
spec/fixtures/cnf-conformance.yml
src/tasks/helmenv_setup.cr
tools/curl_install_tester_docker_setup/Dockerfile
tools/ephemeral_env/Dockerfile

helm repo now points to new helm repo charts.helm.sh

---

USAGE.md
points-all.yml
points.yml
scoring_config/points_v1.yml
spec/cnf_conformance_all/cnf_conformance_container_chaos_spec.cr
spec/cnf_conformance_all/cnf_conformance_network_chaos_spec.cr
src/cnf-conformance.cr
src/tasks/hardware.cr

rename command to Run all hardware resources and scheduling tests #44
Refs: #44
**Issue**

Rename command to Run all hardware resources and scheduling tests #44

---

cnf-wg/README.md

CNF WG meetings TBD
Refs: #NNN
**Issue**

CNF WG meetings TBD

---

USAGE.md

#44 Update documentation
Refs: #44
**Issue**

#44 Update documentation for platform hardware and scheduling

---

.github/workflows/actions.yml
example-cnfs/coredns/cnf-conformance.yml
example-cnfs/envoy/cnf-conformance.yml
sample-cnfs/sample-coredns-cnf-bad-chart/cnf-conformance.yml
sample-cnfs/sample-coredns-cnf/cnf-conformance.yml
sample-cnfs/sample-generic-cnf/cnf-conformance.yml
sample-cnfs/sample-large-cnf/cnf-conformance.yml
spec/fixtures/cnf-conformance-invalid-and-unmapped-keys.yml
spec/fixtures/cnf-conformance-unmapped-keys-and-subkeys.yml
spec/fixtures/cnf-conformance.yml
src/tasks/helmenv_setup.cr

##474 helm repo now cncf.gitlab.io
#474 helm repo now cncf.gitlab.io
Refs: #474
**Issue**

#474 helm repo now cncf.gitlab.io

---

cnf-wg/README.md
cnf-wg/charter.md

- format updates to responsibilities and deliverables
- cleanup and clarifications in responsibilities
Refs: n/a
n/a
**Issue**
n/a

Cleanup and clarification of CNF WG responsibilities

---

USAGE.md

"Validating cnf", https://github.com/cncf/cnf-conformance/blob/master/USAGE.md#validating-a-cnf-conformanceyml-file should come after "building executable" https://github.com/cncf/cnf-conformance/blob/master/USAGE.md#building-the-executable
Refs: #472
**Issue**

updated order of example commands

---

.github/workflows/actions.yml
EXAMPLE-CNFS.md

Pantheon Network Service Mesh Documentation #464
Refs: #464
**Issue**

Pantheon Network Service Mesh Documentation #464

---

.github/workflows/actions.yml
.github/workflows/skip.sh

Add support for skipping build for doc only changes

---

.github/workflows/actions.yml

Add conditional for crystal spec job #478

---

CODE-STRUCTURE.md

Documentation update and #464 test
Refs: #464
**Issue**

Pure Documentation update and #464-2 test

---

cnf-wg/README.md

Added day of first call, notes, dial in, urls for slack channel and workspace
**Issue**

add meeting details

---

.github/workflows/actions.yml

Add tmate debug

---

.github/workflows/actions.yml
.github/workflows/skip.sh

Fix bug so that skip.sh will work on master

---

.github/workflows/skip.sh

Fix bash syntax bug

---

.github/workflows/actions.yml

Add permanent debug flag for release job
Refs: #NNN
**Issue**

Add permanent debug flag for release job

---

.github/workflows/actions.yml

Add permanent debug flag for skip job
Refs: #NNN
**Issue**

Add permanent debug flag for skip job

---

.github/workflows/actions.yml

Fix bug with permanent debug support for github actions.
Refs: #NNN
**Issue**

Fix bug with permanent debug support for github actions

---

spec/cnf_conformance_all/cnf_conformance_spec.cr
src/tasks/workload/configuration_lifecycle.cr

configuration_lifecycle
add rollback and rolling v change alias to workload #516
Refs: #82 
**Issue**

add rollback and rolling v change alias to workload

---

spec/cnf_conformance_all/cnf_conformance_spec.cr

hopefully fix array order test break

---

src/tasks/utils/release_manager.cr

if git tag is empty, use empty string

---

CNF_CONFORMANCE_YML_USAGE.md
INSTALL.md
POINTS.md
SOURCE_INSTALL.md

Update INSTALL.md to streamline instructions, remove redundancy, and move most source based information to a new document.
Refs:  #526
**Issue**

Refactoring Install Docs into Source separate from Binary

---

example-cnfs/nsm/cnf-conformance.yml
example-cnfs/nsm/helm_chart/values.yaml
src/tasks/utils/cnf_manager.cr
src/tasks/utils/kubectl_client.cr
src/tasks/workload/microservice.cr
src/tasks/workload/resilience.cr

[Proof of Concept] Add support for testing the 1st level of dependent Helm charts #536

---

README.md

fixed grammatical mistakes
Refs: #550 
**Issue**

#550 checked README.md

---

CNF_CONFORMANCE_YML_USAGE.md

- Updates for changes in configuration needs
- TOC
- adding descriptions
- clarity on required vs optional
- example configuration updates
Refs: #537

Doc/cnf conformance yml usage #537

---

src/tasks/utils/release_manager.cr

Use markdown bullets and removed unnecessary pre text from dev snapshot UPDATEs section
Refs: #528 
**Issue**

#528 Update release_manager.cr

---

src/tasks/platform/platform.cr

Replaced hardcoded emojis with variables
Refs: #336 
**Issue**

#336 moved emoji to variable

---

spec/utils/release_manager_spec.cr
src/tasks/utils/release_manager.cr

Update release manager to fetch notes from latest snapshot.
Refs: cncf/cnf-conformance/issues/527
**Issue**

Update release manager to fetch notes from latest snapshot

---

src/tasks/utils/release_manager.cr

Only publish release on 'master'.
Refs: cncf/cnf-conformance#527
**Issue**

Only publish release on 'master' 

---

src/tasks/utils/release_manager.cr

'master' triggers a snapshot cncf/cnf-conformance#527
Refs: #527
**Issue**

'master' triggers a snapshot cncf/cnf-conformance#527

---

src/tasks/litmus_setup.cr

moved emoji to variables
Refs: #336 
**Issue**

#336 moved emoji to variables

---

spec/utils/cnf_manager_spec.cr
spec/utils/utils_spec.cr
src/tasks/cnf_setup.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/utils.cr

cnf installation refactor #569
Refs: #569
**Issue**

cnf installation refactor #569

---

spec/workload/configuration_lifecycle_spec.cr

unbreak build
Refs: #508 
**Issue**

disable immutable_configmap specs until we fix

---

spec/utils/release_manager_spec.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/helm.cr
src/tasks/utils/kubectl_client.cr
src/tasks/utils/release_manager.cr
src/tasks/utils/system_information/kubectl.cr
src/tasks/workload/configuration_lifecycle.cr

[BUG] cnf-conformance.yml helm repo is not added when running cnf_setup #546
Refs: #546
**Issue**

[BUG] cnf-conformance.yml helm repo is not added when running cnf_setup #546

---

src/tasks/cleanup.cr
src/tasks/dockerd_setup.cr
src/tasks/utils/kubectl_client.cr
src/tasks/workload/microservice.cr
tools/dockerd/manifest.yml

Support running the test suite against a CNF using a username/password protected Docker Hub or private Official Docker registry
Refs: #594
**Issue**

Support running the test suite against a CNF using a username/password protected Docker Hub or private Official Docker registry 

---

spec/cnf_conformance_all/cnf_conformance_container_chaos_spec.cr
spec/cnf_conformance_all/cnf_conformance_network_chaos_spec.cr
spec/cnf_conformance_all/cnf_conformance_spec.cr
spec/utils/cnf_manager_spec.cr
spec/utils/utils_spec.cr
src/cnf-conformance.cr
src/tasks/cleanup.cr
src/tasks/platform/hardware_and_scheduling.cr
src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/utils.cr
src/tasks/workload/configuration_lifecycle.cr
src/tasks/workload/installability.cr
src/tasks/workload/microservice.cr
src/tasks/workload/resilience.cr
src/tasks/workload/scalability.cr
src/tasks/workload/security.cr
src/tasks/workload/statelessness.cr

Refactor of utils in preparation of #603
Refs: #603
**Issue**

Refactor utils

---

spec/cnf_conformance_all/cnf_conformance_container_chaos_spec.cr
spec/cnf_conformance_all/cnf_conformance_network_chaos_spec.cr
spec/cnf_conformance_all/cnf_conformance_spec.cr
spec/workload/resilience/container_chaos_spec.cr
spec/workload/resilience/network_chaos_spec.cr
spec/workload/resilience/pod_network_latency_spec.cr
src/tasks/chaos_mesh_setup.cr
src/tasks/utils/cnf_manager.cr
src/tasks/workload/resilience.cr

CNF manager removed direct apply and calls
Refs: #590
**Issue**

CNF manager removed direct apply and calls

---

src/tasks/utils/cnf_manager.cr

Fix release name bug.
Refs: cncf/cnf-conformance#612
**Issue**

Fix release name bug cncf/cnf-conformance#612

---

RELEASE.md

Documentation update for releases

---

sample-cnfs/sample-minimal-cnf/README.md
sample-cnfs/sample-minimal-cnf/cnf-conformance.yml
spec/fixtures/cnf-conformance-invalid-and-unmapped-keys.yml
spec/utils/cnf_manager_spec.cr
src/tasks/utils/config.cr
src/tasks/utils/types/cnf_conformance_yml_type.cr

[Feature] Minimal cnf-conformance.yml test
Release name (regression) now not required
white list name now not required
Refs: #608 #622 #612
**Issue**

[Feature] Minimal cnf-conformance.yml test

---

src/tasks/utils/helm.cr

Filter out resources that have the 'helm.sh/hook: test' annotation
Refs: #614 
**Issue**

When looking for resource yamls, reject resources that contain the 'helm.sh/hook: test' annotation

---

CONTRIBUTING.md

Contributing docs now have acceptance process #614

---

points-all.yml
points.yml
spec/utils/cnf_manager_spec.cr
spec/utils/utils_spec.cr
src/tasks/constants.cr
src/tasks/utils/points.cr
src/tasks/utils/utils.cr

[Feature] Implement scoring for SKIPPED tests
Refs: #603
**Issue**

[Feature] Implement scoring for SKIPPED tests

---

EXAMPLE-CNFS.md

Example images

---

src/cnf-conformance.cr

[Feature] Provide a list of CNF commands to run if no command is given. (CLI help getting started)
Refs: #297
**Issue**

[Feature] Provide a list of CNF commands to run if no command is given. (CLI help getting started)

---

spec/utils/cnf_manager_spec.cr
spec/utils/utils_spec.cr
spec/workload/configuration_lifecycle_spec.cr
spec/workload/installability_spec.cr
spec/workload/microservice_spec.cr
spec/workload/resilience/container_chaos_spec.cr
spec/workload/resilience/network_chaos_spec.cr
spec/workload/statelessness_spec.cr
src/tasks/litmus_setup.cr
src/tasks/platform/hardware_and_scheduling.cr
src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr
src/tasks/utils/embedded_file_manager.cr
src/tasks/workload/configuration_lifecycle.cr
src/tasks/workload/installability.cr
src/tasks/workload/microservice.cr
src/tasks/workload/resilience.cr
src/tasks/workload/scalability.cr
src/tasks/workload/security.cr
src/tasks/workload/statelessness.cr

#649  Description
Refs: #NNN
**Issue**

fix: FAILURE to FAILED in test results #649

---

.github/workflows/actions.yml

Test binary without source in the directory
Refs: #599 
**Issue**

test without source in directory refs #599

---

spec/utils/kubectl_client_spec.cr
spec/workload/microservice_spec.cr
src/tasks/dockerd_setup.cr
src/tasks/utils/kubectl_client.cr

[BUG] reasonable_image_size test should not fail if dockerd is not installed or if docker command fails 
Refs: #NNN
**Issue**

[BUG] reasonable_image_size test should not fail if dockerd is not installed or if docker command fails 

---

USAGE.md

Update the USAGE.md document with details on PASSED, SKIPPED and FAILED status for test output.
Refs: #645 
**Issue**

#645 update USAGE with pass, failed and skipped documentation

---

points-all.yml
scoring_config/points_v1.yml
spec/platform/resilience_spec.cr
src/tasks/litmus_setup.cr
src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr
src/tasks/utils/points.cr
src/tasks/workload/installability.cr

Add volume_hostpath_not_found to statelessness suite
The points are not calculated correctly, this PR adds extra debug to help diagnose and adds the required entry to points-all.yml
Refs: #652 
**Issue**
@wavell @taylor

Add extra debug to identify why points are not calculated correctly #652

---

points-all.yml
scoring_config/points_v1.yml
spec/platform/resilience_spec.cr
src/tasks/litmus_setup.cr
src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr
src/tasks/utils/points.cr
src/tasks/workload/installability.cr

Add volume_hostpath_not_found to statelessness suite
The points are not calculated correctly, this PR adds extra debug to help diagnose and adds the required entry to points-all.yml
Refs: #652 
**Issue**
@wavell @taylor

Add extra debug to identify why points are not calculated correctly

---

scoring_config/points_v1.yml
src/tasks/workload/configuration_lifecycle.cr
src/tasks/workload/microservice.cr
src/tasks/workload/resilience.cr

Debug to help identify issues with secrets_used
Refs: #667 
**Issue**

[BUG] secrets used #667

---

src/cnf-conformance.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/config.cr
src/tasks/utils/helm.cr

[BUG] Rollling Update ls root if cnf not installed 
Refs: #576 #620
**Issue**

[BUG] Rollling Update ls root if cnf not installed 

---

USAGE.md
src/tasks/workload/scalability.cr

when increase_decrease_capacity test fails, provide remediation suggestions

---

INSTALL.md
SOURCE_INSTALL.md
spec/cnf_conformance_all/cnf_conformance_container_chaos_spec.cr
spec/cnf_conformance_all/cnf_conformance_network_chaos_spec.cr
spec/prereqs_spec.cr
spec/utils/kubectl_client_spec.cr
spec/utils/system_information/wget_spec.cr
src/tasks/helmenv_setup.cr
src/tasks/prereqs.cr
src/tasks/utils/points.cr
src/tasks/workload/microservice.cr

[Feature] Remove wget as a cnf-conformance dependency
Refs: #679 #640
**Issue**

[Feature] Remove wget as a cnf-conformance dependency

---

spec/platform/cluster_api_spec.cr
spec/platform/platform_spec.cr
spec/prereqs_spec.cr
src/tasks/cluster_api_setup.cr
src/tasks/platform/observability.cr
src/tasks/prereqs.cr
src/tasks/sonobuoy_setup.cr
src/tasks/utils/points.cr
src/tasks/utils/release_manager.cr

[Feature] Remove curl as a cnf-conformance dependency. Switch to using a crystal library or curl instead
Refs: #689
**Issue**

[Feature] Remove curl as a cnf-conformance dependency. Switch to using a crystal library or curl instead

---

spec/utils/kubectl_client_spec.cr
spec/workload/configuration_lifecycle_spec.cr
src/tasks/utils/kubectl_client.cr

[Feature] Resource wait for uninstall
Refs: #660
**Issue**

[Feature] Resource wait for uninstall

---

src/tasks/utils/kubectl_client.cr
src/tasks/utils/utils.cr
src/tasks/workload/configuration_lifecycle.cr

Check kubectl version before failing immutable configmap test
Refs: #669
**Issue**
Please review: @taylor @wavell @denverwilliams

PR Test - Bug/#669 immutable configmap

---

src/tasks/utils/kubectl_client.cr
src/tasks/utils/utils.cr
src/tasks/workload/configuration_lifecycle.cr

Check kubectl version before failing immutable configmap test
Refs: #669
**Issue**
Please review: @taylor @wavell

Check kubectl version before failing immutable configmap test

---

src/tasks/utils/utils.cr
src/tasks/workload/configuration_lifecycle.cr

when converting a hash value to string try to convert integer to string if value isn't a string
Refs: #682 
**Issue**
Please review:
@taylor @wavell @lixuna @denverwilliams @williscool

PR GH Test - Bug/#682 version test tag

---

src/tasks/utils/utils.cr
src/tasks/workload/configuration_lifecycle.cr

when converting a hash value to string try to convert integer to string if value isn't a string
Refs: #682 
**Issue**
Please review:
@taylor @wavell @lixuna

Fix for rolling_version_change where the version is an integer

---

.github/workflows/actions.yml
CNF_CONFORMANCE_YML_USAGE.md
CONTRIBUTING.md
EXAMPLE-CNFS.md
FAQ.md
INSTALL.md
KIND-INSTALL.md
README-testsuite.md
RELEASE.md
SOURCE_INSTALL.md
TEST-CATEGORIES.md
USAGE.md
example-cnfs/coredns/README.md
example-cnfs/envoy/README.md
example-cnfs/linkerd2/README.md
example-cnfs/nsm/README.md
example-cnfs/pantheon-nsm-nat/README.md
example-cnfs/pantheon-nsm-nat/nat-cnf/README.md
spec/utils/release_manager_spec.cr
src/cnf-conformance.cr
src/tasks/utils/points.cr
src/tasks/utils/release_manager.cr
src/tasks/workload/scalability.cr

[Feature] Rename master branch to main for GitHub repo
Refs: #626
**Issue**

[Feature] Rename master branch to main for GitHub repo

---

points.yml
spec/utils/cnf_manager_spec.cr
src/tasks/utils/points.cr

Update tests to use the correct tags
Refs: cncf/cnf-conformance#701
**Issue**

Update tests to use the correct tags

---

.gitignore
src/tasks/chaos_mesh_setup.cr
src/tasks/utils/kubectl_client.cr
src/tasks/workload/resilience.cr

[BUG] Erroneous output on LOG_LEVEL=error that should be suppressed
Refs: #685
**Issue**

[BUG] Erroneous output on LOG_LEVEL=error that should be suppressed

---

src/tasks/utils/helm.cr
src/tasks/utils/utils.cr
src/tasks/workload/configuration_lifecycle.cr

[BUG] debug output is present in LOG_LEVEL=error output
[BUG] debug output is present in LOG_LEVEL=error output
Refs: #688
**Issue**

[BUG] debug output is present in LOG_LEVEL=error output

---

sample-cnfs/sample_coredns/cnf-conformance.yml
src/tasks/litmus_setup.cr
src/tasks/workload/resilience.cr

Running CNF test displays a failed test but then PASSED on next line output afterwards
Refs: #684
**Issue**

[BUG] Running CNF test displays a failed test but then PASSED on next line output afterwards

---

README-testsuite.md

Removing usage of wget #681 #679 #388

switch from wget to curl

---

src/tasks/workload/configuration_lifecycle.cr

address now spelled correctly
Refs: #717
**Issue**

address now spelled correctly

---

README.md

Re-ordering things where quick start is sooner in the README.

moving quick start to top

---

CNF_CONFORMANCE_YML_USAGE.md
CONTRIBUTING.md
FAQ.md
INSTALL.md
README.md
SOURCE_INSTALL.md
USAGE.md

refs #555
- Remove `conformance` from test suite name
- update urls for slack channels
Refs: #555
**Issue**

renaming CNF Test Suite

---

curl_install.sh
spec/curl_install_spec.cr

Update curl install to fetch the test-suite from the new repo.
Refs: cncf/cnf-testsuite#728
**Issue**

Update curl install to fetch the test-suite from the new repo 

---

src/tasks/workload/scalability.cr

fix spelling
Refs: #632 
**Issue**

fix spelling errors in increase_decrease_capacity

---

USAGE.md

[Feature] Update USAGE guide to list platform tests by test categories
Refs: #729
**Issue**

[Feature] Update USAGE guide to list platform tests by test categories

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

for bugs and features.
Refs: #703
**Issue**

add How will this be tested? aka Acceptance Criteria to pull templates

---

embedded_files/points.yml
spec/utils/cnf_manager_spec.cr
src/tasks/constants.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/points.cr
src/tasks/utils/utils.cr

[BUG] Address whether SKIPPED tests (Soft failures & Crystal failures) should be inclusive or exclusive of the Total Score. (Handling of N/A tests)
Refs: #707
**Issue**

[BUG] Address whether SKIPPED tests (Soft failures & Crystal failures) should be inclusive or exclusive of the Total Score. (Handling of N/A tests)

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/new-example-cnf.md
.github/ISSUE_TEMPLATE/new-platform-test.md
.github/ISSUE_TEMPLATE/new-workload-test.md
.github/ISSUE_TEMPLATE/proof-of-concept-test.md
CNF_CONFORMANCE_YML_USAGE.md
CONTRIBUTING.md
EXAMPLE-CNFS.md
FAQ.md
KIND-INSTALL.md
README.md
RELEASE.md
ROADMAP-testsuite.md
SOURCE_INSTALL.md
TEST-CATEGORIES.md
USAGE.md
example-cnfs/coredns/README.md
example-cnfs/envoy/README.md
example-cnfs/linkerd2/README.md
example-cnfs/nsm/README.md
example-cnfs/pantheon-nsm-nat/README.md
example-cnfs/pantheon-nsm-nat/nat-cnf/README.md
sample-cnfs/sample_coredns_protected/README.md
src/cnf-testsuite.cr
src/tasks/workload/configuration_lifecycle.cr
tools/ephemeral_env/README.md

This Pull Request solves the links issues. All references of <code>https://github.com/cncf/cnf-conformance</code> are replaced to <code>https://github.com/cncf/cnf-conformance</code>
In a file [USAGE.md], all references are changed to relative links
Refs: #724 
**Issue**

Fixed links🔗

---

CNF_CONFORMANCE_YML_USAGE.md
SOURCE_INSTALL.md
TEST-CATEGORIES.md
example-cnfs/coredns/README.md
example-cnfs/pantheon-nsm-nat/nat-cnf/README.md

changing more docs to use relative links so they are good with different branches
Refs: #742 and PR #749
**Issue**

more relative link updates

---

CNF_CONFORMANCE_YML_USAGE.md
CONTRIBUTING.md
FAQ.md
INSTALL.md
README.md
SOURCE_INSTALL.md
USAGE.md
embedded_files/POINTS.md
example-cnfs/coredns/README.md
example-cnfs/envoy/README.md
example-cnfs/ip-forwarder/README.md
example-cnfs/linkerd2/README.md
example-cnfs/nsm/README.md
example-cnfs/pantheon-nsm-nat/README.md
example-cnfs/vpp-3c2n-csp-use-case/README.md
tools/curl_install_tester_docker_setup/Dockerfile
tools/curl_install_tester_docker_setup/README.md

More updates for the name change of the repo #555 from cnf-conformance to cnf-testsuite.
This does not update references to the `cnf-conformance.yml` mentions since code continues to use those YML files to operate. 
Refs: #724 ; #555
**Issue**

Feature/#724 more link fixes and updates of cnf-conformance to cnf-testsuite where applicable

---

spec/setup_spec.cr
src/tasks/cnf_setup.cr
src/tasks/constants.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/generate_config.cr
src/tasks/utils/helm.cr
src/tasks/utils/kubectl_client.cr
src/tasks/utils/utils.cr

Add support for generating the cnf-conformace.yml 
Refs: cncf/cnf-testsuite#752
**Issue**

Add support for generating the cnf-conformace.yml 

---

src/tasks/workload/installability.cr

added helm emojis to helm tests

---

src/tasks/workload/configuration_lifecycle.cr
src/tasks/workload/installability.cr

Adding helm unicode ⎈ for helm test emoji
ref: 
- #334 
- #197 
**Issue**

Adding helm unicode ⎈ for helm tests

---

CNF_TESTSUITE_YML_USAGE.md

Update Testsuite usage doc to use correct naming

---

.github/ISSUE_TEMPLATE/bug-report.md

Fix typo for unncesasray to unnecessary that was somehow overlooked.
Refs: #703
**Issue**

fix unncesasray typo #703

---

spec/setup_spec.cr
spec/utils/airgap_spec.cr
src/tasks/chaos_mesh_setup.cr
src/tasks/helmenv_setup.cr
src/tasks/utils/airgap.cr

#763 airgap now extracts to the /tmp directory

---

src/tasks/setup.cr

offline now has an alias as input-file
Refs: #763
**Issue**

#763 offline now has an alias as input-file

---

src/tasks/utils/cnf_manager.cr

Fix bug with setup removing non-existent file.
Refs: cncf/cnf-testsuite#776
**Issue**

Fix bug with setup removing non-existent file.

---

.github/workflows/actions.yml
.gitignore
spec/utils/airgap_spec.cr
spec/utils/bootstrap_k8s_spec.cr
spec/utils/kubectl_client_spec.cr
spec/utils/utils_spec.cr
src/tasks/constants.cr
src/tasks/utils/airgap.cr
src/tasks/utils/bootstrap_k8s.cr
src/tasks/utils/kubectl_client.cr
tools/bootstrap-cri-tools.sh
tools/cri-tools/Dockerfile
tools/publish_tarball.sh

Add publish tarball command for offline cluster support.
Refs: cncf/cnf-testsuite#780
**Issue**

Add publish tarball command for offline cluster support.

---

spec/utils/airgap_spec.cr
spec/utils/kubectl_client_spec.cr
src/tasks/utils/airgap.cr
src/tasks/utils/kubectl_client.cr

Add support for bootstrapping using the tar binary from the host.
Refs: cncf/cnf-testsuite/#785
**Issue**

Add support for bootstrapping using the tar binary from the host.

---

.gitignore
config.yml
spec/setup_spec.cr
spec/utils/airgap_spec.cr
src/tasks/utils/airgap.cr
src/tasks/utils/docker_client.cr
src/tasks/utils/kubectl_client.cr
src/tasks/utils/tar.cr

[Feature] Use the air-gap tool to install all images that we maintain or that are maintained upstream
Refs: #786
**Issue**

[Feature] Use the air-gap tool to install all images that we maintain or that are maintained upstream

---

.github/workflows/actions.yml
.github/workflows/check_litmus.sh
spec/fixtures/litmus-operator-v1.13.2.yaml
spec/setup_spec.cr
spec/utils/airgap_spec.cr
spec/utils/utils_spec.cr
src/tasks/constants.cr
src/tasks/litmus_setup.cr
src/tasks/prereqs.cr
src/tasks/sonobuoy_setup.cr
src/tasks/utils/airgap.cr
src/tasks/utils/tar.cr
tools/airgapped_kind/Dockerfile
tools/airgapped_kind/entrypoint-wrapper.sh
tools/airgapped_kind/kind-config.yaml
tools/airgapped_kind/kind_node/Dockerfile
tools/airgapped_kind/kind_node/entrypoint-wrapper.sh

[Feature] Create an environment for the automated test of #585 
Refs: #585
**Issue**

[Feature] Create an environment for the automated test of #585 

---

FAQ.md
SOURCE_INSTALL.md

MacOS source install verification and proof of concept. 
Refs: #647 
**Issue**

doc updates to reference mac os x support for source installs #647

---

spec/setup_spec.cr
src/tasks/utils/airgap.cr

CNF setup should install all images referenced in the cnf-testsuite.yml
Refs: #815
**Issue**

CNF setup should install all images referenced in the cnf-testsuite.yml

---

CONTRIBUTING.md

- CNCF Slack (request invite to join [slack.cncf.io](slack.cncf.io))
adding link to join slack [slack.cncf.io](slack.cncf.io))
Refs: N/A
**Issue**

added slack.cncf.io to contributing

---

sample-cnfs/k8s-non-helm-no-image-policy/README.md
sample-cnfs/k8s-non-helm-no-image-policy/cnf-testsuite.yml
sample-cnfs/k8s-non-helm-no-image-policy/manifests/manifest.yml
sample-cnfs/k8s-non-helm-no-image-policy/manifests/pod.yml
sample-cnfs/k8s-non-helm/cnf-testsuite.yml
src/tasks/cnf_setup.cr
src/tasks/utils/airgap.cr
src/tasks/utils/airgap_utils.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/kubectl_client.cr

Fix bug causing cnf_setup to hang on image pull when installing cnfs from a manifest directory when in offline mode.
Refs: cncf/cnf-testsuite#808
**Issue**

Fix bug causing image pull to fail in offline mode

---

.github/workflows/actions.yml
spec/workload/registry_spec.cr
tools/github-runner/cleanup_runners.sh
tools/github-runner/create_runners.sh

Fix bug with docker pulls being rate limited.
Refs: #NNN
**Issue**

Fix bug with docker pulls being rate limited & excessive disk usage.

---

INSTALL.md

Created link from INSTALL.md to the new AIRGAP.md documentation
Refs: #825
**Issue**

#825 added link from INSTALL.md to new AIRGAP.md

---

.github/workflows/actions.yml
tools/github-runner/create_runners.sh

Refs: cncf/cnf-testsuite#841
**Issue**

Fix Docker Rate-limiting issue causing CI Jobs to fail intermittently.

---

src/tasks/workload/microservice.cr

#835 reasonable startup timeout now 30s in test mode

---

README.md

add https://calendly.com/cnftestsuite to README
Refs: #852 
**Issue**

add calendly

---

src/tasks/workload/resilience.cr

Fix bug causing network latency test to return results multiple times
Refs: cncf/cnf-testsuite#857
**Issue**

Fix bug causing network latency test to return results multiple times

---

README.md

Add presentation recordings to readme
Refs: #848 
**Issue**

add recordings to readme

---

ROADMAP.md

add links to good first issue label and air gapped label
Refs: #863 
**Issue**

add links to issue labels

---

ADOPTERS.md

add adopters file to repo
Refs: #851
**Issue**

#851 add adopters file to repo

---

ADOPTERS.md

Adding MATRIXX and our use case to the adopters list.

Adding MATRIXX to the Adopters list

---

.gitignore
USAGE.md
embedded_files/points.yml
sample-cnfs/k8s-multiple-processes/README.md
sample-cnfs/k8s-multiple-processes/chart/Chart.yaml
sample-cnfs/k8s-multiple-processes/chart/templates/manifest.yml
sample-cnfs/k8s-multiple-processes/chart/templates/pod.yml
sample-cnfs/k8s-multiple-processes/chart/values.yaml
sample-cnfs/k8s-multiple-processes/cnf-testsuite.yml
spec/utils/cnf_manager_spec.cr
spec/utils/kernel_introspection_spec.cr
spec/utils/kubectl_client_spec.cr
spec/workload/microservice_spec.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/kernel_instrospection.cr
src/tasks/utils/kubectl_client.cr
src/tasks/workload/microservice.cr
src/tasks/workload/resilience.cr

Microservice test: What is the total number of processes in a container?
Refs: #865 #156
**Issue**

Microservice test: What is the total number of processes in a container?

---

.gitignore
spec/workload/microservice_spec.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/docker_client.cr
src/tasks/utils/image_prepull.cr

pre-cache cnf setup image before calculating startup time using cri-tools
Refs: #908 
**Issue**

[Feature] #908 reasonable time

---

shard.lock
shard.yml
spec/platform/observability_spec.cr
spec/workload/installability_spec.cr
src/tasks/chaos_mesh_setup.cr
src/tasks/constants.cr
src/tasks/helmenv_setup.cr
src/tasks/platform/resilience.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/config.cr
src/tasks/utils/generate_config.cr
src/tasks/utils/points.cr
src/tasks/utils/system_information/helm.cr
src/tasks/utils/task.cr
src/tasks/workload/configuration_lifecycle.cr
src/tasks/workload/installability.cr
src/tasks/workload/microservice.cr
utils/helm/binary_reference.cr
utils/helm/helm.cr
utils/helm/shard.yml

helm module now separated
Refs: #916
**Issue**

helm module now separated

---

MAINTAINERS.md

- It has been a great experience to learn CNF and contribute to the resiliency branch of it. Thanks to the community for the support. This PR is for adding Udit to the contributor list.
Refs: #NNN
**Issue**

Add Udit to the contributor list

---

src/tasks/chaos_mesh_setup.cr
src/tasks/cleanup.cr
src/tasks/cnf_setup.cr
src/tasks/dockerd_setup.cr
src/tasks/helmenv_setup.cr
src/tasks/litmus_cleanup.cr
src/tasks/platform/resilience.cr
src/tasks/sonobuoy_setup.cr
src/tasks/utils/airgap.cr
src/tasks/utils/find.cr
src/tasks/utils/system_information/curl.cr
src/tasks/utils/system_information/git.cr
src/tasks/utils/system_information/helm.cr
utils/find/find.cr

* Replace some backtick commands with `Process.run`
* Replace deletion lines with `FileUtils.rm_rf`
* Use `KubectlClient` helpers where possible
* Remove use of `LOGGING` and `VERBOSE_LOGGING`
Refs: #307
**Issue**

[Bug/307] Run shell commands with Process.run (Part-1)

---

INSTALL.md
SOURCE_INSTALL.md
tools/ephemeral_env/Dockerfile

- Documentation updates for Crystal-Lang version 1.0.0 updates.
- Added missing steps (shards install) for the source-install using the crystal 1.0.0 image from Docker Hub.
Refs: #912 
**Issue**

Documentation crystal v1.0.0 updates #912

---

.github/workflows/actions.yml
src/tasks/utils/cnf_manager.cr
src/tasks/workload/resilience.cr
tools/github-runner/cleanup_runners.sh
tools/github-runner/create_runners.sh
utils/airgap/airgap.cr

Fix bugs causing Litmus Chaos Spec tests to fail.
Refs: cncf/cnf-testsuite/issues/918
**Issue**

Fix bugs causing Litmus Chaos Spec tests to fail 

---

src/tasks/workload/scalability.cr

Update the remediation output for `increase_decrease_capacity` test.
Refs: #907 
**Issue**

[Enhancement] #907 improve remediation output

---

embedded_files/falco_rule.yaml
src/tasks/utils/falco.cr

Fix bugs with the Falco non_root_user test. 
Refs: cncf/cnf-testsuite#953
**Issue**

Fix bugs with the Falco non_root_user test.  #953

---

.github/workflows/actions.yml
spec/workload/microservice_spec.cr
tools/github-runner/create_runners.sh

Fix docker-ratelimt issue when doing authenticated pulls.
Refs: cncf/cnf-testsuite#927
**Issue**

Bug/docker ratelimit#927

---

USAGE.md

Documentation change for USAGE.md to add description for the `increase_decrease_capacity` test.
Refs: https://github.com/cncf/cnf-testsuite/issues/939
**Issue**

Documentation #939 increase decrease description

---

.gitignore
USAGE.md
embedded_files/constraint_template.yml
embedded_files/enforce-image-tag.yml
spec/workload/configuration_lifecycle_spec.cr
src/tasks/constants.cr
src/tasks/falco_setup.cr
src/tasks/opa_setup.cr
src/tasks/setup.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/embedded_file_manager.cr
src/tasks/utils/opa.cr
src/tasks/workload/configuration_lifecycle.cr
utils/kubectl_client/kubectl_client.cr

Configuration and Lifecycle test: does the image use a versioned tag?
Refs: #955
**Issue**

Configuration and Lifecycle test: does the image use a versioned tag?

---

.github/workflows/actions.yml
src/tasks/falco_setup.cr

Fix bug causing github-runners to run out of disk space.
Refs: https://github.com/cncf/cnf-testsuite/issues/997
**Issue**

Fix bug causing github-runners to run out of disk space. #997

---

shard.lock
shard.yml
src/tasks/litmus_setup.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/generate_config.cr
src/tasks/workload/configuration_lifecycle.cr
src/tasks/workload/resilience.cr
src/templates/chaos_templates/container_kill.yml.ecr
src/templates/chaos_templates/cpu.yml.ecr
src/templates/chaos_templates/disk_fill.yml.ecr
src/templates/chaos_templates/network.yml.ecr
src/templates/chaos_templates/node_drain.yml.ecr
src/templates/chaos_templates/pod_delete.yml.ecr
src/templates/chaos_templates/pod_io_stress.yml.ecr
src/templates/chaos_templates/pod_memory_hog.yml.ecr
src/templates/chaos_templates/pod_network_corruption.yml.ecr
src/templates/chaos_templates/pod_network_duplication.yml.ecr
src/templates/chaos_templates/pod_network_latency.yml.ecr
src/templates/configmap_template.yml.ecr
src/templates/immutable_configmap.yml.ecr
src/templates/testsuite_template.yml.ecr
utils/airgap/airgap.cr
utils/airgap/cri-tools-template.yml.ecr
utils/airgap/shard.yml

* Use ECR for templating instead of a third-party library
* Remove the dependency on the third-party library
This change is to help make progress on #867.
Refs: #1093 
**Issue**

[1093] Use ECR for templating instead instead of a third-party library

---

USAGE.md

Added description and remediation details for USAGE doc. Moved the test from 'To Do's' drop down.
Refs: #1098 
**Issue**

DOC/#1098 log output USAGE details add

---

USAGE.md

Added missing description and remediation details for kubescape security tests.
Refs: #1103 , #1104 , #1052 , #1053 , #1056 , #1055 , #1058 , #1059 , #1061 , #1054, #1062
**Issue**

[DOC] USAGE description and remediation detail updates

---

USAGE.md

Added missing rolling_version_change, cni_compatible descriptions, increase and decrease individual tests added. Fixed additional info for k8s as details drop down.
Refs: #1085 #1108 #1067
**Issue**

Updates to USAGE #1085 #1108 #1067

---

CONTRIBUTING.md

meeting time is 15:15 UTC during Standard Time, it was 14:15 UTC during Daylight Savings Time
Refs: #945  
**Issue**

update meeting time to 15:15 UTC

---

src/tasks/utils/fluentd.cr
src/tasks/utils/jaeger.cr
src/tasks/workload/observability.cr

tracing now skips if jaeger not installed
Refs: #1146
**Issue**

#1146 tracing now skips if jaeger not installed

---

.github/workflows/actions.yml
tools/github-runner/cleanup_runners.sh

Enable Mirror for all Docker Pulls
Refs: #1162
**Issue**

Enable Mirror for all Docker Pulls 

---

README.md
TEST-CATEGORIES.md
USAGE.md

Category refactor doc updates for TEST-CATEGORIES, README and USAGE
Refs: #1088 #1133 #1134 #1137
**Issue**

Documentation/#1088 category refactor for USAGE, README and TEST-CATEGORIES

---

.github/workflows/actions.yml
sample-cnfs/sample_local_registry_org_image/chart/values.yaml
spec/workload/configuration_spec.cr
spec/workload/registry_spec.cr
src/tasks/workload/compatibility.cr
src/tasks/workload/microservice.cr
tools/crystal-alpine.dockerfile
utils/kubectl_client/kubectl_client.cr

* Update Crystal version in crystal-alpine dockerfile.
* Update Crystal image in GitHub Actions yaml.
* Remove `wait_count` from `cnf_setup` to allow rolling_update test to pass.
* Replace `KubectlClient.exec("docker -ti ...")` with `KubectlClient.exec("docker -t ...")`. Removing the `i` flag resolves warnings about tty.
* Some tests in the tag group require one of the two image repositories `coredns` and `coredns/coredns`. To resolve this
* Change the image repository org name in the sample CNF `sample_local_registry_org` to `coredns-sample-org`.
* Also update the `before_all` in `registry_spec.cr` to tag and push images to this repository too.
* Add an argument to `KubectlClient.exec` to force stdout to be printed at `LOG_LEVEL=info` if required for certain commands. Enabled it for the …

[867] Crystal upgrade to 1.2.2 and fix for private_registry_image test failures [1180]

---

USAGE.md
embedded_files/points.yml
spec/utils/cnf_manager_spec.cr
src/tasks/utils/cluster_utils.cr
tools/cluster-tools/manifest.yml

#1024 points and documentation
Refs: #1024
**Issue**

#1024 points and documentation

---

RATIONALE.md
src/tasks/workload/compatibility.cr

#1208 rationale for tests

---

USAGE.md
embedded_files/points.yml
src/tasks/workload/reliability.cr
src/tasks/workload/state.cr

[Workload] State test: Check if the CNF still operates after being re-scheduled to another node.
Refs: #1023
**Issue**

[Workload] State test: Check if the CNF still operates after being re-scheduled to another node.

---

RATIONALE.md

removed #1165

---

src/tasks/workload/state.cr

Updated check to use the found property
Refs: #1213 
- [ X] Ran database_persistence with and without mysql
- [ X] Bug fix (non-breaking change which fixes an issue)
- [X ] No updates required.

Updating database check in state

---

USAGE.md

Remove category headers for Platform tests in USAGE.md to simplify the document layout.
Refs: #1179 
**Issue**

Updates to remove categories from platform test section #1179

---

USAGE.md
src/tasks/workload/configuration.cr
utils/kubectl_client/kubectl_client.cr

Adding require_labels test which checks for any containers that do not have "app.kubernetes.io/name" label and reports accordingly
Refs: #NNN
**Issue**

updating code and documentation for require_labels test using kyverno

---

USAGE.md
src/tasks/workload/configuration.cr
src/tasks/workload/security.cr

Add disallow_sock_mounts Kyverno test.
Refs: #NNN
**Issue**

Add disallow_sock_mounts Kyverno test.

---

USAGE.md
src/tasks/workload/security.cr
utils/kubectl_client/kubectl_client.cr

Test to check if containers use container socket mounts
Refs: #NNN
**Issue**

updated code and documentation for disallow_container_sock_mounts test

---

USAGE.md
src/tasks/workload/security.cr

Add Kyverno disallow_helm_tiller test.
Refs: #NNN
**Issue**

Add Kyverno disallow_helm_tiller test

---

USAGE.md
src/tasks/workload/security.cr
utils/kubectl_client/kubectl_client.cr

Adding test to integrate kyverno to CNF testsuite. The test checks if there are any containers that use tiller/helm v2 images and reports accordingly
Refs: #NNN
**Issue**

updated code and documentation for disallow_helm_tiller test using kyverno

---

USAGE.md
src/tasks/workload/security.cr

Add Kyverno test for restrict_external_ips
Refs: #NNN
**Issue**

Add Kyverno test for restrict_external_ips

---

USAGE.md
src/tasks/workload/configuration.cr
src/tasks/workload/security.cr
utils/kubectl_client/kubectl_client.cr

Adding test to integrate kyverno to CNF testsuite. The test checks if there are any external IP's in the service configuration and reports accordingly
Refs: #NNN
**Issue**

Restrict external ips

---

src/tasks/workload/configuration.cr

#1230 immutable configmap now does not check nul env

---

RATIONALE.md

Additions to rational doc.
Refs: #1208 
**Issue**

Helm and Observability rationale

---

RATIONALE.md

Added links to USAGE doc and moved alpha_k8s_api to compatibility as also it's POC test, might need to remove.
Refs: #1208 
**Issue**

Updated to RATIONALE to include links to USAGE for each test

---

tools/github-runner/Dockerfile
tools/github-runner/cleanup_runners.sh
tools/github-runner/create_runners.sh
tools/github-runner/delete-runners-on-github.sh

In the `create_runners.sh` script, use the `docker rm` command to force-delete each container before creating a new github runner. This would prevent container name clashes when recreating containers.
Wrote a script to avoid clicking on GitHub Actions to delete runners.
**To use the script,**
1. Please install `jq` from the package/app repository of your OS.
2. Set the `GH_USER` env var to the GitHub Username.
3. Create a GitHub Personal Access Token with the `admin:org` write permission.
4. Set the `GH_TOKEN` env var to the GitHub Personal Access Token.
Run the command below to cleanup runners on the GitHub Actions page.
```
GH_USER=TODO GH_TOKEN=TODO bash tools/github-runner/delete-runners-on-github.sh
```
> **KNOWN LIMITATION**: For now, this script only deletes the first 100 GitHub …

[1261,1262,1263] Changes to resolve issues with GitHub Actions Runners

---

README.md

- Meetings every Thursday at 14:15 - 15:00 UTC (during Daylight Savings Time)
Refs: N/A
**Issue**

update contributor meeting time to 14:15 UTC

---

spec/cnf_testsuite_all/cnf_testsuite_spec.cr
spec/utils/utils_spec.cr
src/cnf-testsuite.cr
src/tasks/utils/task.cr
src/tasks/workload/mock_task.cr

Enable Critical Error Codes
Refs: #650
**Issue**

Enable Critical Error Codes

---

tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh

Need new github runner image for action jobs to pick up tests.
Refs: #1318 
**Issue**

#1318 new image 2.289.2 for github runners

---

docs/LIST_OF_TESTS.md

add links to rollback/rolling tests
Ref: #1306 
**Issue**

update 0.27.0 list of tests

---

RATIONALE.md
USAGE.md

refs #1177
fix typo for OpenMetrics
Refs: #1177 
**Issue**

fix typo for OpenMetrics

---

src/tasks/workload/compatibility.cr
src/tasks/workload/configuration.cr
src/tasks/workload/microservice.cr
src/tasks/workload/observability.cr
src/tasks/workload/security.cr

Updates all skipped tests with proper emoji and then fixes the shared_database desc in the code.
Refs: #1291 #1298 
**Issue**

[BUG] [#1291 & #1298] skipped tests and shared database description

---

USAGE.md

Duplicate entries found for latest_tag and default_namespace entries and details.
Refs: #1347 
**Issue**

Removed duplicate test entries #1347

---

sample-cnfs/sample_privileged_cnf/chart/templates/deployment.yaml
spec/utils/utils_spec.cr
src/tasks/utils/cnf_manager.cr

Fix bug with spec test: spec/utils/utils_spec.cr:171 
Refs: #1275 
**Issue**

Fix bug with spec test: spec/utils/utils_spec.cr:171 #1275

---

src/tasks/cluster_api_setup.cr
tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh
utils/kubectl_client/kubectl_client.cr

Fix bugs with ClusterAPI test when running against a Kubespray Cluster. 
Refs: cncf/cnf-testsuite#1275
**Issue**

Fix bugs with ClusterAPI test when running against a Kubespray Cluster. 

---

USAGE.md

Test is not destructive; removed the word to avoid confusion from end users.
Refs: #1332 
**Issue**

Removed destructive from reasonable startup time USAGE #1332

---

src/tasks/workload/reliability.cr
src/tasks/workload/security.cr
src/tasks/workload/state.cr

Caught more SKIPPED tests that got added with wrong emoji. This updates so all console output is in consistent and in uniform with the other SKIPPED tests output.
Refs: #1291 
**Issue**

BUG #1291 Updated SKIPPED tags with proper emoji

---

embedded_files/points.yml
spec/utils/cnf_manager_spec.cr
src/tasks/cert/cert.cr
src/tasks/workload/cert_compatibility.cr
src/tasks/workload/cert_configuration.cr
src/tasks/workload/cert_microservice.cr
src/tasks/workload/cert_observability.cr
src/tasks/workload/cert_resilience.cr
src/tasks/workload/cert_security.cr
src/tasks/workload/cert_state.cr

[Feature] Add command to run tests that will be included in CNF Certification v1.0.0
Refs: #1251
**Issue**

[Feature] Add command to run tests that will be included in CNF Certification v1.0.0

---

spec/workload/security_spec.cr
src/tasks/utils/points.cr
src/tasks/workload/security.cr

[Feature] update Command Line output for cert command
[Feature] update Command Line output for cert command
Refs: #1408
**Issue**

[Feature] update Command Line output for cert command

---

spec/utils/system_information/docker_spec.cr
src/tasks/utils/system_information/docker.cr
src/tasks/workload/compatibility.cr

[BUG] cni_compatible FAILS when it should SKIP the test when Docker not found or installed on client
Refs: #1420
**Issue**

[BUG] cni_compatible FAILS when it should SKIP the test when Docker not found or installed on client

---

INSTALL.md

#1420 #1366 documentation update
Refs: #1366
**Issue**

#1420 #1366 documentation update

---

src/tasks/cert/cert.cr

#1251 uncommented full cert command

---

INSTALL.md

Making it more apparent that containerd is required
ref https://github.com/cncf/cnf-testsuite/issues/1366

Updating prereq for container runtime

---

CNF_TESTSUITE_YML_USAGE.md
example-cnfs/coredns/cnf-testsuite.yml
spec/cnf_testsuite_all/cnf_testsuite_config_lifecycle_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_microservice_spec.cr
spec/cnf_testsuite_all/cnf_testsuite_spec.cr
spec/setup_spec.cr
src/tasks/utils/generate_config.cr

Update Testsuite Usage Document
Refs: https://github.com/cncf/cnf-testsuite/issues/1432
**Issue**

Update Testsuite Usage Document

---

src/tasks/workload/compatibility.cr

Fix to console output for description for rollback failure. 
Refs: #1446 
**Issue**

Bug Fix - #1446 updated rolling update to be rollback in console description

---

src/tasks/utils/cnf_manager.cr

* `CNFManager.sample_setup` helper to use the `cnf_installation_method` helper to detect installation mechanism.
* `CNFManager.sample_cleanup` helper to use the `cnf_installation_method` helper to detect installation mechanism.
* Updated `CNFManager.cnf_workload_resources` to use default namespace based on the installation method.
* Also updated `CNFManager.sample_cleanup` by organizing the cleanup methods into a `case` block
```
./cnf-testsuite -l info cnf_setup cnf-config=./sample-cnfs/sample-coredns-cnf
./cnf-testsuite -l info cnf_cleanup cnf-config=./sample-cnfs/sample-coredns-cnf
```
> Edit the CNF config for `sample-coredns-cnf` and remove the `helm_install_namespace` option
```
./cnf-testsuite -l info cnf_setup cnf-config=./sample-cnfs/sample-coredns-cnf
./cnf-testsuite -l info …
```

[1389] helm_install_namespace option should only be read for helm-based CNFs

---

embedded_files/points.yml

Fixes 5 tests mis-tagged.
Refs: #1395
**Issue**

[BUG] #1395 fixed missed labeled tags for tests for cert v1

---

src/tasks/utils/points.cr
src/tasks/utils/utils.cr

#1448 duplicate code removed

---

USAGE.md

Update Documentation for hardcoded_ip_addresses_in_k8s_runtime_configuration & hostport_not_used tests.
Refs: #1193 #1192
**Issue**

Documentation Updates #1193 #1192

---

USAGE.md

fix typos in details
Refs: #1193 
**Issue**

[1193] fix typos in details

---

embedded_files/points.yml
spec/utils/cnf_manager_spec.cr
src/tasks/utils/points.cr

[BUG] maximum points for cert seem incorrect in test results file from v0.29.0 

---

USAGE.md
docs/LIST_OF_TESTS.md

Refactor USAGE.md & LIST_OF_TESTS.md for Compatibility
Refs:  #1370 #1371 #1372
**Issue**

Refactor USAGE.md & LIST_OF_TESTS.md for Compatibility #1370 #1371 #1372

---

src/tasks/utils/utils.cr

#1437 results file now includs passing and essential passing count

---

tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh

github runners needed updates; would find "waiting on available runner" errors when running actions jobs.
Refs: #N/A
**Issue**

New github runner image 2.293.0 updates

---

src/tasks/workload/configuration.cr

Update the latest tag test not to catch failures outside of the CNF's resources.
Issue: #1507
Testing:
Install a container on the cluster using the latest tag(outside of the CNF being tested):
```helm install --set image.tag=latest corednstag coredns/coredns```
Results on main branch: (Failing)
`./cnf-testsuite -l info cnf_cleanup cnf-config=./sample-cnfs/sample_coredns`
`./cnf-testsuite -l info latest_tag`
```
[pair@dev1:~/src/denver/cnf-testsuite] 
☺ ➔  ./cnf-testsuite -l info latest_tag                                                                                         
I, [2022-06-21 22:24:25 +00:00 #875551]  INFO -- cnf-testsuite-verbose: latest_tag
I, [2022-06-21 22:24:25 +00:00 #875551]  INFO -- cnf-testsuite: kyverno_policy_path command: ls …
```

Latest Tag Bug Fix #1507

---

src/tasks/workload/security.cr

> Issue refs: #1508
* Update `selinux_options` to use Kyverno test results parser.
* This new test results parser only considers failures for resources that belong to the CNF under test.
```
./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_latest_tag
./cnf-testsuite selinux_options
./cnf-testsuite cnf_cleanup cnf-config=./sample-cnfs/sample_latest_tag
```
```
./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_nonroot
./cnf-testsuite selinux_options
./cnf-testsuite cnf_cleanup cnf-config=./sample-cnfs/sample_nonroot
```
```
./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_valid_selinux_options
./cnf-testsuite selinux_options
./cnf-testsuite cnf_cleanup cnf-config=./sample-cnfs/sample_valid_selinux_options
```
**Issue**

[#1508] Update `selinux_options` to use Kyverno test parser

---

tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh

> **This PR is for #1544**
Update runner base image and image name in runner setup script
**Issue**

Update runner base image and image name in runner setup script

---

RATIONALE.md
USAGE.md
docs/LIST_OF_TESTS.md

Updates docs to reflect fluentbit support
Refs: #1522
**Issue**

Update docs to reflect FluentBit support in routed_logs test

---

docs/LIST_OF_TESTS.md

Signed-off-by: agentpoyo <drew.bentley@gmail.com>
Fix spelling of Rational to Rationale 
Refs: #1565 
**Issue**

Fix rational to rationale in all links to RATIONALE.md

---

.github/workflows/actions.yml
spec/platform/cluster_api_spec.cr
src/tasks/cluster_api_setup.cr
tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh

Fix bugs with the cluster api spec test.
Refs: cncf/cnf-testsuite#1575
**Issue**

Fix bugs with the cluster api spec test #1575

---

src/tasks/helmenv_setup.cr

Signed-off-by: denverwilliams <denver@debian.nz>
Bump helm version to v3.8.2 
Refs: cncf/cnf-testsuite#1391
**Issue**

Bump helm version to v3.8.2 

---

spec/utils/kernel_introspection_spec.cr
src/tasks/utils/cloud_native_introspection.cr
src/tasks/utils/kernel_instrospection.cr
src/tasks/workload/microservice.cr

Add Support for getting workloads by processes.
Refs: #1580
**Issue**

Add Support for getting workloads by processes #1580

---

src/tasks/utils/kernel_instrospection.cr
src/tasks/workload/microservice.cr
src/tasks/workload/observability.cr
utils/kubectl_client/kubectl_client.cr

This PR updates the prometheus_traffic test to use new process search.
Refs: #1581 1567
**Issue**

Update prometheus_traffic test to use new process search #1581 #1567

---

INSTALL.md
KIND-INSTALL.md
SOURCE_INSTALL.md

Signed-off-by: agentpoyo <drew.bentley@gmail.com>
INSTALL updates to reflect latest changes and requirements.
Refs: #1598
**Issue**

Updates for requirements for INSTALLATION Documentation

---

.github/workflows/actions.yml
sample-cnfs/k8s-multiple-processes/chart/templates/manifest.yml
spec/utils/kernel_introspection_spec.cr
src/tasks/utils/cluster_utils.cr
src/tasks/utils/kernel_instrospection.cr
src/tasks/workload/microservice.cr
src/tasks/workload/observability.cr
tools/cluster-tools/manifest.yml
utils/kubectl_client/kubectl_client.cr

[BUG] Update process search module to search using proc on the host fs
Refs: #1591
**Issue**

[BUG] Update process search module to search using proc on the host fs

---

spec/platform/observability_spec.cr
src/tasks/platform/observability.cr
src/tasks/utils/cloud_native_introspection.cr
src/tasks/utils/kernel_instrospection.cr
tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh

Update Platform Tests to Use The New Process Search Module.
Refs: #1581
**Issue**

Update Platform Tests to Use The New Process Search Module

---

.github/workflows/actions.yml
src/tasks/cluster_api_setup.cr
src/tasks/helmenv_setup.cr
src/tasks/kind_setup.cr
src/tasks/kubescape_setup.cr
src/tasks/litmus_setup.cr
src/tasks/sonobuoy_setup.cr
src/tasks/utils/kernel_instrospection.cr
src/tasks/utils/kyverno.cr
src/tasks/workload/state.cr
utils/kubectl_client/kubectl_client.cr

Fix SSL Failures for RHEL Systems  
Refs: #1464
**Issue**

Fix SSL Failures for RHEL Systems #1464 

---

.github/workflows/actions.yml
src/tasks/cluster_api_setup.cr
src/tasks/helmenv_setup.cr
src/tasks/kind_setup.cr
src/tasks/kubescape_setup.cr
src/tasks/litmus_setup.cr
src/tasks/sonobuoy_setup.cr
src/tasks/utils/http_helper.cr
src/tasks/utils/kernel_instrospection.cr
src/tasks/utils/kyverno.cr
src/tasks/utils/utils.cr
src/tasks/workload/observability.cr
src/tasks/workload/state.cr
utils/airgap/airgap.cr
utils/docker_client/docker_client.cr

Fix Bugs With SSL.
Refs: #1464
**Issue**

Fix Bugs with SSL for RHEL #1464 

---

src/tasks/kubescape_setup.cr

Fix TLS Bug with Kubescape.
Refs: #1464
**Issue**

Fix TLS Bug with Kubescape #1464

---

tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh

Refs: #1639
Update GitHub Runners image to conformance/github-runner:v2.296.2
**Issue**

[#1639] Update GitHub Runners image to conformance/github-runner:v2.296.2

---

shard.lock
src/tasks/prereqs.cr

kubectl client reenable offline warning

---

CNF_TESTSUITE_YML_USAGE.md

Updates to YML USAGE to include `helm_install_namespace` config option
Refs: #1672 
**Issue**

[DOC] CNF_TESTSUITE_YML_USAGE doc updates for `helm_install_namespace` config option

---

.github/workflows/actions.yml

Fix bug with Chaos Spec tests
Refs: #1703
**Issue**

Fix bug with Chaos Spec tests #1703

---

README.md

Signed-off-by: Lucina Stricko <lucina@vulk.coop>
remove UTC to meeting time
Refs: #NNN
**Issue**

remove UTC to meeting time

---

src/tasks/litmus_setup.cr

Signed-off-by: Akash Manohar <akash@akash.im>
check title
Refs: #1681 
**Issue**

Update Litmus version to 2.14.0

---

src/tasks/litmus_setup.cr
src/tasks/utils/http_helper.cr

Rocky Linux based on RHEL is throwing 
```SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed` when attempts to do `setup```
Refs: #1728
* [ x New Packet K8s cluster
**Issue**

Rocky Linux v8.x SSL Bug Fix #1728

---

.github/workflows/actions.yml

Refs: #1739 
Update Github Actions to resolve deprecation notices
**Issue**

[1739] Update Github Actions to resolve deprecation notices

---

shard.lock
src/tasks/utils/image_prepull.cr

Update test-suite to use fixed schedulable_node_list func .
Refs: cncf/cnf-testsuite#1745
**Issue**

Update test-suite to use fixed schedulable_node_list func 

---

src/cnf-testsuite.cr
src/cnf_testsuite.cr
src/tasks/utils/points.cr

Update code to use ReleaseManager::VERSION to fix duplicate logging bug
Refs: cncf/cnf-testsuite#1749
**Issue**

Update code to use ReleaseManager::VERSION to fix duplicate logging bug #1749

---

spec/platform/platform_spec.cr
spec/workload/configuration_spec.cr
src/cnf-testsuite.cr
src/tasks/platform/hardware_and_scheduling.cr
src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr
src/tasks/platform/security.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/task.cr
src/tasks/workload/mock_task.cr

tell user to install cnf before workload but not platform tests

---

src/tasks/workload/compatibility.cr

Increase_Decrease test was missing the essential emoji
Refs: #1690 
**Issue**

BUG #1690 Add essential emoji to increase decrease test

---

tools/github-runner/Dockerfile
tools/github-runner/create_runners.sh

Github runners needed to be updated to pick up jobs.
Refs: #1761 
**Issue**

Github Runner 2.303.0 ubuntu bionic image updates

---

.github/workflows/actions.yml
spec/platform/observability_spec.cr

Fix Bug with Kubestate Metrics install 
Refs: #1771
**Issue**

Fix Bug with Kubestate Metrics install #1771

---

.github/workflows/actions.yml

update to kind 0.17.0
https://github.com/kubernetes-sigs/kind/releases/tag/v0.17.0
Refs: #1532
**Issue**

update kind on runners

---

spec/workload/operator_spec.cr
spec/workload/registry_spec.cr
src/tasks/apisnoop_setup.cr
src/tasks/constants.cr
src/tasks/helmenv_setup.cr
src/tasks/kind_setup.cr
src/tasks/kubescape_setup.cr
src/tasks/litmus_setup.cr
src/tasks/platform/platform.cr
src/tasks/sonobuoy_setup.cr
src/tasks/utils/apisnoop.cr
src/tasks/utils/dockerd.cr
src/tasks/utils/kubescape.cr
src/tasks/utils/kyverno.cr
src/tasks/utils/system_information/clusterctl.cr
src/tasks/utils/system_information/curl.cr
src/tasks/utils/system_information/wget.cr
src/tasks/utils/utils.cr
src/tasks/workload/configuration.cr

Refs: #1782
When cnf-testsuite binary is moved to a location in PATH instead of running relative commands like `./cnf-testsuite`, then the binary fails to construct the path to tools directory.
This resolves any crashes that occur in tests due to not being able to find the tools directory.
* By default `$HOME/.cnf-testsuite` is used to download tools.
* This can be overridden by setting the ENV var `CNF_TESTSUITE_DIR`. This option is ideal for our pair machines or anyone that that needs the testsuite tools directory to be different.
> *These screenshots are to show the current issues when using the binary from the `main` branch.*
```
cni_compatible
container_sock_mounts
external_ips
selinux_options
sysctls
require_labels
latest_tag
default_namespace
```
The failures are reduced. So the …

[bug/1782] Resolves crashes when using binary in PATH directories

---

CONTRIBUTING.md

- remove out-of-date UTC time, keep Pacific Time only
Refs: n/a
**Issue**

Update CONTRIBUTING.md meeting time

---

spec/workload/microservice_spec.cr
src/tasks/workload/state.cr

#1829 update node drain to use chaos operator resource

---

src/tasks/workload/state.cr

#1829 removed forced test of rescheduling litmus node

---

CNF_TESTSUITE_YML_USAGE.md
RATIONALE.md
USAGE.md
docs/LIST_OF_TESTS.md
embedded_files/points.yml
spec/5g/core_spec.cr
spec/5g/ran_spec.cr
spec/utils/cnf_manager_spec.cr
src/tasks/workload/5g_validator.cr
src/tasks/workload/ran.cr

#1848 5g and RAN categories

---

README.md

Documentation: Change CNF WG hyperlink to CNF WG repo

---

src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr
src/tasks/workload/compatibility.cr
src/tasks/workload/configuration.cr

Unify reporting of skipped tests
Refs: #878 
**Issue**

Unify reporting of skipped tests #878

---

src/tasks/workload/compatibility.cr

This change updates emojis for helm_deploy.
Refs: #875 
**Issue**

emoji: Update emoji for helm_deploy

---

CONTRIBUTING.md

- Update community meeting time on CONTRIBUTING.md
- New time: weekly on Tuesdays at 8:00-9:00am Pacific Time
Refs: N/A
**Issue**

 Update community meeting time on CONTRIBUTING.md

---

src/tasks/workload/configuration.cr

This change adds emojis for ip_addresses test.
Refs: #868
**Issue**

emoji: Add emojis for ip_addresses test

---

sample-cnfs/sample_open5gs/cnf-testsuite.yml
sample-cnfs/sample_open5gs_no_auth/cnf-testsuite.yml
sample-cnfs/sample_srsran_ueauth_open5gs/cnf-testsuite.yml
src/tasks/utils/config.cr
src/tasks/utils/srsran.cr
src/tasks/utils/task.cr
src/tasks/utils/ueransim.cr
src/templates/ues-values-template.yml.ecr

This change updates pod to service in Open5gs configuration and samples.
Refs: #1860
**Issue**

amf: Change amf_pod_name to amf_service_name

---

spec/workload/configuration_spec.cr

Added pass/happy scenario spec test for increase_decrease_test. Tested by running all spec tests in configuration_spec.cr file. Also tested individually when running spec test with "increase_decrease_capacity" tag.
Refs: #1436
**Issue**

Added spec test for increase_decrease_capacity test

---

README.md

Readme updates for changed slack and meetings links (LFN).
This complements PR #1870 
Refs: #1873 
**Issue**

Readme updates for changed slack and meetings links (LFN)

---

README.md

Updated lines 1-63 to reflect CNTI focus areas and changed calendly link. To be continued for lines 64+
Re #1873 
**Issue**

Update README.md lines 1-63

---

config.yml
spec/platform/observability_spec.cr
spec/utils/utils_spec.cr
src/tasks/workload/configuration.cr

Fix bug with utils spec #1880
Refs:  #1880
**Issue**

Fix bug with utils spec #1880

---

src/tasks/workload/compatibility.cr

If capacity increase have failed - capacity decrease test should be skipped.
Add check for capacity increase before capacity decrease test. Redisign logging and error handling at the end of the test. Increase default wait_count_value to 45s
(was 30, which is too small)
Fixes: #1735 
Tested by running increase_decrease_capacity test on coredns cnf, both successfully and unsuccessfully (with lower wait time it fails)
Refs: #1735
**Issue**

increase_decrease_capacity: Skip decrease on unsuccessful increase

---

spec/workload/microservice_spec.cr
src/tasks/platform/hardware_and_scheduling.cr
src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr
src/tasks/platform/security.cr
src/tasks/utils/cnf_manager.cr
src/tasks/utils/cnf_manager_airgap.cr
src/tasks/utils/k8s_tshark.cr
src/tasks/utils/kyverno.cr
src/tasks/workload/5g_validator.cr
src/tasks/workload/configuration.cr
src/tasks/workload/mock_task.cr
src/tasks/workload/state.cr
utils/airgap/airgap.cr

Fixed syntax for named arguments. Also changed name of named argument, which had typo in microservice_spec.cr.
Tested by running all tests and individual spec tests. Found only one when running microservice_spec.cr -> fixed typo is part of this pull request.
Refs: #1864
**Issue**

Invalid named arguments syntax

---

src/tasks/platform/platform.cr

The platform:security was missing from the platform task dependency list.
Refs: #1871
**Issue**

Add platform:security to platform dependencies

---

src/tasks/ueransim_setup.cr

Need UERANSIM installation for test suite
Refs: #1806
**Issue**

#1806 ueransim cli setup now exists

---

USAGE.md

- update USAGE.md to reflect CNTI
- resolve typos
Ref #1914
**Issue**

update USAGE.md to reflect CNTI

---

src/tasks/ueransim_setup.cr

#1806 ueransim cli messaging now exists

---

embedded_files/points.yml
src/tasks/platform/hardware_and_scheduling.cr
src/tasks/platform/observability.cr
src/tasks/platform/platform.cr
src/tasks/platform/resilience.cr
src/tasks/platform/security.cr
src/tasks/workload/configuration.cr

Platform tests adapted to centralized result logging
Refs: #1861
**Issue**

Platform tests adapted to centralized result logging

---

src/tasks/workload/microservice.cr

Fix wrong description for zombie_handled

---

RATIONALE.md
USAGE.md
docs/LIST_OF_TESTS.md

Ref: #1924
Ref: #1925
Refs: #NNN
**Issue**

Adding sig_term_handled and zombie_handled to the docs

---

example-cnfs/envoy/README.md

Update envoy examples README
This PR will update documentation for envoy example cnf, so it will be aligned with installation and usage guide
Refs: #1951
**Issue**

Update envoy examples README

---

example-cnfs/coredns/README.md
example-cnfs/ip-forwarder/README.md
example-cnfs/linkerd2/README.md
example-cnfs/nsm/README.md
example-cnfs/pantheon-nsm-nat/README.md
example-cnfs/vpp-3c2n-csp-use-case/README.md

This PR will update documentation for all example cnfs, so it will be aligned with installation and usage guide.
Refs: #1951
**Issue**

Update all cnf examples README

---

embedded_files/points.yml
spec/utils/cnf_manager_spec.cr
src/tasks/cert/cert.cr
src/tasks/cert/cert_microservice.cr
src/tasks/cert/cert_state.cr
src/tasks/constants.cr

Ref: #1931
Ref: #1932
Refs: #NNN
**Issue**

Adapt cert tests for CNTI certification V2.0

---

MAINTAINERS.md

In this change are added contributors from Tietoevry to MAINTAINERS.md.

Add new contributors to MAINTAINERS.md

---

src/tasks/workload/reliability.cr

Removing dev logging output using puts or replacing with Log.info where needed.
Refs: #1974
**Issue**

Update reliability.cr to remove unnecessary log output

---

spec/workload/compatibility_spec.cr
spec/workload/configuration_spec.cr

- move spec for increase_decrease_capacity from configuration_spec.cr to compatibility_spec.cr
**Issue**

Change location of increase_decrease_capacity task

---

spec/utils/cnf_manager_spec.cr
spec/utils/utils_spec.cr

Adding local helm binary for spec tests 
Refs: #1909
- [ x] No updates required.
**Issue**

Issue 1909# Adding local helm binary for spec tests

---

src/tasks/utils/points.cr

Timer in results now human readable

---

src/templates/chaos_templates/pod_memory_hog.yml.ecr

Fix Litmus Pod Memory Hog Test
Refs: cnti-testcatalog/testsuite#2019
**Issue**

Fix bug with Litmus Pod Mem Test cnti-testcatalog/testsuite#2019

---

USAGE.md
src/tasks/cert/cert.cr
src/tasks/cert/cert_compatibility.cr
src/tasks/cert/cert_configuration.cr
src/tasks/cert/cert_microservice.cr
src/tasks/cert/cert_observability.cr
src/tasks/cert/cert_resilience.cr
src/tasks/cert/cert_security.cr
src/tasks/cert/cert_state.cr
src/tasks/cert/cert_utils.cr
src/tasks/utils/utils.cr

Adds exclude="... ..." parameter for cert tasks in place of the previous ~... exclusion pattern.
Minor refactor of cert tasks.
Check issue for more info.
Refs: #2048
Build and functionality tested, documentation added.

cert: Add test exclusion in cert tasks

---

USAGE.md

It fixes the documentation by cleaning the latest tests removed [1].
[1] https://github.com/cnti-testcatalog/testsuite/commit/981182ad0bf059186f8a1fbb593d3bd39e00e0a0
Refs: #1649

Remove deprecated capacity tests in docs

---

USAGE.md
spec/platform/observability_spec.cr
spec/workload/operator_spec.cr
src/tasks/chaos_mesh_setup.cr
src/tasks/kind_setup.cr
src/tasks/litmus_setup.cr
src/tasks/platform/resilience.cr
src/tasks/utils/apisnoop.cr
src/tasks/utils/chaos_templates.cr
src/tasks/utils/timeouts.cr
src/tasks/utils/utils.cr
src/tasks/workload/compatibility.cr
src/tasks/workload/configuration.cr
src/tasks/workload/microservice.cr
src/tasks/workload/reliability.cr
src/tasks/workload/state.cr

Add common function to run a code block with a timeout. Add several global timeouts for different tasks, which can be configured via environment variables.
Several small fixes and refactoring.
Refs: #335
build, test functionality on increase_decrease_capacity test.
Bug-fix, redesign
No updates required, ENV variables names could be added somewhere, but the documentation doesn't keep these.
**Issue**

timeouts: Redesign and unify timeouts

---

.github/workflows/actions.yml

Update registry mirror to UNH infrastructure

---

shard.lock
shard.yml

Bump k8s_netstat to fix database timeouts

---

spec/workload/installability_spec.cr
src/tasks/workload/compatibility.cr

Refactors code to not use functions that will be removed with the new installation process introduced in step 6.
Simultaneously the code has been prepared to expect multiple deployments in a single CNF which is part of the #2169 issue.
Refs: #2153
**Issue**

Feat: CNF Installation (5.4) Update compatibility tests

---

.github/workflows/actions.yml

cat prints warnings as deserved.

typo: close cat call

---

.github/workflows/actions.yml

https://github.com/kubernetes-sigs/kind/releases/tag/v0.25.0

Update Kind to v0.25.0

---

.github/workflows/actions.yml

Remove shared_database2 from actions
